compel/arch/aarch64/src/lib/infect.c
compel/arch/arm/src/lib/infect.c

Hi,
When using the musl libc on ARM, the compilation fails with the following messages:
```
armv7a-hardfloat-linux-musleabi-gcc -c -O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -march=armv7-a -Wall -Wformat-security -DCONFIG_ARMV7 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -iquote include/  -iquote images/ images/netdev.pb-c.c -o images/netdev.o
compel/arch/arm/src/lib/infect.c: In function ‘sigreturn_prep_regs_plain’:
compel/arch/arm/src/lib/infect.c:53:2: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
memcpy(&aux->vfp.ufp.fpregs, &fpregs->fpregs, sizeof(aux->vfp.ufp.fpregs));
^
compel/arch/arm/src/lib/infect.c:53:2: warning: incompatible implicit declaration of built-in function ‘memcpy’
compel/arch/arm/src/lib/infect.c:53:2: note: include …
```

compel: add missing header required by musl on ARM

---

criu/cr-dump.c
criu/image.c
criu/include/crtools.h
criu/mem.c

A set of images from criu dump can be used as a previous point, when we
are doing snapshots. In this case, each point contains a full set of
images.
https://github.com/checkpoint-restore/criu/issues/479
v2: return -1 if invertory_save_uptime failed
Cc: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Signed-off-by: Andrei Vagin <avagin@virtuozzo.com>
Reviewed-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Signed-off-by: Andrei Vagin <avagin@virtuozzo.com>

inventory: save dump_uptime for criu dump if track_mem is set

---

criu/cr-service.c

The function parse_options() should return an integer 0, 1 or 2, where:
* 0 := Success
* 1 := Failure
* 2 := CRIU should display help text
The current behaviour always creates a warning message which shows the return value of that function. With this change only the values that are different than 0 (Success) will be logged.

cr-service: Don't log return value of parse_options()

---

criu/crtools.c

The `show` and `exec` commands have been deprecated for some time, and it is unlikely to be called by users. It would be better to move them the end of the sequence of if-statements.

 crtools: Move checks for deprecated commands at the end

---

criu/mount.c

Use `realloc()` to change the size of the memory block pointed to by `info->source` instead of allocating new memory area and releasing the old one. If `info->source` is NULL then the call is equivalent to `malloc(size)`.

mount: realloc info->source when resolve ext mount

---

lib/c/criu.c
lib/c/criu.h

This pull request consists of two commits. The first one contains missing `strudp()` checks (as requested in #602)
The other commit is a proposal that simplifies the c-interface, as it does not require to call `*set_service_comm()` anymore.
I think it would be a good idea to omit these calls in favour of `*set_service_address()`, `*set_service_fd()` or `*set_service_binary()`. As these calls already set the intention of the library user.
And it can not happen that the user sets the wrong service_comm value to the `set_service_*()` calls.
E.g. If `*set_service_comm()` was set to socket, but a string to the binary was given
via `*set_service_binary()` it would probably cause to undefined behavior that can be prevented by a better library design.

c-lib: added strdup-null checks, simplify the interface

---

criu/img-remote.c

When an interrupt signal ([even `SIGWINCH` when `strace` is used](https://unix.stackexchange.com/a/465194)) is received while epoll_wait() sleeps, it will return a value of -1 and set errno to `EINTR`, which is not an error and should be ignored.

remote: Ignore interupt signals

---

criu/config.c
criu/crtools.c

The `-R` is short for `--leave-running`, which is a boolean option and does not require an argument.
From getopt(3) man page:
> optstring is a string containing the legitimate option characters. If such a character is followed by a colon, the option requires an argument, ...

Fix -R option

---

criu/util.c

From man inet_pton(3):
inet_pton() returns 1 on success (network address was successfully
converted). 0 is returned if src does not contain a character
string representing a valid network address in the specified
address family. If af does not contain a valid address family,
-1 is returned and errno is set to EAFNOSUPPORT.
We can assume that the return value is 1 or 0 (because `af` is set to AF_INET4 or AF_INET6), therefore `errno` will not be set.
If a user attempts to bind a server using invalid network address the following error message will be shown:
Bad server address: Success
Which is not very clear, with this change the error message will look like this:
Invalid server address "localhost". The address must be in IPv4 or IPv6 format.

util: Don't log errno on bad server address

---

criu/page-xfer.c

When the `--ps-socket` option is used with page-server, instead of `--address` and `--port`, this message would appear as:
(00.028440) Disconnect from the page server (null):0

page-xfer: Don't log addr/port on disconnect

---

lib/py/cli.py

Running crit with python2 gives following minimal help message:
$ crit/crit
usage: crit [-h] {decode,encode,info,x,show} ...
crit: error: too few arguments
Using a python3 only system crit shows the following error:
$ crit/crit
Traceback (most recent call last):
File "crit/crit", line 6, in <module>
cli.main()
File "/home/criu/crit/pycriu/cli.py", line 334, in main
opts["func"](opts)
KeyError: 'func'
Using this patch the python3 output changes to:
$ crit/crit
usage: crit [-h] {decode,encode,info,x,show} ...
crit: error: the following arguments are required: parser
The help message is not 100% the same but almost. Better than a
traceback in any way.
Signed-off-by: Adrian Reber <areber@redhat.com>

crit: display help message when using python3

---

criu/crtools.c
criu/img-cache.c
criu/img-proxy.c
criu/include/img-remote.h
criu/include/util.h
criu/page-xfer.c
criu/util.c

There is no need to pass the values for address and port as arguments when creating a TCP server. The external `opts` object, which provides `opts.addr` and `opts.port`, is accessible in all components that require these values.

util: Don't pass address/port as arguments

---

test/zdtm/static/socket-tcp-skip-in-flight.c

The server socket is marked as non-blocking, and if the client doesn't connect, `accept()` will fail with `EAGAIN` (or `EWOULDBLOCK`), which is not an error, and we should try again.

socket-tcp-skip-in-flight: Don't fail on EAGAIN

---

criu/img-cache.c
criu/img-proxy.c
criu/img-remote.c
criu/include/img-remote.h

Rename `local_req_fd` and `proxy_to_cache_fd` to `local_sk` and `remote_sk`, because they are shorter and more similar to the name `page_server_sk` which is used in `criu/page-xfer.c`.

remote: Rename 'local_req_fd' and 'proxy_to_cache_fd'

---

criu/pagemap.c

The variable `len` is used only to calculate the value of `end`. We already have the static inline function `pagemap_len()`, which can be used, instead.

seek_pagemap: Use pagemap_len()

---

criu/util.c

When `saddr.ss_family` is `AF_INET6` we should cast `&saddr` to `(struct sockaddr_in6 *)`.

util: Fix addr casting for IPv4/IPv6 in autobind

---

criu/config.c

When the `--ps-socket` option is specified the provided file descriptor of a socket will be reused for incoming TCP connection. In such case the `--address` and `--port` options are ignored.

config: Add msg for obsolete use of port/address

---

criu/img-remote.c
criu/include/util.h
criu/util.c

Combine the functionality of `socket_set_non_blocking()` and `socket_set_blocking()` into a new function, called `fd_set_nonblocking()`, and move it in `criu/util.c` to enable reusability throughout the code base.

util: Introduce fd_set_nonblocking()

---

criu/cr-service.c
images/rpc.proto
test/others/rpc/test.py
test/others/rpc/version.py

In rpc.proto the interface to query the CRIU version number uses major
and minor as keywords. This creates errors when using the RPC
definitions with C++: https://github.com/checkpoint-restore/criu/issues/625
In this commit the fields are renamed from major to major_number and
from minor to minor_number.
For existing programs using the RPC protobuf definition this should be a
transparent change. Only for programs importing the latest rpc.proto it
will require code changes.
Signed-off-by: Adrian Reber <areber@redhat.com>

Rename version protobuf RPC members

---

criu/img-remote.c
criu/include/img-remote.h

Combine the macro constants `DUMP_FINISH` and `RESTORE_FINISH`, into a single one, called `FINISH`.
In addition, replace the key-word strings used by the above-mentioned constants, and `NULL_SNAPSHOT_ID`, with a `\0` character that will be used to indicate a "finish" message.

remote: Use \0 as indicator for a "finish" msg

---

criu/files.c

Support for printing early log messages was recently added, which makes the
comment below no longer relevant.
```
We can't print diagnostics messages in this function because the
log file isn't initialized yet.
```

Remove irrelevant comment

---

compel/arch/x86/src/lib/include/uapi/asm/fpu.h
compel/arch/x86/src/lib/include/uapi/asm/sigframe.h
criu/arch/x86/include/asm/restore.h
criu/sk-unix.c
test/zdtm/static/binfmt_misc.c

This fixes errors on current Fedora rawhide with gcc 9.
Most of the changes is to remove `__packed` to remove errors like:
```
error: taking address of packed member of ‘union <anonymous>’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
```
CC: @cyrillos @0x7f454c46 
There have similar changes last year for gcc 8 but that was more adding alignments. Not sure if removing `__packed` is correct.
This also fixes:
```
CC       criu/cr-restore.o
In file included from criu/include/restore.h:6,
from criu/cr-restore.c:91:
criu/cr-restore.c: In function ‘sigreturn_restore’:
criu/arch/x86/include/asm/restore.h:10:2: error: listing the stack pointer register ‘rsp’ in a clobber list is deprecated [-Werror=deprecated]
10 |  asm volatile(       \
|  ^~~
```
and:
```
CC …
```

criu: fix gcc9 rawhide compilation errors

---

criu/files-reg.c
test/zdtm/static/Makefile
test/zdtm/static/pid_file.c

The pathname passed to access() in check_path_remap() should
not include the "." prefix present in link names.
Signed-off-by: Ashutosh Mehra <asmehra1@in.ibm.com>

Fix pathname passed to access()

---

scripts/travis/docker-test.sh

The flag `--security-opt` doesn't use the colon separator (:) anymore to divide keys and values, instead it uses the equal symbol (=) for consistency with other similar flags, like `--storage-opt`.
Deprecated in release: v1.11.0
Target for removal in release: v17.06
https://docs.docker.com/engine/deprecated/

docker-test: Fix deprecated security-opt format

---

criu/include/util.h
criu/util.c

The print_data() function was part of the deprecated (and removed)
'show' action, and it was moved in util.c with the following commit:
a501b4804b3c95e1d83d64dd10ed95c37f0378bb
The 'show' action has been deprecated since 1.6, let's finally drop it.
The print_data() routine is kept for yet another (to be deprecated too)
feature called 'criu exec'.
The criu exec feature was removed with:
909590a3558560655c1ce5b72215efbb325999ca
Remove criu exec code
It's now obsoleted by compel library.
Maybe-TODO: Add compel tool exec action?
Therefore, now we can drop print_data() as well.

util: Remove deprecated print_data() routine

---

scripts/build/Dockerfile.s390x.hdr
scripts/build/extract-deb-pkg

And get qemu-static from the 18.04 LTS Ubuntu repos.
https://github.com/checkpoint-restore/criu/issues/652

scripts/build: use the last stable release for s390

---

criu/cr-restore.c
criu/include/restorer.h
criu/pie/restorer.c

Restoring a multi-threaded process with CRIU's SELinux support fails
because SELinux does not always support changing the process context of
a multi-threaded process.
Reading the man-page for setcon(), to change the context of a running
process, it states that changing the SELinux context of a multi-threaded
process can only work 'if the new security context is bounded by the old
security context'.
To be able to restore a process without the need to have 'the new
security context [] bounded by the old security context', this sets the
SELinux process context before creating the threads. Thus all threads
are created with the process context of the main process.
Signed-off-by: Adrian Reber <areber@redhat.com>

restore: support restoring threads with SELinux

---

images/rpc.proto

We want to commit --check-mounts feature to vz-criu. But to maintain
image level compatibility between ms-criu and vz-criu one shouldn't use
the same field id for different data. So add a comment that these id is
reserved.

rpc: reserve number for --check-mounts feature

---

test/zdtm.py

[imp.load_source()](https://docs.python.org/2.7/library/imp.html#imp.load_module) has been deprecated. The recommended alternative API for loading a module is [exec_module()](https://docs.python.org/3.4/library/importlib.html#importlib.abc.Loader.exec_module).

zdtm: Replace imp module with importlib

---

compel/arch/x86/src/lib/cpu.c

As Hygon Dhyana can reuse most AMD CPU support codes, add Hygon CPU Vendor ID checking in compel_cpuid().
Signed-off-by: hygonsoc <hygonsoc@gmail.com>

add Hygon CPU support

---

criu/cr-restore.c
criu/include/lsm.h
criu/include/restorer.h
criu/lsm.c
criu/pie/restorer.c
criu/sk-inet.c
criu/sockets.c
images/creds.proto
images/fdinfo.proto
test/zdtm/static/Makefile
test/zdtm/static/selinux00.c
test/zdtm/static/selinux01.c
test/zdtm/static/selinux01.checkskip
test/zdtm/static/selinux01.desc
test/zdtm/static/selinux01.hook
test/zdtm/static/selinux02.c
test/zdtm/static/selinux02.checkskip
test/zdtm/static/selinux02.desc
test/zdtm/static/selinux02.hook

If restoring a process in a SELinux environment, sockets created during restore must also have the correct labels. This sets the label for all sockets to the label the process had during restore.
As with all SELinux related labels, this assumes that all processes and sockets restored are using the same label (that is what is currently done for SELinux containers with Podman).

This also adds the correct labels to sockets during restore

---

criu/lsm.c

This fixes following compiler error:
```
criu/lsm.c: In function ‘dump_xattr_security_selinux’:
criu/include/log.h:51:2: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
51 |  print_on_level(LOG_ERROR,     \
|  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
52 |          "Error (%s:%d): " LOG_PREFIX fmt,  \
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
53 |          __FILE__, __LINE__, ##__VA_ARGS__)
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
criu/lsm.c:166:3: note: in expansion of macro ‘pr_err’
166 |   pr_err("Reading xattr %s to FD %d failed\n", ctx, fd);
|   ^~~~~~
```

lsm: fix compiler error on Fedora 30

---

criu/sk-inet.c
criu/sockets.c
images/sk-opts.proto
test/zdtm/static/Makefile
test/zdtm/static/socket_udp-broadcast.c

Inet sockets may have broadcasting capability enabled. The `SO_BROADCAST` option is used to enable this feature. It is a Boolean flag option, which is defined, fetched, and set with the int data type. During
checkpoint, CRIU should detect the state of this flag, and during restore, it should be set appropriately.
Fixes #673

sk-inet: restore SO_BROADCAST option

---

criu/config.c
criu/include/util.h
criu/uffd.c
criu/util.c

When running lazy-pages in daemon mode, file descriptor 3 is reused after fork to keep the opened UNIX socket. However, fd 3 happens to correspond to the opened image directory, and therefore this causes the following error:
```sh
$ criu lazy-pages -D <PATH> --page-server --address <ADDR> --port <PORT> -d
...
(06.835596) Error (criu/image.c:470): Unable to open pagemap-1.img: Not a directory
(06.835855) Error (criu/uffd.c:773): uffd: 1-7: Failed to open pagemap
```

util: cr_daemon: Drop keep_fd argument

---

criu/crtools.c
criu/include/log.h
criu/log.c

When `check_options()` exits with an error (return value != 0) the logging is not yet initialised, and therefore the error messages are not printed out.
Since this affects only command-line usage, and only when `check_options()` reports an error, flush the early log messages to standard error.

crtools: Print error messages from check_options()

---

lib/py/images/pb2dict.py

From the python-six module is used only six.string_types in the is_string() function. An alternative solution is to use basestring with additional if statement for Python 3 compatibility.
This change avoids the dependency on the six module.
However, this module is required by junit_xml and it is not listed as a dependency in the CentOS 7 package python2-junit_xml.

python: Drop six dependency

---

scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.centos
scripts/build/Dockerfile.fedora.tmpl
scripts/nmk/scripts/tools.mk
scripts/travis/travis-tests

The final release of [asciidoc](https://github.com/asciidoc/asciidoc) was on Sep 29, 2017 and the development is continued under [asciidoctor](https://github.com/asciidoctor/asciidoctor).
In commit 0493724 was added support for this tool by introducing `USE_ASCIIDOCTOR`. However, using asciidoctor by default might be a better option.
With this change CRIU will use asciidoctor if installed. Otherwise, it will fallback to asciidoc.

make: Use asciidoctor by default

---

criu/arch/aarch64/include/asm/restore.h

Since gcc version 9.1 was added the [restriction](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=9d1cdb749a1) that the clobber list of an inline assembly should not contain the stack pointer register.
In commit 901f5d4 have been fixed most of the build failures related to this gcc restriction. In this patch is resolved a build error that occurs only on aarch64.

aarch64: Remove stack pointer from clobber list

---

test/zdtm.py

In some cases the stats-dump file can be missing, so do not
crash the whole zdtm.py in this case.
https://ci.openvz.org/job/CRIU/job/criu-live-migration/job/criu-dev/2362/console
Signed-off-by: Pavel Emelyanov <xemul@virtuozzo.com>

zdtm: Check stats file presence before reading

---

Documentation/Makefile
Documentation/compel.txt

Resolves #349
Signed-off-by: Harshavardhan Unnibhavi <hvubfoss@gmail.com>

Documentation: Create man page for libcompel

---

criu/files-reg.c
criu/seize.c
criu/sk-inet.c
criu/util.c

I have been running some code analysis against criu 3.12 and this fixes a few of the reported errors.
All tests are still successful, but as this touches many different parts of criu I am not I did not break something.

Fixes for coverity and clang warnings

---

criu/image.c
criu/mem.c
criu/pagemap.c
test/zdtm.py

It is inspired by the discussion about inotify fix:
https://github.com/checkpoint-restore/criu/pull/728#issuecomment-506929427
From one point of view, warnings might be important to understand why we
detect some visible change in the environment after c/r-ing the process,
and if this change is expected or not. So we should add "Warn" messages
to the output.
From over point, these warnings if they are expected, can spoil our
final logs with a lot of unnecessary details.
I see warnings from dedup when it tries to find region in parent hit the log limits:
```
From: https://api.travis-ci.org/v3/job/552665729/log.txt
The job exceeded the maximum log length, and has been terminated.
```

zdtm: make grep_errors also grep warnings

---

test/zdtm.py

In zdtm.py, the page size is hardcoded as 4096, but on ppc64le, is is equal
to 64K and all test fail with errors like this:
ERROR: bad page counts, stats = 13 real = 208(0)

zdtm: use a proper page size for the host

---

contrib/debian/dev-packages.lst
criu/Makefile.packages
scripts/build/Dockerfile.tmpl
scripts/travis/travis-tests

The `libprotobuf-c0-dev` virtual package is no longer available
in Debian Buster, but is provided by `libprotobuf-c-dev`, which
is available.
https://packages.debian.org/stretch/libprotobuf-c0-dev
> Virtual Package: libprotobuf-c0-dev
>
> This is a virtual package. See the Debian policy for a definition of virtual packages.
>
> Packages providing libprotobuf-c0-dev
> libprotobuf-c-dev
> Protocol Buffers C static library and headers (protobuf-c)

Replace libprotobuf-c0-dev with libprotobuf-c-dev

---

lib/Makefile
lib/c/criu.h

Including the macros that provide information about the version of CRIU is required by projects that use libcriu to preserve backward compatibility.
Closes #738

make: Insert version macros in criu.h

---

scripts/build/Dockerfile.fedora.tmpl
scripts/build/Makefile

This removes python2 from Fedora based Dockerfiles as it is not needed and will be removed from future Fedora releases. This PR also adds an environment variable to use other container runtimes for testing.

Remove python2-future from Fedora Dockerfiles

---

lib/py/images/pb2dict.py
scripts/build/Dockerfile.fedora.tmpl
scripts/travis/travis-tests
soccr/test/run.py
test/check_actions.py
test/others/ext-tty/run.py
test/others/mounts/mounts.sh
test/others/rpc/config_file.py
test/others/rpc/errno.py
test/others/rpc/ps_test.py
test/others/rpc/restore-loop.py
test/others/rpc/setup_swrk.py
test/others/rpc/test.py
test/others/rpc/version.py
test/others/shell-job/run.py

In https://github.com/checkpoint-restore/criu/pull/751 have been removed some of the Python 2 packages that are installed in Fedora Dockerfiles. There are a few necessary changes to allow the tests to work in environment with Python 3 only.
cc @adrianreber

scripts: Remove Python 2 dependency for Fedora tests

---

test/zdtm/static/netns_sub.c
test/zdtm/static/netns_sub.desc
test/zdtm/static/netns_sub_veth.c
test/zdtm/static/netns_sub_veth.desc

This is needed to workaround the problem with "ip route save":
(00.113153) 	Running ip route save
Error: ipv4: FIB table does not exist.

test: bring the lo interface up in each network namespace

---

.travis.yml
scripts/travis/Makefile
scripts/travis/podman-test.sh

This adds the same tests currently running for docker also for podman.
In addition this also tests podman --export/--import (migration) support.

travis: add podman test case

---

criu/include/files-reg.h

The function `clear_ghost_files()` has been removed in commit b11eeea.

files-reg: Drop clear_ghost_files() prototype

---

scripts/build/Dockerfile.fedora.tmpl

This change was introduced with c75cb2b and it is no longer necessary.

scripts: Drop Fedora 28/rawhide fix

---

scripts/build/Dockerfile.fedora.tmpl

The following tests fail in Fedora rawhide because `/usr/bin/diff` is not installed.
* zdtm/static/bridge(ns)
* zdtm/static/cr_veth(uns)
* zdtm/static/macvlan(ns)
* zdtm/static/netns(uns)
* zdtm/static/netns-nf(ns)
* zdtm/static/sit(ns)

travis: Install missing diffutils dependency

---

criu/cgroup.c

1) s/\s*$//
2) fix snprintf out of bound access

cgroup: fixup nits

---

criu/page-pipe.c

When performing pre-dump we continuously increase the page-pipe size to
fit the max amount memory pages in the pipe's buffer. However, we never
actually set the pipe's buffer size to max. By doing so, we can reduce
the number of pipe-s necessary for pre-dump and improve the performance
as shown in the example below.
For example, let's consider the following process:
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
void main(void)
{
int i = 0;
void *cache = calloc(1, 1024 * 1024 * 1024);
while(1) {
printf("%d\n", i++);
sleep(1);
}
}
stats-dump before this change:
frozen_time: 123538
memdump_time: 95344
pages_scanned: 262721
pages_written: 262169
page_pipes: 513
page_pipe_bufs: 519
stats-dump after this change:
frozen_time: 83287
memdump_time: 54587
pages_scanned: 262721 …

page-pipe: Resize up to PIPE_MAX_SIZE

---

criu/cgroup.c

cgroup: fix cg_yard leak on error path in prepare_cgroup_sfd

---

criu/cr-service.c
criu/include/protobuf.h
criu/protobuf.c

RPC messages are have fairly small size and using space on the stack might be a better option. This change follows the pattern used with do_pb_read_one() and pb_write_one().

service: Use space on stack for msg buffer

---

scripts/travis/travis-tests
test/others/libcriu/Makefile
test/others/libcriu/run.sh

libcriu tests are currently broken. This patch fixes couple of
issues to allow the building and running libcriu tests.
1. lib/c/criu.h got updated to include version.h which is present
at "criu/include", but the command to compile libcriu tests is not
specifying "criu/include" in the path to be searched for header
files. This resulted in compilation error.
This can be fixed by adding "-I ../../../../../criu/criu/include"
however it causes more problems as "criu/include/fcntl.h" would now
hide system defined fcntl.h
Solution is to use "-iquote ../../../../../criu/criu/include"
which applies only to the quote form of include directive.
2. Secondly, libcriu.so major version got updated to 2 but
libcriu/run.sh still assumes verion 1. Instead of just updating the
version in libcriu/run.sh to …

Couple of fixes to build and run libcriu tests

---

.travis.yml
scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.centos
scripts/build/Makefile
scripts/travis/travis-tests

With the newly introduced aarch64 at Travis it is possible for the CRIU test-cases to switch to aarch64.
Travis uses unprivileged LXD containers on aarch64 which blocks many of the kernel interfaces CRIU needs. So for now this only tests building CRIU natively on aarch64 instead of using the Docker+QEMU combination.
All tests based on Docker are not working on aarch64 is there currently seems to be a problem with Docker on aarch64. Maybe because of the nesting of Docker in LXD.
The problem with Docker on LXD was reported here: https://travis-ci.community/t/docker-container-download-fails/5674/2
Once this is fixed I will try to move all other arm32/arm64 related tests to native hardware.

travis: start to use aarch64 hardware

---

test/javaTests/README.md
test/javaTests/pom.xml
test/javaTests/src/org/criu/java/tests/CheckpointRestore.java
test/javaTests/src/org/criu/java/tests/FileRead.java
test/javaTests/src/org/criu/java/tests/Helper.java
test/javaTests/src/org/criu/java/tests/ImgFilter.java
test/javaTests/test.xml

As noted in issue #820, we are adding sample Java tests to check CRIU APIs. Currently this only checks File-based CRIU APIs. Based on feedback we can add the remaining Java tests that we have been working on.
These tests take 1.5 minutes when run the first time as maven needs to build its repo. Subsequent runs on the same machine will take about 6 seconds as the required files will be cached locally.

Add Java-based CRIU Tests.

---

criu/cr-dump.c
criu/parasite-syscall.c
images/opts.proto
images/rlimit.proto
images/sa.proto
lib/py/images/pb2dict.py

Display rlimits type and signal number when decoding
core-<pid>.img file using crit
Fixes #774 
Signed-off-by: Ashutosh Mehra <asmehra1@in.ibm.com>

Display rlimits type and signal number

---

criu/include/namespaces.h
criu/mount.c
criu/namespaces.c
criu/net.c

Patches 1-4 do a minor cleanup of mounts code.
Patch 5 brings in the option --check-mounts on restore to check that at
the end of restore we have properly restored tree of mounts in each
mount namespace of the container.
We've seen cases of container migration passing fine without error, but
actually some mounts changed their attributes or even some new mounts
appeared. Potentially these "inaccuracies" during restore can accumulate
over several migrations of the same container, and we will finally see
unexpected crap in mounts and won't be able to find out the initial
problem. With --check-mounts we will catch initial problem and fix it.

mount: check mounts after restoring

---

criu/proc_parse.c

Before this change CRIU would checkpoint all controllers, even the ones not specified in --cgroup-dump-controller. That becomes a problem if there's a cgroup controller on the checkpointing machine that doesn't exist on the restoring machine even if CRIU is instructed not to dump that controller. After that change everything works as expected.

Checkpoint only specified controllers

---

scripts/travis/travis-tests

Kernels 5.4 and higher will restrict availability of UFFD_EVENT_FORK only
for users with SYS_CAP_PTRACE. This prevents running --lazy-pages tests
with 'uns' flavor.
Disable 'uns' for lazy pages testing in travis for newer kernels.

travis: exclude uns tests for lazy-pages on newer kernels 

---

Documentation/criu.txt
criu/cr-restore.c
criu/mount.c
test/zdtm.py

When restoring a runc container with enabled user namespace CRIU fails to mount the specified root directory because the path is under `/run/runc` which is inaccessible to unprivileged users.

mount: Bind-mount root via userns_call

---

test/zdtm.py

It doesn't require to create a temporary directory and mount the proc file system in it.

mount: use new mount API to open the proc file system

---

criu/net.c
images/netdev.proto
test/zdtm/lib/Makefile
test/zdtm/lib/sysctl.c
test/zdtm/lib/sysctl.h
test/zdtm/static/Makefile
test/zdtm/static/netns_sub_sysctl.c
test/zdtm/static/netns_sub_sysctl.desc

This patch set resolves problem of changing sysctl net.unix.max_dgram_qlen value after C/R

unix sysctl max-dgram-qlen preserve

---

scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.openj9-alpine

The py-future package [has been renamed to py3-future](https://git.alpinelinux.org/aports/commit/main?id=316d44abaed13964e97eb43c095cd1b64e3943ad) and py2 package for yaml [has been dropped](https://git.alpinelinux.org/aports/commit/main?id=e369c1fd7707a73f2c3e2b11b613198d9a4106de).

scripts: alpine: Install py2 packages with pip

---

criu/include/sk-inet.h
criu/sk-inet.c
criu/sk-tcp.c
criu/sockets.c
images/sk-opts.proto
test/zdtm/static/Makefile
test/zdtm/static/socket-tcp-keepalive.c

This PR implements checkpoint/restore support for `SO_KEEPALIVE`, `TCP_KEEPIDLE`, `TCP_KEEPINTVL` and `TCP_KEEPCNT` socket options.

Add checkpoint/restore support for TCP keepalive

---

.travis.yml
scripts/travis/Makefile
scripts/travis/docker-test.sh
scripts/travis/podman-test.sh

Podman Ubuntu packages are now available via OBS and no longer via PPA.

Fix tests on Ubuntu

---

scripts/build/Dockerfile.alpine

Now that Python 2 has officially reached its end of life also switch the Alpine based test to Python 3.

travis: switch alpine to python3

---

compel/arch/ppc64/src/lib/include/uapi/asm/sigframe.h
criu/arch/ppc64/include/asm/restore.h

Compiling 'criu-dev' on Fedora 31 gives two errors about wrong clobber lists:
```
compel/include/uapi/compel/asm/sigframe.h:47:9: error: listing the stack pointer register ‘1’ in a clobber list is deprecated [-Werror=deprecated]
criu/arch/ppc64/include/asm/restore.h:14:2: error: listing the stack pointer register ‘1’ in a clobber list is deprecated [-Werror=deprecated]
```
There was also a bug report from Debian that CRIU does not build because of this.
Each of these errors comes with the following note:
```
note: the value of the stack pointer after an ‘asm’ statement must be the same as it was before the statement
```
As far as I understand it this should not be a problem in this cases as the code never returns anyway.
Running zdtm very seldom fails during `zdtm/static/cgroup_ifpriomap` …

ppc64le: remove register '1' from clobber list

---

images/core.proto

To ensure consistency of runtime environment processes within a container need to see same start time values over suspend/resume cycles. We introduce new field to the core image structure to store start time of a dumped process. Later same value would be restored to a newly created task. In future the feature is likely to be pulled here, so we reserve field id in the core's protobuf descriptor.

image: core -- Reserve start_time field

---

scripts/travis/podman-test.sh

We are running each podman test loop 50 times. This takes more than 20 minutes in Travis. Reduce both test loops to only run 20 times.

travis: reduce the number of podman tests

---

compel/arch/arm/plugins/std/syscalls/syscall.def
compel/arch/ppc64/plugins/std/syscalls/syscall-ppc64.tbl
compel/arch/s390/plugins/std/syscalls/syscall-s390.tbl
compel/arch/x86/plugins/std/syscalls/syscall_32.tbl
compel/arch/x86/plugins/std/syscalls/syscall_64.tbl
compel/plugins/include/uapi/std/syscall-types.h
criu/arch/aarch64/include/asm/restorer.h
criu/arch/arm/include/asm/restorer.h
criu/arch/ppc64/include/asm/restorer.h
criu/arch/s390/include/asm/restorer.h
criu/arch/x86/include/asm/restorer.h
criu/clone-noasan.c
criu/cr-check.c
criu/cr-restore.c
criu/include/clone-noasan.h
criu/include/kerndat.h
criu/include/restorer.h
criu/include/rst_info.h
criu/include/sched.h
criu/kerndat.c
criu/pie/restorer.c

This is my first attempt to use the newly introduced clone3() with set_tid to replace CRIU's use of ns_last_pid.
My current test case is a simple threaded process which can be restored using the changes in this PR.
This is still work in progress and a request for comments. I am not sure if I did the whole child handling correct so please have close look at these changes. I am especially unsure about the child stack setup.
This is currently still x86_64 only and once this is working I would start looking at the other architectures.
One very nice result of clone3() with set_tid is that by no longer using ns_last_pid, newly created processes after running CRIU are using different PIDs and PID collisions during testing by restoring the same process again and again does not happen any more.

Restore processes using clone3() with set_tid

---

compel/arch/s390/src/lib/include/uapi/asm/sigframe.h
criu/arch/s390/include/asm/restore.h

Just like on all other supported architectures gcc complains about the stack pointer register being part of the clobber list: `error: listing the stack pointer register ‘15’ in a clobber list is deprecated [-Werror=deprecated]`
This removes the stack pointer from the clobber list.
`zdtm.py run -a` still runs without any errors after this change.

s390x: remove stack pointer from clobber list

---

criu/arch/s390/include/asm/restorer.h
criu/kerndat.c

This adds the parasite clone3() with set_tid wrapper for s390x.
In contrast to the x86_64 implementation the thread start address and arguments are not put on the thread stack but passed via r4 and r5. As those registers are caller-saved they still contain the correct value (thread start address and arguments) after returning from the syscall.
Tested on 5.5.0-rc6.
Thanks to @fweimer and @huth for your help in understanding this.
CC: @alicefr 
Also see #882 and #890

s390x: use clone3() if possible

---

criu/arch/arm/include/asm/restore.h

Just like on all other supported architectures gcc complains about the stack pointer register being part of the clobber list. This removes the stack pointer from the clobber list.
Fixes: #913 
Only compile tested so far.

arm: remove stack pointer from clobber list

---

criu/arch/ppc64/include/asm/restorer.h
criu/kerndat.c

This adds the parasite clone3() with set_tid wrapper for ppc64le.
Almost the same as #911 and depends on #911
Also see #882 and #890

ppc64le: use clone3() if possible

---

criu/arch/aarch64/include/asm/restorer.h
criu/arch/arm/include/asm/restorer.h
criu/kerndat.c

This is the last architecture specific change to make CRIU use clone3() with set_tid if available. Just as on all other architectures this adds a clone3() based assembler wrapper to be used in the restorer code.
Tested on Fedora 31 with the same 5.5.0-rc6 kernel as on the other architectures.
Depends on the other architecture specific assembler wrapper pull request.

arm/aarch64: use clone3() if possible

---

.travis.yml

This fixes the validation errors from Travis:
Build config validation
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing os, using the default linux
root: key matrix is an alias for jobs, using jobs

travis: fix warning and errors from validation

---

criu/config.c
criu/include/cr_options.h
criu/include/pstree.h
criu/include/tun.h

On gcc-10 (and gcc-9 -fno-common) build fails as:
```
ld: criu/arch/x86/crtools.o:criu/include/cr_options.h:159:
multiple definition of `rpc_cfg_file'; criu/arch/x86/cpu.o:criu/include/cr_options.h:159: first defined here
make[2]: *** [scripts/nmk/scripts/build.mk:164: criu/arch/x86/crtools.built-in.o] Error 1
```
gcc-10 will change the default from -fcommon to fno-common:
https://gcc.gnu.org/PR85678.
The error also happens if CFLAGS=-fno-common passed explicitly.
Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/707942

criu: fix build failure against gcc-10

---

criu/cr-restore.c
criu/include/util-vdso.h
criu/pie/parasite-vdso.c
criu/pie/restorer.c
criu/vdso.c

Apparently, after removing `CONFIG_VDSO` ifdefs from CRIU, C/R was broken on !CONFIG_VDSO duts.
Much help provided by @adrianreber to test this.
Unfortunately, there doesn't seem to be a way to disable vdso in kernel, except `vdso=` boot cmdline or .config option. So, in the result zdtm is not covering this platform-related code.

vdso: repair C/R on nodes with CONFIG_VDSO unset

---

scripts/travis/podman-test.sh

Podman changed the output of 'podman ps'. For the test only running containers are interesting. Adding the filter '-f status=running' only returns running containers as previously.

Travis: fix podman test case

---

MAINTAINERS
MAINTAINERS_GUIDE.md

@avagin , @adrianreber , @rst0git , @cyrillos , @rppt, @0x7f454c46 
Gentlemen,
Some time ago Andrey suggested to change the maintainership of the project. He suggested to take the runc's maintainer's guide and adopt it for us. Let's discuss this version of it.
The current list of maintainers reflects the current project state, but I encourage you (if the guide gets accepted) to extend this list :)

Maintainers: Suggest the maintainers codex

---

Documentation/criu.txt

This option was introduced with commit https://github.com/checkpoint-restore/criu/commit/e2c38245c613df5e36dcf0253c7652f928e46abf.

 criu(8): Add documentation for --enable-fs 

---

criu/filesystems.c
criu/seize.c
images/mnt.proto

With these changes I am able to use runc again on a cgroup v2 system. I am also preparing a small runc patch to fall back to non-freezer based checkpointing if necessary.

Use cgroup v2 freezer if detected

---

MAINTAINERS

The following changes since commit 872b795a5678d82a415419e139d680cbf81391ff:
Maintainers: Suggest the maintainers codex (#932) (2020-02-21 18:48:41 +0300)
are available in the Git repository at:
https://github.com/rppt/criu maint
for you to fetch changes up to a7903240259af2e66ab8896cd39bf4e0f912b63a:
MAINTAINERS: add Mike (2020-02-26 20:35:12 +0200)
----------------------------------------------------------------
Mike Rapoport (1):
MAINTAINERS: add Mike
MAINTAINERS | 1 +
1 file changed, 1 insertion(+)

MAINTAINERS: add Mike

---

MAINTAINERS

They have done a lot of contributions to the project and always help with reviewing new changes.

MAINTAINERS: Add Dima and Adrian to maintainers

---

criu/files-reg.c
criu/memfd.c

Processes can run in a mount namespace without /proc.
Fixes #970 
```
$ python test/zdtm.py run --iter 2  -t zdtm/static/clean_mntns 
=== Run 1/1 ================ zdtm/static/clean_mntns
====================== Run zdtm/static/clean_mntns in ns =======================
Start test
Test is SUID
./clean_mntns --pidfile=clean_mntns.pid --outfile=clean_mntns.out
Run criu dump
Run criu restore
Run criu dump
Run criu restore
=[log]=> dump/zdtm/static/clean_mntns/51/2/restore.log
------------------------ grep Error ------------------------
b'(00.100914)      4: pr167872-3 Read 0 1 pages'
b'(00.100915)      1: `- render 1 iovs (0x7f60da7c0000:4096...)'
b'(00.100927)      4: \tpr167872-3 Read page from self 0/0'
b'(00.100961)      1: Restore via sigreturn'
b"(00.101052)      4: Error …
```

memfd: use __open_proc instead of open("/proc/...", ... )

---

test/zdtm.py

python 2.7 doesn't call the read system call if it's read file to the
end once. The next seek allows to workaround this problem.
inhfd/memfd.py hangs due to this issue.

zdtm/inhfd: force python to read new data from a file

---

criu/files-reg.c
criu/files.c
criu/pie/parasite.c
images/ghost-file.proto
test/zdtm/static/Makefile
test/zdtm/static/opath_file.c
test/zdtm/static/symlink.c
test/zdtm/static/symlink01.c

This patchset adds support c/r of opened O_PATH fds and symlinks (ghost symlinks also)
Extract from commit messages:
1. fown: Don't fail on dumping files opened wit O_PATH
O_PATH opened files are special: they have empty
file operations in kernel space, so there not that
much we can do with them, even setting position is
not allowed. Same applies to a signal number for
owner settings.
2. files: allow dumping opened symlinks
To really open symlink file and not the regular file below it, one needs
to do open with O_PATH|O_NOFOLLOW flags. Looks like systemd started to
open /etc/localtime symlink this way sometimes, and before that nobody
actually used this and thus we never supported this in CRIU.
3. zdtm: add a test on open symlink migration

Add support of symlinks

---

test/crit-recode.py

fix tests https://ci.openvz.org/job/CRIU/job/CRIU-crit/job/criu-dev/6027/consoleText

crit-recode: skip (not try to parse) nftables raw image

---

.travis.yml
scripts/build/Dockerfile.ppc64-cross
scripts/build/Makefile

Now when @0x7f454c46 did the heavy lifting of resolving compel headers mess, it's easy to add another cross-build target :)

travis: add ppc64-cross test

---

scripts/nmk/scripts/utils.mk

The config.h detection scripts should use the provided CFLAGS/LDFLAGS
as it tries to link libnl, libnet, and others.

make: use cflags/ldflags for config.h detection mechanism

---

criu/files.c
criu/include/memfd.h
criu/memfd.c
criu/proc_parse.c
test/zdtm/static/Makefile
test/zdtm/static/shmemfd-priv.c
test/zdtm/static/shmemfd-priv.desc
test/zdtm/static/shmemfd.c
test/zdtm/static/shmemfd.desc

Any shared memory mapping can be opened via /proc/self/maps_files/.
Such file descriptors look like memfd file descriptors, so they can be dumped by the same way.
Cc: @nviennot

mem: dump shared memory file descriptors

---

test/zdtm/lib/Makefile
test/zdtm/lib/fs.c
test/zdtm/lib/fs.h
test/zdtm/lib/unix.c
test/zdtm/lib/zdtmtst.h
test/zdtm/static/del_standalone_un.c
test/zdtm/static/deleted_unix_sock.c
test/zdtm/static/sk-unix01.c

Any filesystem syscall, that needs to navigate to inode by it's
absolute path performs successive lookup operations for each part of the
path. Lookup operation includes access rights check.
Usually but not always zdtm tests processes fall under 'other' access
category. Also, usually directories don't have 'x' bit set for other.
In case when bit 'x' is not set and user-ID and group-ID of a process
relate it to 'other', test's will not succeed in performing these
syscalls which are most of filesystem api, that has const char *path
as part of it arguments (open, openat, mkdir, bind, etc).
The observable behavior of that is that zdtm tests fail at file
creation ops on one system and pass on the other. The above is not
immediately clear to the developer by just looking at failed test's logs. …

In tests check current working directory permissions in filesystem operations with absolute paths.

---

criu/pipes.c
test/zdtm/static/pipe03.c
test/zdtm/transition/fifo_loop.c

Without this patch, pipe size is restored only if a pipe has queued data.
Fixes #995

pipe: restore pipe size even if a pipe is empty

---

scripts/feature-tests.mak

Fixes: 9433b7b9db3e ("make: use cflags/ldflags for config.h detection mechanism")

config/nftables: include string.h for strlen

---

criu/namespaces.c

Fix n_xid_map leaks on error path and remove useless exit_code.
Fixes: 6e1726f8 ("userns: set uid and gid before entering into userns")

namespaces: fix error handling in dump_user_ns

---

.gitignore

After running make install, build directory is generated but not ignored
in gitignore. So this commit add build directory to gitignore.
Signed-off-by: Byeonggon Lee <gonny952@gmail.com>

Add build directory to gitignore

---

criu/cr-restore.c
criu/util.c

See my review comments to https://github.com/checkpoint-restore/criu/pull/1003, these headers seem excess, so I remove them.

Remove header include statements duplicates v3.14 part2

---

criu/pagemap.c

Before, reaching EOF too soon would trigger an infinite loop.

img-read: reaching EOF unexpectedly in read_page_img_cache() should fail

---

criu/config.c
test/others/ext-tty/run.py

Oddly, one of the test had a typo which should be fatal.

style: fix typos

---

criu/protobuf.c

When an image is opened but errored with a ENOENT error, the image is still valid. Later on, do_pb_read_one() can fail and will invoke image_name(). The image fd is EMPTY_IMG_FD (-404). read_fd_link fails.

img: fix image_name() when image is empty

---

criu/mem.c
criu/pie/restorer.c

This commit introduces an optimization when rsti(t)->vma_io is empty. This optimization provides support for streaming a non-seekable image as CR_FD_PAGES is not re-oepened.

mem: avoid re-opening CR_FD_PAGES when not needed

---

compel/arch/ppc64/src/lib/infect.c
compel/src/main.c
criu/arch/ppc64/crtools.c
criu/cr-dump.c
criu/pagemap.c
test/zdtm/static/fifo_wronly.c
test/zdtm/static/inotify_system.c
test/zdtm/static/ptrace_sig.c
test/zdtm/static/vsx.c
test/zdtm/transition/epoll.c

We should follow Linux Kernel Codding Style:
... the closing brace is empty on a line of its own, except in the cases
where it is followed by a continuation of the same statement, ie ... an
else in an if-statement ...
https://www.kernel.org/doc/html/v4.10/process/coding-style.html#placing-braces-and-spaces
Automaticly fixing with:
```
:!git grep --files-with-matches "^\s*else[^{]*{" | xargs
:argadd <files>
:argdo :%s/}\s*\n\s*\(else[^{]*{\)/} \1/g | update
```

criu: put statement continuation on the same line as the closing bracket

---

criu/kerndat.c

kerndat_socket_netns() is called twice. We keep the latter to avoid
changing the behavior.
Signed-off-by: Nicolas Viennot <Nicolas.Viennot@twosigma.com>

kerndat: remove duplicate call to kerndat_socket_netns()

---

criu/pie/parasite.c

Changed all the %u into %d.
Ideally, we should implement the %u format for parasite code.
---
If we use %u, we get: https://github.com/checkpoint-restore/criu/blob/criu-dev/compel/plugins/std/log.c#L333
Maybe we should change compel's printf() implementation with something like [musl's printf() implementation](https://github.com/bminor/musl/blob/master/src/stdio/vfprintf.c) which is licensed under the MIT license.

parasite-msg: %u is not implemented for parasite code

---

criu/kerndat.c

Func kerndat_nsid() is called twice.

kerndat remove duplicate call to kerndat_nsid()

---

criu/proc_parse.c
criu/timens.c

Clock IDs in this file has been replaced by clock symbolic names.
Now it looks like this:
$ cat /proc/774/timens_offsets
monotonic      864000         0
boottime      1728000         0

proc: parse clock symbolic names in /proc/pid/timens_offsets

---

test/jenkins/criu-btrfs.sh
test/jenkins/criu-by-id.sh
test/jenkins/criu-dedup.sh
test/jenkins/criu-dump.sh
test/jenkins/criu-fault.sh
test/jenkins/criu-fcg.sh
test/jenkins/criu-groups.sh
test/jenkins/criu-inhfd.sh
test/jenkins/criu-iter.sh
test/jenkins/criu-join-ns.sh
test/jenkins/criu-lazy-common.sh
test/jenkins/criu-lazy-migration.sh
test/jenkins/criu-lazy-pages.sh
test/jenkins/criu-other.sh
test/jenkins/criu-overlay.sh
test/jenkins/criu-pre-dump.sh
test/jenkins/criu-remote-lazy-pages.sh
test/jenkins/criu-sibling.sh
test/jenkins/criu-snap.sh
test/jenkins/criu-stop.sh
test/jenkins/criu-user.sh
test/jenkins/criu.sh

We permanently have issues like this:
./test/jenkins/criu-iter.sh: 3: source: not found
It looks like a good idea to use one shell to run our jenkins scripts.

test/jenkins: use bash to run jenkins scripts

---

criu/mount.c

The error here is not fatal since it is handled in ns_open_mountpoint(),
(at least since #520 is fixed), so demote this error to a warning
to avoid confusing a user.

get_clean_mount: demote an error to a warning

---

criu/crtools.c

A similar one is already printed in check_options().
Before this patch:
> $ ./criu/criu -vvvvvv --deprecated --log-file=/dev/stdout xxx
> (00.000000) Turn deprecated stuff ON
> ...
> (00.029680) DEPRECATED ON
> (00.029687) Error (criu/crtools.c:284): unknown command: xxx
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

Remove dupe of "deprecated stuff on" msg

---

.travis.yml

A few tests were still running on xenial because at some point they were hanging. This switches now all tests to bionic except one docker test which still uses xenial to test with overlayfs.

travis: use bionic almost everywhere

---

.github/workflows/cross-compile.yml
.travis.yml

This moves the cross compilation tests to github actions, to slightly reduce the number of Travis tests and run them in parallel on github actions.

tests: move cross compilation to github actions

---

criu/config.c
criu/cr-service.c

A couple of nits for messages printed by cr-service.
The message "Overwriting RPC settings with values from <filename>" is
misleading, giving the impression that file is being read and consumed.
It really puzzled me, since <filename> didn't exist.
What it needs to say is "Would overwrite", i.e. if a file with such name
is present, it would be used.
Also, add actual "Parsing file ..." so it will be clear which files are
being used.
While working on runc checkpointing, I incorrectly closed status_fd
prematurely, and received an error from CRIU, but it was
non-descriptive.
Do print the error from open().

cr-service: message fixes

---

criu/action-scripts.c
criu/cr-service.c
criu/include/action-scripts.h
criu/include/util.h
criu/uffd.c
criu/util.c

When we use swrk, we have a mechanism to send notifications over RPC.
It is cleaner and more straightforward than sending `\0` to status fd.
For now, both mechanisms are supported, although status fd request
option is now deprecated, so a warning is logged in case it's used.
Guess we can remove it in a few years.
The corresponding runc PR is here: https://github.com/opencontainers/runc/pull/2414

[RFC] swrk: send notification instead of using status fd

---

criu/files.c
criu/include/sockets.h
criu/sk-unix.c

Optimize find_unix_sk_by_ino().
Replaced the linear search with a hashtable lookup.
Fixes #339

Optimize find_unix_sk_by_ino()

---

lib/c/criu.c
lib/c/criu.h
test/others/libcriu/lib.c
test/others/libcriu/lib.h
test/others/libcriu/test_self.c

Although the CRIU version is exported in macros in version.h it only contains the CRIU version of libcriu during build time.
As it is possible that CRIU is upgraded since the last time somethingwas built against libcriu, this adds functions to query the actual CRIU binary about its version.

lib/c: add criu_get_version()

---

criu/clone-noasan.c
criu/cr-restore.c

Without clone3() CRIU was able to detect a process with a wrong PID only in the already created child process. With clone3() this error can happen before the process is created.
The clone3() function will now return -errno if something does not work correctly and in the case of EEXIST this error will also be correctly forwarded to an RPC client.
This was detected by running test/others/libcriu on a clone3() system.

Also report clone3() errors correctly

---

.travis.yml
scripts/travis/Makefile
scripts/travis/vagrant.sh

This adds the minimal configuration to run Fedora 31 based VMs on Travis.
This can be used to test cgroupv2 based tests, tests with vdso=off and probably much more which requires booting a newer kernel.
The current minimal test case is not really useful as it does not use any features of the kernel in the vagrant VM, but it can be used as a starting point.

Travis: use Vagrant to run VMs

---

criu/crtools.c

TL;DR: this makes possible to use `-v` with `criu swrk`, and removes showing
default usage which is useless in swrk mode.
1. Since criu swrk command is not described in usage, there is no sense
in showing it. Instead, show a one-line hint about how to use it.
2. In case some global options (like `-v`) are used, `argv[1]` might not
point to "swrk". Use `optind` to point to a correct non-option
argument. Same for `fd` argument.
3. While at it, also error out in case we have extra arguments.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

criu swrk: fix usage, allow common options

---

scripts/build/Dockerfile.alpine
test/zdtm.py

With the latest version of the alpine container image it seems that alpine changed a few package names. This adapts the alpine container to solve the travis failures.
This also includes a small change to zdtm.py because the latest run of flake8 complains about having variables named 'l'.

travis: fix alpine builds

---

CONTRIBUTING.md

Following the discussions at #1096 and #1100, start updating the contributor's guide.
* Fix spelling and formatting
* Add sections about describing and splitting patches
* Add section about pull request creation

CONTRIBUTING.md: fixups and additions

---

criu/uffd.c

When uffd_open is called from kerndat_uffd, userfaultfd failure is not
considered an error, so the goal is to suppress the error message --
instead, we print this message as info.
If the function fails, it is the responsibility of the caller
to print the error message.

uffd: uffd_open prints info, caller prints error

---

criu/cgroup.c
criu/mount.c
test/zdtm/static/Makefile
test/zdtm/static/zombie_leader.c
test/zdtm/static/zombie_leader.desc

Zombies have zero cg_set and ids on pstree they are just not dumped for them. Zombies can have children (Yes Run, Run, Run...! and see prepare_pstree_ids). So we can get segfault on ids and fail cgroup restore on zero parent cg_set, fix it.
Fixes: #1066

Fix segfault restoring tasks mntns

---

criu/config.c
criu/crtools.c
criu/fault-injection.c
criu/image.c
criu/include/criu-log.h

CRIU sometimes returns 1 from main() with no explanation. Even
increasing the log level is insufficient because that was not set until
after some initialization. Changes made add more logging in the case of
initialization errors in config and crtools.
Signed-off-by: Angie Ni <avtni@google.com>

Add error logging to config + crtools init

---

criu/kerndat.c
criu/net.c

CRIU sometimes returns 1 from main() with no explanation.
These changes add additional logging for initialization errors in kerndat.
There may be discourse surrounding the messages themselves -- specific alternatives are written and recorded elsewhere for each "foo failed" message. Given the large number of functions I've written error messages for in this commit, it may be safer to start with generic "foo failed" messages. These can be replaced depending on the preference of the CRIU maintainers. 
Signed-off-by: Angie Ni <avtni@google.com>

Add error logging to kerndat init

---

scripts/install-criu-image-streamer.sh

Now that the new protocol is in, we can move to the master branch on criu-image-streamer

tests: criu-image-streamer change dev branch to master branch

---

criu/cr-restore.c
criu/include/magic.h
test/others/ns_ext/run.sh

I pushed the wrong branch to the pidns PR
https://github.com/checkpoint-restore/criu/pull/1056
which resulted in the wrong patches getting merged.
This is the actual result from the review.
The code in `criu-dev` already works. When using `criu-dev` to checkpoint a container out of pod in cri-o I saw that the wrong magic number was in the pidns image file.
Sorry for the mixup of the branches, but this should be now the result from the review in the original PR. Mainly using a correct magic number and using `call_in_child_process()` instead of `fork()`.

pidns: fixup

---

criu/cr-check.c
criu/cr-restore.c
criu/include/log.h
criu/include/proc_parse.h
criu/include/util.h
criu/ipc_ns.c
criu/kerndat.c
criu/log.c
criu/proc_parse.c
criu/util.c

I've found that the print_on_level helper is used in several places of code. This is not correct, the decision if the message is info/warning/error/whatever should be taken based on the place in the code where it happens, not by some C-expression. With this, the set of pr_foo()-s should be enough to use log.h

Fix usage of logging functionality

---

lib/c/criu.c
lib/c/criu.h

When using libcriu with the notify callback functionality CRIU transmits an FD during 'orphan-pts-master' back to libcriu user. This is message is sent via sendmsg() to transmit the FD and not via write() as all other protobuf messages.
libcriu was using recv() and to be able to receive the FD this needs to be changed to recvmsg() and if an FD is attached to it (currently only for 'orphan-pts-master' this FD is stored in a variable which can be retrieved with the function criu_get_orphan_pts_master_fd().
This (and #959) are the last changes to make it possible to use crun instead of runc to checkpoint and restore a container with Podman.

lib/c: extend receive to handle incoming FDs

---

CONTRIBUTING.md

The description of the Fixes: tags could be misleading and may be
understood as if "Fixes: " should be the commit summary.
Add a sentence with explicit description of Fixme: tags placement.
Reported-by: Otto Bittner <otto-bittner@gmx.de>

CONTRIBUTING.md: clarify placement of Fixes: tags

---

lib/py/images/pb2dict.py

This PR fixes #1165. 
We were experiencing cases where parsed snapshot images included byte string in the resulting dictionaries. These byte strings where not handled correctly and are properly decoded with this change.
Reported by: liikt

Fixes #1165

---

scripts/travis/travis-tests

One of the most common CI errors we see is that package install fails due to some hashsum mismatch or some DNS errors.
This adds a loop around each apt-get install call to do a clean, update and install and if one of the steps fails it repeats it up to 10 times.

travis: loop over apt-get to recover from errors

---

.github/workflows/cross-compile-daily.yml

This adds a definition to do a daily rebuild of all cross-compile tests on the master and criu-dev branch.
Follow up on #1067 to also have daily cron-like builds like defined in Travis for the builds moved to github actions.

actions: create file for daily rebuild

---

criu/sk-inet.c
criu/sk-unix.c

```
(00.015271) unix: 	Add a peer: ino 2203289876 peer_ino 2203289875 family    1 type    1 state  1 name /mnt/test/zdtm/static/sockets03.test
(00.015277) Warn  (criu/sk-unix.c:475): unix: Shutdown mismatch -2091677421:1 -> -2091677420:0
```

criu: the type of a socket inode has to be "unsigned int"

---

.github/workflows/cross-compile-daily-mips.yml
.github/workflows/cross-compile-mips.yml
.github/workflows/cross-compile.yml

Master branch does not have mips support yet, so automated builds for
mips on the master branch fail.
Temporarily split mips cross-build into a separate files until mips
support will be mergded into the master branch.
Suggested-by: Adrian Reber <areber@redhat.com>

github: disable cross-compule for mips on master branch

---

contrib/debian/dev-packages.lst

This one contains builtins module from which zdtm.py imports.
Signed-off-by: Pavel Emelyanov <xemul@openvz.org>

contrib: Add python-future to Debian packages

---

scripts/travis/travis-tests

Python2 has reached its EOL. Let's switch to Python3 in our Travis runs.
We are still using Python 2 in the CentOS 7 test run.

travis: switch travis to Python 3

---

.travis.yml
scripts/travis/travis-tests

It seems travis supports now Ubuntu 20.04. Let's run at least one test also on 20.04 (focal).
This depends on #1074 because 20.04 seems to have limited Python 2 support. 
Tests will fail without #1074. Only opening as a draft until  #1074 is merged.

travis: add a focal based test run

---

scripts/travis/travis-tests

Since commit cdd08cdff ("uffd: use userns_call() to execute
ioctl(UFFDIO_API)") UFFD_API ioctl() is wrapped with userns_call() and this
allows runing lazy-pages tests on recent kernels in uns.
Restore testing of lazy-pages in uns in travis.

travis: restore lazy-pages tests for uns flavor

---

scripts/build/Dockerfile.fedora-rawhide.hdr

The docker hub container registry is not updated as fast as Fedora's registry at registry.fedoraproject.org. Fedora's registry gets a new image whenever there is a new version of rawhide, docker hub's rawhide image can take a couple of weeks because the process is not automated.
Especially when Fedora branches of a new release we see lot's of errors in CRIU's Fedora rawhide based Travis runs. Switch to Fedora's registry to always have the newest rawhide images for our tests.

travis: use Fedora rawhide images from Fedora

---

criu/eventpoll.c
test/zdtm/static/Makefile
test/zdtm/static/epoll01.c
test/zdtm/static/epoll01.desc

In dump_one_eventpoll we call find_tfd_bsearch with arguments
"e->tfd[i]->tfd, toff[i].off". By this we want to check if
"toff[i].off"-th inclusion of target "e->tfd[i]->tfd" in an eventpoll
coresponds to our fd "e->tfd[i]->tfd" in terms of kcmp.
But because of toff was sorted to calculate off, indexes in e->tfd and
toff does not address the same eventpoll target at this point.
Let's sort toff back to original state to make indexes consistent.

eventpoll: resort toff back by idx

---

images/sk-unix.proto

The id 18 in unix_sk_entry is already used in Virtuozzo criu for a long time so we can't easily change it to new ```vz_<field> 1000+<id>``` model so let's kindly ask not to use it.
Previous PR: https://github.com/checkpoint-restore/criu/pull/1152
v2: instead of reserving new fields in original image, lets reserve special vendor message field with id 1024, so that all extra fields are put in it
v3: We will use `vz_<field> 1000+<id>` semantics in Virtuozzo so that it would be easier to handle porting to mainstream and rebasing on mainstream with the ported id. Only thing which is left is id 18 in unix_sk_entry, for which we would kindly ask not to use it.

Images: kindly ask not to use fields with id 18 in unix_sk_entry 

---

criu/sk-netlink.c

This PR includes the commit from https://github.com/checkpoint-restore/criu/pull/878 rebased on the criu-dev branch.

sk-netlink: Handle case of in-use netlink peer ids

---

criu/sockets.c
images/sk-opts.proto
test/zdtm/static/Makefile
test/zdtm/static/sock_opts00.c
test/zdtm/static/socket-linger.c

This PR adds checkpoint/restore support for `SO_LINGER` and `SO_OOBINLINE` socket options.

socket: Add c/r support for SO_LINGER and SO_OOBINLINE

---

.github/workflows/lint.yml
Makefile
scripts/install-criu-image-streamer.sh
scripts/install-debian-pkgs.sh
scripts/protobuf-gen.sh
scripts/systemd-autofs-restart.sh
scripts/tmp-files.sh
scripts/travis/asan.sh
scripts/travis/docker-test.sh
scripts/travis/openj9-test.sh
scripts/travis/podman-test.sh
scripts/travis/travis-tests
scripts/travis/vagrant.sh

Seeing that the tool *shellcheck* exists and that other projects started to include it in their CI process (and our discussion about `clang-format`), I included `shellcheck` into our CI setup. The easy and simple change is to not run `make test` for every Travis target but to only run it once through github actions. This does not change CI runtime in any way, but I think it makes kind of sense to run `make lint` in just a single place.
I also included the tool `shellcheck` into the Makefile target `lint`. I only added all `*.sh` files in the `scripts/` folder for now as `shellcheck` wants changes to almost all our scripts.
I am not totally convinced that the changes to the shellscripts in this PR actually fix anything. Knowing the environment the scripts are running in and what they are …

Add shellcheck to lint target and run 'make lint' only once

---

scripts/build/Dockerfile.aarch64-cross
scripts/build/Dockerfile.armv7-cross
scripts/build/Dockerfile.linux32.tmpl
scripts/build/Dockerfile.mips64el-cross
scripts/build/Dockerfile.openj9-ubuntu
scripts/build/Dockerfile.ppc64-cross
scripts/build/Dockerfile.tmpl
scripts/build/Dockerfile.x86_64.hdr
scripts/travis/apt-install
scripts/travis/docker-test.sh
scripts/travis/podman-test.sh
scripts/travis/travis-tests
scripts/travis/vagrant.sh

The previously introduced apt_install loop function to make package install more robust against network errors is now moved to its own script used in multiple places.

CI: switch to loop based apt-get

---

Makefile
scripts/travis/apt-install
scripts/travis/travis-tests

Running 'make lint' will now also check our travis-tests script with shellcheck.

CI: add Travis test script to 'lint'

---

.github/workflows/cross-compile.yml

The github action based cross compile tests are only running when pushing to master or criu-dev. This changes this to have it run on all branches. Useful to have all CI tests running on personal CRIU checkouts on branches with other names.
If I prepare a branch to create a new pull request, the cross compile tests have not been running if my branch has another name than criu-dev or master. With this change these tests will run on all branches.

CI: run cross compile on all branches

---

criu/sk-inet.c
test/zdtm/lib/tcp.c
test/zdtm/lib/zdtmtst.h
test/zdtm/static/Makefile
test/zdtm/static/socket-tcp-listen.c

There is no direct way to get this state but we can get it indirectly from polling events for a socket.

tcp: dump shutdown state for unconnected sockets

---

criu/cr-restore.c
criu/image.c
criu/include/crtools.h
criu/pstree.c

If the tcp-close has been set for dump, it has to set for restore too.
But we don't need to require matching of tcp-close for criu lazy-pages.
Reported-by: Mr Travis

criu: check matching the tcp-close option on restore only

---

criu/servicefd.c

We can have tmp != sfd if fcntl(F_DUPFD) sees that sfd is already used,
but tmp is left open on this error path, lets close it.

servicefd: close temporary fd on error path

---

criu/bpfmap.c
images/bpfmap-file.proto
test/zdtm/lib/Makefile
test/zdtm/lib/bpfmap_zdtm.c
test/zdtm/lib/bpfmap_zdtm.h
test/zdtm/static/bpf_array.c
test/zdtm/static/bpf_array.desc
test/zdtm/static/bpf_hash.c
test/zdtm/static/bpf_hash.desc

This PR accomplishes the following:
a) Adds support for frozen BPF maps
b) Allows c/r of map names and ifindex
c) Creates a ZDTM library for BPF test helper functions
d) Refactors ZDTM tests to use the BPF test library functions
e) Updates tests to check for frozen maps
The commit messages provide detailed explanations for all code changes.
I look forward to hearing your kind feedback.
Thank you.

bpf: frozen maps, refactoring zdtm tests

---

criu/sockets.c
test/zdtm/static/Makefile
test/zdtm/static/sock_filter00.c
test/zdtm/static/sock_filter01.c

Fix malloc size: use size * filter_size instead of typo size * size.
In case when there are filter with 4 commands this would corrupt malloc chunk ([reproduce](https://src.openvz.org/users/andrey.zhadchenko/repos/criu/commits/1fc43fa1e5af4d8c2c4c74195c6422d22c807b1d))
```
(1732.81300 Error (criu/cr-restore.c:1968): 38 killed by signal 6: Aborted
(1732.81304 Error (criu/cr-restore.c:3022): Restoring FAILED. 
```
```
backtrace:
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f2eab371535 in __GI_abort () at abort.c:79
#2  0x00007f2eab3c8508 in __libc_message …
```

sockets: fix incorrect malloc size

---

scripts/build/Dockerfile.fedora.tmpl

travis fails on Rawhide because gzip is missing

travis: install gzip for Fedora Rawhide based tests

---

compel/arch/ppc64/scripts/compel-pack.lds.S
compel/arch/s390/scripts/compel-pack.lds.S
compel/arch/x86/scripts/compel-pack.lds.S
compel/include/uapi/infect.h
compel/src/lib/handle-elf.c
compel/src/lib/infect.c

Some kernels have W^X mitigation, which means they won't execute memory blocks if that memory block is also writable or ever was writable. This patch enables CRIU to run on such kernels.
1. Align .data section to a page.
2. mmap a memory block for parasite as RX.
3. mprotect everything after .text as RW.
I'm not sure if this is the best way to achieve this goal. If anyone has a better idea, feel free to share.
v2: add alignment for ppc64 and s390

compel: don't mmap parasite as RWX

---

scripts/ci/run-ci-tests.sh

Most (all?) lazy tests are not being executed if "$KERN_MAJ" -ge "4" and "$KERN_MIN" -ge "18". Currently most CI systems are running on something with 5.4.x which means $KERN_MAJ is greater than 4 but $KERN_MIN is less than 18 and so we are not running any lazy tests.
This commit removes the complete lazy test kernel version detection as kernels on the CI systems are new enough to always have all required features.

ci: 'fix' lazy tests

---

criu/uffd.c

This xfree() which was added during static code analysis fixes breaks one of the tests with a double free error message:
free(): double free detected in tcache 2

uffd: fix 'double free detected in tcache 2'

---

criu/uffd.c

In the case, that xrealloc() fails do not overwrite the original pointer to be able to free the original pointer on exit.

uffd: handle xrealloc() failure

---

compel/plugins/std/log.c
criu/pie/util-vdso.c

Three printing fixes:
- copy string with (len - 1) to leave '\0' at the end (the buffer is big enough for now, but it may change)
- try to avoid crashing PIE whenever unknown specifier is found on logging
- support %u specifier

vdso: Printing fixes

---

criu/tls.c

Log messages showing the send/recv errno value would help us to debug issues such as #1280.
```
Error (criu/tls.c:321): tls: Pull callback recv failed: Connection reset by peer
Error (criu/tls.c:147): tls: Failed receiving data: Error in the pull function.
Error (criu/page-xfer.c:1225): page-xfer: Can't read pagemap from socket: I/O error
```

tls: Add logging within send/recv callbacks

---

criu/uffd.c

Sometimes there are uffd messages in a queue of a dying task and by the
time these messages are processed in handle_request, the uffd is no
longer valid and reading from it causes errors.
Add processing of EBADF in handle_uffd_event() to gracefully handle such
situation.

uffd: check for exited task when reading uffd_msg

---

test/zdtm.py

zdtm: on fail with no error also print the tail of the log
We see strange cases there page-server or lazy-pages are exiting with
non-zero but print no errors, probably the tail of the log can help us
to understand what happened.
There are some other uses of grep_errors but let's only change cases
where we explicitly through an exeption on bad ret. For others I'm not
sure if we need extra output, e.g. for validly failing fault injections.
To debug #1280

Zdtm add more verbosity to fail with no error case

---

test/crit-recode.py
test/inhfd/tty.py
test/zdtm.py

Probably all vim users can setup their desired indent in their vimrc by
themselfs.

vim: remove wrong 8-space tabs indent from python files

---

test/zdtm/static/socket_aio.c
test/zdtm/static/socket_listen.c
test/zdtm/static/socket_udp-corked.c
test/zdtm/static/socket_udp.c
test/zdtm/static/socket_udplite.c

There is a small typo in test/zdtm/static/socket_aio.c, test/zdtm/static/socket_listen.c, test/zdtm/static/socket_listen4v6.c, test/zdtm/static/socket_listen6.c, test/zdtm/static/socket_udp-corked.c, test/zdtm/static/socket_udp.c, test/zdtm/static/socket_udplite.c.
Should read `client` rather than `clietn`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, clietn -> client

---

compel/src/lib/handle-elf.c

We've seen addresses in parasite.built-in.o precalculated by linker but
in some unexpected manner:
readelf -WS criu/pie/parasite.built-in.o
Section Headers:
[Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
[ 1] .text             PROGBITS        0000000000000000 000040 00400a 00  AX  0   0 16
[87] .data             PROGBITS        0000000000000000 005000 000068 00  WA  0   0 4096
[88] .rodata           PROGBITS        0000000000000080 005080 001016 00   A  0   0 32
(Notes: All other sections does not have SHF_ALLOC or are of size 0, so I
skip them. Need to add "-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1" to
CFLAGS to reproduce.)
Section 88 has address 0x80 in elf file but in our "consequent"
addresses precalculation algorithm it should be at 0x5080: …

compel/handle-elf: override unexpected precalculated addresses

---

include/common/arch/x86/asm/asm.h
include/common/arch/x86/asm/bitops.h

When I try to compile criu in ubuntu amd64 with command "make DEBUG=1", it produces following errors:
include/common/asm/bitops.h: Assembler messages:
include/common/asm/bitops.h:71: Error: incorrect register `%edx' used with `q' suffix
The problem is caused by following code:
`
static inline bool test_and_set_bit(int nr, volatile unsigned long *addr)
{
bool oldbit;
asm("btsq %2,%1"
CC_SET(c)
: CC_OUT(c) (oldbit)
: "m" (*(unsigned long *)addr), "Ir" (nr) : "memory");
return oldbit;
}
`
since nr is a int, it can not be used with 'q' suffix.

x86/asm: fix compile error in bitops.h

---

CONTRIBUTING.md

If one will do "git log --oneline", it is quite easy to see that we
don't begin subject lines with a capital letter. We start subjects with
component prefixes where components (mostly) are lowercase. So let's fix
it in contribution guide not to mislead newcomers.

CONTRIBUTING.md: add component prefix to the subject example

---

criu/namespaces.c

This is just a small cleanup, no behaviour change.

namespaces: don't set rst on error in switch_ns_by_fd

---

scripts/ci/run-ci-tests.sh

Quick fix for the broken Alpine based CI runs using 'free -h' which busybox does not understand.

ci: Alpine's busybox based free does not understand -h

---

test/zdtm/static/netns-nf.desc
test/zdtm/static/socket-tcp-closed-last-ack.desc
test/zdtm/static/socket-tcp-reseted.desc
test/zdtm/static/socket-tcp-syn-sent.desc

On Ubuntu 20.04, iptables is in /usr/sbin/.

zdtm: look up iptables in /sbin and /usr/sbin

---

.github/workflows/stale.yml

This is a copy of stale.yml from the Podman repository to automatically close tickets after 365 days. After 30 days tickets and issues are marked as stale and after 365 tickets and issues are finally closed.
We have lots of old open issues and pull requests in GitHub. I think auto-closing, as done in this PR, issues and pull requests after 365 days of inactivity would make sense. I do not think any of our old issues and pull requests will every get any attention.
There are currently over 300 open issues against CRIU and I think it is difficult to see which of those are still relevant. 365 days is a long enough period for someone interested in a issue or pull request to still work on it, but if after 365 days no one is doing anything on an issue or pull request it makes more sense to close …

github: auto-close stale issues and pull requests

---

compel/arch/arm/src/lib/infect.c
compel/arch/mips/src/lib/infect.c
compel/arch/ppc64/src/lib/infect.c

1. The -ERESTART_RESTARTBLOCK case in get_task_regs() depends on kernel
internals too much, and for no reason. We shouldn't rely on fact that
a) we are going to do sigreturn() and b) restore_sigcontext() always
sets restart_block->fn = do_no_restart_syscall which returns -EINTR.
Just change this code to enforce -EINTR after restore, this is what
we actually want until we teach criu to handle ERESTART_RESTARTBLOCK.
2. Add pr_warn() to make the potential bug-reports more understandable,
a sane application should handle -EINTR correctly but this is not
always the case.
Fixes: #1325

ppc64,arm,mips: sanitize the ERESTART_RESTARTBLOCK -> EINTR transition

---

criu/cr-restore.c
criu/files.c
criu/include/servicefd.h
criu/include/util.h
criu/memfd.c
criu/servicefd.c
criu/sk-unix.c
criu/util.c

This is an attempt to cleanup service fds and put "self" to service fds. Also now we can use it instead of getpid() variant in memfd_open, it is a more general way because in case we would support nested pid namespaces opening by getpid is not an option.

Make proc/self a service fd and use it for memfd

---

criu/fsnotify.c
criu/mount.c

Adjust some log levels:
1) get_clean_mnt() pr_perror  -> pr_warn since the caller may resolve this situation or print error in the worst case (similar to this [commit](https://github.com/checkpoint-restore/criu/commit/5c5e7695a51318b17e3d982df8231ac83971641c))
2) mnt_is_dir() pr_perror->pr_warn since it may fail several times before finding suitable mountpoint. Added error in lookup_mnt_sdev. Other callers of mnt_is_dir() have corresponding errors.
Remove redundant call to open_handle() in check_open_handle() since alloc_openable() do exactly the same work plus some code.

mount: adjust log & fsnotify: rework redundant code

---

.cirrus.yml
.travis.yml
scripts/ci/vagrant.sh

This includes the changes to run the Vagrant based CI run on Cirrus CI. Cirrus CI seems to be one of the few (only) services which enable nested virtualization besides Travis. With the upcoming shutdown of travis-ci.org (end of 2020) and the necessary move the travis-ci.com I am trying to move all long running jobs away from Travis. To activate the Cirrus CI based job the Cirrus CI integration into checkpoint-restore/criu is necessary. Let me know if I should do that. Once we know it works on Cirrus CI I would disable it on Travis.
This is also includes a commit to prepare our aarch64 based run to work on aws-graviton2 based system. That would be the first non x86_64 based Travis CI run doing actual tests instead of just building CRIU. This is only available on travis-ci.com. If we …

Move first job to Cirrus CI

---

.drone.yml
.travis.yml
scripts/ci/run-ci-tests.sh

Besides Travis CI Drone CI seems to be only service providing ARM based builds. This switches the aarch64 and arm32 builds to drone.io.
Because Drone CI is running in a Docker container we cannot use 'setarch linux32' as it requires the blocked syscall 'personality(2)'.
But Drone CI provides an 'arch: arm' which gives the same architecture as 'setarch linux32' on Travis aarch64: armv8l
The goal from all this CI changes it to be able to move as much away from Travis as possible. Except maybe ppc64le and s390x (and maybe bare metal graviton2 based aarch64).
Using so many different CI systems is on the one hand not the nicest solution, but if one of the free CI systems decides to go the same way as Travis does we already are comfortable with setting up runs on other CI systems.
If this get …

CI: run aarch64 compile tests on Drone

---

.github/workflows/stale.yml

The commas need to be inside of the quotes. Not on the outside.

ci: fix syntax error in stale.yml

---

scripts/ci/vagrant.sh

As requested by @rst0git I updated to Fedora 33 and I am using --no-tty instead of > /dev/null
@avagin This also updates the VM to the latest Fedora 33 kernel (5.10) which means that we will have a kernel with time namespace support. Just FYI.

ci: upgrade vagrant and Fedora version

---

scripts/ci/vagrant.sh

See: https://github.com/checkpoint-restore/criu/issues/1354
Until we have a fix I think it would be better to skip tests which are known to fail.

ci: skip bpf tests on vagrant

---

.drone.yml
.github/workflows/fedora-rawhide-test.yml
.travis.yml
scripts/build/Dockerfile.fedora.tmpl
scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/run-ci-tests.sh

This moves Fedora Rawhide aarch64 to Drone and Fedora Rawhide x86_64 to github actions.

Move the Fedora Rawhide tests away from Travis

---

scripts/ci/podman-test.sh

Just saw that the podman test is failing. This is still caused by the broken overlayfs in the Ubuntu kernel. Hopefully this will be fixed at some point in the future.
It seems each podman command now needs to be told to use the storage-driver vfs

Tell podman to use vfs as storage-driver

---

criu/arch/aarch64/include/asm/vdso.h
criu/arch/arm/include/asm/vdso.h
criu/arch/mips/include/asm/vdso.h
criu/arch/ppc64/include/asm/vdso.h
criu/arch/s390/include/asm/vdso.h
criu/arch/x86/include/asm/vdso.h
criu/pie/util-vdso.c

I compile criu with the command "make DEBUG=1", and I use it to check/restore my program, it produces a segmentation fault(check the log at the bottom)
My running environment:
> Fedora 33
> Linux localhost.localdomain 5.8.15-301.fc33.aarch64 #1 SMP Thu Oct 15 15:56:58 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
My test program:
`
#include <unistd.h>
int main()
{
while(1)
{
sleep(10);
}
return 0;
}
`
This problem is caused by code in ./criu/pie/util-vdso.c, to be specific，by following codes:
`
const char * symbol = vdso_symbols[i];
k = elf_hash((const unsigned char *)symbol);
`
I try the same program in x86, it does not have such a problem, so I guess it is related to how the compiler handles the memory layout of the program since the execution code for pie is copied from somewhere.
I find …

pie/vdso: fix Segmentation fault caused by char pointer array

---

.github/workflows/fedora-asan-test.yml
.github/workflows/stream-test.yml
.travis.yml
scripts/build/Dockerfile.fedora-asan.hdr
scripts/ci/Makefile

This moves two more tests from Travis to GitHub Actions.
At Travis we now only have the aarch64 Graviton2, ppc64le and s390x tests remaining. As far as I know there is no CI system supporting those. We could, if we have access to any of those architectures, try to work with self-hosted GitHub Actions runners.
There are also still the Docker based tests. My last information was that Docker was broken. Not sure. @rst0git do you know if Docker works again with checkpoint/restore? Can you look into moving those tests to GitHub Actions?

ci: move asan and image streamer test to github

---

README.md

This removes trailing whitespace and replaces all of the broken badges with some working badges.

Minimal README.md cleanups

---

criu/file-lock.c
test/zdtm/static/Makefile
test/zdtm/static/file_locks00_fail.c
test/zdtm/static/file_locks00_fail.desc

If criu finds a file lock and the --file-locks option isn't set, it
stops dumping processes, resumes them and exits with an error.
Cc: @dracoding

dump: dump has to fail if there is locks and --file-locks isn't set

---

.github/workflows/gcov-test.yml
.travis.yml
Makefile
scripts/ci/run-ci-tests.sh

While moving CI jobs away from Travis I saw that we still have some GCOV based builds mentioned in the Travis configuration file.
This re-enables it (it was not running in Travis) and pushes the results to codecov.io.
See for results against my branch: https://codecov.io/gh/adrianreber/criu/tree/438efd3aedef9b38c545aca3be6117d7efb6c9ab
This would require integration of codecov.io into checkpoint-restore/criu.
This includes the changes from #1358

Use codecov.io

---

criu/proc_parse.c

In parse_pid_status(), it is assumed that the seccomp field can be
missing from /proc/pid/status. When the field is missing, it is not
properly initialized, leading to bad behavior.
We initialize seccomp_mode to SECCOMP_MODE_DISABLED by default,
similarly to what is done in compel/src/lib/infect.c:parse_pid_status.
Signed-off-by: Nicolas Viennot <Nicolas.Viennot@twosigma.com>

seccomp: initialize seccomp_mode in all cases

---

scripts/ci/podman-test.sh

The latest podman pulls in crun instead of runc. Unfortunately crun is not built against libcriu and does not support checkpoint/restore. This switches the podman test back to runc.

ci: use runc instead of crun for podman tests

---

criu/file-lock.c
scripts/build/Dockerfile.openj9-alpine
scripts/build/Dockerfile.openj9-ubuntu
test/.gitignore
test/javaTests/src/org/criu/java/tests/CheckpointRestore.java

The java tests are using file locks which results in the following error after https://github.com/checkpoint-restore/criu/pull/1357
> Error (criu/file-lock.c:112): Some file locks are hold by dumping tasks!You can try --file-locks to dump them.
Resolves #1370

Fix java tests

---

test/zdtm/static/sigaltstack.c

The latest glibc has redefined SIGSTKSZ as 'sysconf (_SC_SIGSTKSZ)' and
this breaks a static char[] definition. According to the kernel
sources all for CRIU relevant architectures use 8192 except AARCH64.
Hardcode SIGSTKSZ in the test. This fixes:
```
sigaltstack.c:17:13: error: variably modified 'stack_thread' at file scope
17 | static char stack_thread[SIGSTKSZ + TEST_MSG_BUFFER_SIZE] __stack_aligned__;
|             ^~~~~~~~~~~~
sigaltstack.c:18:13: error: variably modified 'stack_main' at file scope
18 | static char stack_main[SIGSTKSZ + TEST_MSG_BUFFER_SIZE] __stack_aligned__;
|             ^~~~~~~~~~
```

test: fix test compilation on rawhide

---

criu/plugin.c

New compilators print warnings if snprintf return value is not checked
for truncation. Let's make them happy.
Fixes: #1372

plugin: check for plugin path truncation

---

scripts/ci/prepare-for-fedora-rawhide.sh

It seems the Fedora rawhide /tmp is no longer 1777 but 755.
Change it back to 1777 to make our CI runs successful again.

ci: fix Fedora rawhide CI failures

---

scripts/ci/run-ci-tests.sh

Just an additional check. I see that they are currently, but to be double sure that it starts to fail if they are 64-bit ELFs.

Ci/compat: check that test are 32bit ELFs

---

compel/Makefile
compel/arch/aarch64/src/lib/include/uapi/asm/infect-types.h
compel/arch/arm/src/lib/include/uapi/asm/infect-types.h
compel/arch/mips/src/lib/include/uapi/asm/infect-types.h
compel/arch/ppc64/src/lib/include/uapi/asm/infect-types.h
compel/arch/s390/src/lib/include/uapi/asm/infect-types.h
compel/arch/x86/src/lib/include/uapi/asm/infect-types.h
compel/arch/x86/src/lib/thread_area.c
compel/include/infect-priv.h
compel/src/lib/infect.c
criu/arch/arm/include/asm/parasite.h
criu/arch/x86/include/asm/parasite.h
criu/arch/x86/include/asm/restorer.h
criu/arch/x86/include/asm/types.h
criu/parasite-syscall.c

To minimize things done in parasite, `PTRACE_GET_THREAD_AREA` can be
used to get remote tls. That also removes an additional compat stack
(de)allocation in the parasite (also asm-coded syscall).
In order to use `PTRACE_GET_THREAD_AREA`, the dumpee should be stopped.
So, let's move this from criu to compel to non-seized state and put tls
into thread info on x86.
Fixes: #1253
Signed-off-by: Dmitry Safonov <dima@arista.com>

x86/criu/compel: Use PTRACE_GET_THREAD_AREA instead of sys_get_thread_area()

---

criu/namespaces.c

If snprintf was truncated we should probably know about it instead of
continuing to increase off, as snprintf returns number of characters
which would have been written and not the number which was actually
written.
Normally we check snprintf only for overflow not for error, some modern
compilers print warnings if truncation was not checked.
Probably it was the case why we implemented [1], the truncation happened
and on the next iteration of for loop we've hit negative size for
snprintf and got -1.
Fixes: 90f043dea ("namespaces: handle errors of snprintf") [1]

namespaces: properly handle errors of snprintf

---

criu/pstree.c

Without this check we can hit the BUG in lookup_create_item just a few
steps later (if one thread in images has same pid with new sid/gid). And
also this check saves us from different sorts of unexpected errors on
restore (if one non-thread task in images has same pid/sid/gid already).
Fixes: #1332

pstree: check for pid collision before switching to new sid/gid

---

lib/py/cli.py

python3 fails to encode image with the following:
> [dima@Mindolluin criu]$ ./crit/crit encode -i tmp -o tmp.1
> Traceback (most recent call last):
>   File "/home/dima/src/criu/./crit/crit", line 6, in <module>
>     cli.main()
>   File "/home/dima/src/criu/crit/pycriu/cli.py", line 410, in main
>     opts["func"](opts)
>   File "/home/dima/src/criu/crit/pycriu/cli.py", line 50, in encode
>     pycriu.images.dump(img, outf(opts))
>   File "/home/dima/src/criu/crit/pycriu/images/images.py", line 617, in dump
>     f.write(struct.pack('i', magic.by_name['IMG_COMMON']))
> TypeError: write() argument must be str, not bytes
Opening the output file as binary seems to help.
Signed-off-by: Dmitry Safonov <dima@arista.com>

lib/cli.py: Open out file as a binary

---

scripts/ci/run-ci-tests.sh

This removes extending LDFLAGS with '-Wl,-z,now'. This was added as workaround but never really worked. It is correctly fixed with pull request #1379

ci: remove '-Wl,-z,now' workaround

---

lib/py/images/images.py
lib/py/images/pb2dict.py
scripts/ci/run-ci-tests.sh

Although we are running crit-recode.py also in all CI runs we never seen
following error except in Jenkins:
```
Traceback (most recent call last):
File "/usr/lib/python3.8/base64.py", line 510, in _input_type_check
m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "./test/crit-recode.py", line 25, in recode_and_check
r_img = pycriu.images.dumps(pb)
File "/var/lib/jenkins/workspace/Q/test/pycriu/images/images.py", line 635, in dumps
dump(img, f)
File "/var/lib/jenkins/workspace/Q/test/pycriu/images/images.py", line 626, in dump
handler.dump(img['entries'], f)
File "/var/lib/jenkins/workspace/Q/test/pycriu/images/images.py", line 289, in dump …
```

ci: fix recode errors seen in Jenkins

---

.travis.yml
scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.centos7
scripts/build/Dockerfile.centos8
scripts/build/Dockerfile.fedora.tmpl
scripts/build/Dockerfile.linux32.tmpl
scripts/build/Dockerfile.openj9-alpine
scripts/build/Dockerfile.tmpl
scripts/build/Makefile
scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/run-ci-tests.sh

ccache was set up in Travis to speed up compilation by re-using the .ccache directory from previous CI runs. As we are no longer using Travis we can remove all CI related ccache setup.

ci: remove ccache setup

---

scripts/ci/run-ci-tests.sh

This test should be run with at least 1 pre-dump to trigger the problem as mentioned in commit 4d9bf608b59b6e323f346b0beb956b02ecbef294.

Run zdtm/transition/pid_reuse with pre-dumps in ci tests

---

scripts/criu-ns

The `criu-ns` script creates a new PID namespace where CRIU runs as the "init" process.
When using the `--restore-detached` option with `criu-ns`, users expect `criu-ns` to exit without killing the restored process tree. Thus, `criu-ns` should exit instead of waiting for CRIU's status and it should not pass the `--restore-detached` to CRIU to prevent terminating the init process.
Resolves #1278
Resolves #807

criu-ns: Fix --restore-detached option

---

.cirrus.yml
scripts/ci/vagrant.sh

It allows to remove the workarounds and performance is much better (13 mins build vs 20 mins).

Use a real VM instead of a privileged container

---

.cirrus.yml
.github/workflows/centos-test.yml
lib/py/images/images.py
lib/py/images/pb2dict.py
scripts/ci/run-ci-tests.sh

The kernel on GitHub Actions has a bug
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1919472
which breaks our CI. It works on Cirrus. Let's move it there.
Maybe this is a better solution than #1401. Just run the CentOS 8 tests on a CentOS 8 kernel instead in a container on Ubuntu.

ci: move CentOS 8 based test to Cirrus

---

criu/cr-service.c

Closes: #1408
CRIU_REQ_TYPE__FEATURE_CHECK was failing, this was caused by two things in ```handle_feature_check()```:
1. ```setup_opts_from_req()``` was used and it could be NULL (```kerndat_init()``` is enough for feature checking)
2. ```resp.success``` was always set to false

fix CRIU_REQ_TYPE__FEATURE_CHECK RPC request

---

criu/image.c
criu/include/image.h
criu/irmap.c
criu/page-xfer.c
criu/pagemap.c

In image dump directory, there are 2 parent symlink error cases:
- Parent symlink does not exist
- Parent symlink exists but points to invalid target
At the moment, 2 cases are handled exactly the same (do full dump). However, while
the first case happen when parent path is not provided, the second one is likely
user's mistake when provides invalid parent path.
So we throw an error in the latter case instead of performing the full dump.
Fixes: #1387.

criu: Throw error when parent path is provided but invalid

---

criu/image.c

Currently, alpine musl libc library returns Invalid argument error (EINVAL)
when calling faccessat with AT_SYMLINK_NOFOLLOW flag.
Fix this by using fstatat instead.
Fixes: #1426.

criu: Replace faccessat with fstatat when using AT_SYMLINK_NOFOLLOW flag

---

scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.centos7
scripts/build/Dockerfile.centos8
scripts/build/Dockerfile.fedora.tmpl
scripts/build/Dockerfile.linux32.tmpl
scripts/build/Dockerfile.tmpl

The ENV1 variable was first introduced with commit 7290de5 and it not used anymore.

scripts/build: drop obsolete ENV1 variable

---

criu/crtools.c
criu/net.c

This introduces a new option
--external netdev[IFNAME]:ORIGNAME
which informs CRIU that this is pre-created network device that it is
supposed to move into a target network namespace. The "netdev" name was
chosen to make it flexible enough to e.g. also cover physical devices if
that is desirable at some point. For example:
--external netdev[eth0]:vethA23adf3
would instruct CRIU to move the network device with the name
"vethA23adf3" into a target network namespace renaming it to "eth0"
while doing so.
In order to restore ip addresses and additional data correctly CRIU
needs to move the network device into the target netns with the recorded
ifindex. This requires a kernel patch as discussed in [1]. The patch has
been merged into net-next and is expected to show up in the v5.13
release (cf. …

net: allow restoring of precreated veth devices

---

criu/filesystems.c
criu/util.c

return value of is_empty_dir:
* -1 : open directory stream failed
*  0 : directory is not empty
*  1 : directory is empty

tiny fix on dump_empty_fs

---

Makefile
scripts/build/Dockerfile.tmpl

The `make docker-test` command was originally used with the shell-script version of zdtm, which was removed in commit https://github.com/checkpoint-restore/criu/commit/2cb4532e266d0c9f8e87839d5b5eb728a3e4d10d.
This pull request includes a number of updates to allow the container image build with `make docker-build` to run zdtm tests.

Makefile: fix docker-test

---

scripts/ci/run-ci-tests.sh

Temporarily disable the lazy-thp test for remote lazy pages with enabled tls until #1380 is resolved.

ci: Skip lazy-thp for remote pages over tls

---

criu/pie/restorer.c

`last_pid_buf` is not where the last_pid string is, but it is in `s`.

restore: fix error message when fork fails

---

criu/net.c

Debian 9 doesn't have IFLA_NEW_IFINDEX defined

net: add a #define for increased compatiblity with old distributions

---

criu/util.c

When invoking an action-script, all file descriptors >= 3 are closed.
If execvp() fails, we can only log the error on stderr. pr_msg() outputs
on stderr, so we use this as opposed to pr_perror().

logging: pr_perror() -> pr_msg() when execvp fails in action scripts and others

---

criu/proc_parse.c

Currently, it cannot be check-pointed, because that type of file is on UNSUPP list.
Signed-off-by: zl-wang <zlwang@ca.ibm.com>

Allow systemcfg proc file to be dumped

---

criu/lsm.c

CRIU used to check for the existence of /sys/fs/selinux to see if SELinux is enabled on a system. We have seen systems with SELinux kind of enabled but reading out the labels gives does not return real labels.
To work around this, this commit adds a check during LSM detection if SELinux labels are in the right format. For CRIU this check means to see if there are at least 3 ':' in a label. If not CRIU switches to no LSM mode.
Fixes: #1402

lsm: handle half initialized SELinux setups

---

criu/sk-unix.c
test/zdtm/static/Makefile
test/zdtm/static/sk-unix-dgram-ghost.c
test/zdtm/static/sk-unix-dgram-ghost.desc

This patch fixes deadlock that appears on ghost DGRAM unix sockets.
Problem is that wake_connected_sockets() function *should* be called
strictly after fle->stage >= FLE_OPEN.
Explanation:
Consider situation, we have ghost unix DGRAM socket (peer socket),
and also have several sockets that connected to this peer socket.
How restore of that picture works?
In files subsystem we have open_fdinfos(pstree_item*) function that calls open_fd()
function for *every* fd of task. open_fd() function calls appropriate
file descriptor "open" handler that may return "1" which means "try again later".
This retcode means, that some additional resources is needed to fully restore file
descriptor. For *ghost* UNIX sockets, for instance, we need to have peer socket
file descriptor *before* we can open and …

Fix deadlock for ghost DGRAM unix socket

---

compel/include/uapi/ksigset.h
compel/src/lib/infect.c
test/zdtm/static/Makefile
test/zdtm/static/sigtrap.c
test/zdtm/static/sigtrap.desc

This is the workaround for #1429.
The parasite code contains instructions that trigger SIGTRAP to stop at certain points. In such cases, the kernel sends a force SIGTRAP that can't be ignored and if it is blocked, the kernel resets its signal handler to a default one and unblocks it. It means that if we want to  save the origin signal handle

parasite: don't block SIGTRAP

---

criu/kerndat.c

While Dumping the process, it fails and exits as a user because of kerndat_uffd() returns -1 and due permission error 
uffd = syscall(SYS_userfaultfd, flags); this function fails inturn kerndat_uffd() fails. 
In the change it ignores the permission error and proceeds further.

uffd: fixed for exiting exiting program as user

---

criu/mem.c

One should never rely on errno if libc syscall is successful. We can
either see an errno set from some previous failed syscall or even errno
set by a this successful libc syscall. So lets check ret first.
Fixes: 1ccdaf47 ("criu: add pidfd based pid reuse detection for RPC
clients")

mem/pidfd: fix poll retry error checking

---

scripts/ci/docker-test.sh
scripts/ci/podman-test.sh

Now that the Ubuntu kernel is no longer broken with regards to overlayfs, let's switch back to overlayfs instead of devicemapper and
vfs graphdrivers.

ci: no longer avoid overlayfs

---

criu/include/uffd.h
criu/kerndat.c
criu/uffd.c

Else "Failed to get uffd API" and "Incompatible uffd API ..." errors are
just ignored, which is probably not what we want.
Fixes: cfdeac4a4 ("kerndat: Handle non-root mode when checking uffd")

kdat: make kerndat_uffd differentiate -EPERM and -1 from uffd_open

---

Documentation/criu.txt

The `--join-ns` option was introduced with commits https://github.com/checkpoint-restore/criu/commit/2cf17cd  and https://github.com/checkpoint-restore/criu/commit/790ec46.
Closes: #1054

criu(8): document --join-ns option

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This way users would be able to create more meaningfull pull-requests
and issues. And we would not need to ask them to provide basic
information each time.

github: Add templates for new issues and pull requests

---

criu/include/cr_options.h

The `SET_CHAR_OPT(__dest, __src)` macro is essentially:
```
free(opts.__dest);
opts.__dest = xstrdup(__src);
```
So if __dest == __src the string that get's copied is freed. This e.g.
is the case in criu/lsm.c
```
int lsm_check_opts(void)
{
char *aux;
if (!opts.lsm_supplied)
return 0;
aux = strchr(opts.lsm_profile, ':');
if (aux == NULL) {
pr_err("invalid argument %s for --lsm-profile\n", opts.lsm_profile);
return -1;
}
*aux = '\0';
aux++;
if (strcmp(opts.lsm_profile, "apparmor") == 0) {
if (kdat.lsm != LSMTYPE__APPARMOR) {
pr_err("apparmor LSM specified but apparmor not supported by kernel\n");
return -1;
}
SET_CHAR_OPTS(lsm_profile, aux);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
} else if (strcmp(opts.lsm_profile, "selinux") == 0) {
if (kdat.lsm != LSMTYPE__SELINUX) {
pr_err("selinux LSM …
```

cr_options: handle the case where __dest == __src in SET_CHAR_OPTS

---

.github/workflows/docker-test.yml

Ubuntu 18.04 still has a problem with overlayfs and breaks CRIU
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1857257

ci: update docker test matrix

---

test/zdtm_ct.c

Although CentOS 8 comes with 4.18 kernel it has time namespace patches backported but not all the required once. This changes the kernel version check from major == 5 to major <= 5 to also exclude CentOS 8.

test: skip time namespaced tests on <= 5

---

test/zdtm/static/tun_ns.desc

The tun_ns test was introduced with https://github.com/checkpoint-restore/criu/commit/7e355e7 and https://github.com/checkpoint-restore/criu/commit/3ba0893, however, these commits didn't add per-test dependencies required for the test. Per-test dependencies are listed in the `.desc` file as `'deps': [<list>]`. These dependencies are made available inside the test namespace and without the ip dependency, the tests fails on Fedora 34 with `Error: ipv4: FIB table does not exist.`

zdtm/tun_ns: add per-test dependencies

---

scripts/ci/docker-test.sh

This patch improves the changes from 19be9ced9. To use the newer version of containerd, we need to make sure that the containerd service has been restarted after install. Instead of hard-coding a version number, we can use github API to get the latest release. In addition, the tar file contains all binary files in a `./bin` sub-folder. Thus, it should be extracted in `/usr`.

docker-test: use latest containerd release

---

test/zdtm/lib/Makefile
test/zdtm/static/Makefile

These files use $PKG_CONFIG before they include the common files that
setup a default, so set early defaults in them too.
Signed-off-by: Mike Frysinger <vapier@chromium.org>

add PKG_CONFIG default in a few more places

---

criu/bfd.c
criu/include/util.h
criu/util.c

The callers of bread() and bwrite() assume the operation reads/writes
the complete length of the passed buffer.
We must loop when invoking the read()/write() APIs.
Fixes #1504

bfd: loop through read()/write() when the action is incomplete

---

.gitignore
Makefile
criu/Makefile
criu/config.c
criu/include/util.h
criu/unittest/Makefile
criu/unittest/mock.c
criu/unittest/unit.c
scripts/ci/run-ci-tests.sh
test/others/config-file/Makefile
test/others/config-file/conf1.test
test/others/config-file/conf2.test
test/others/config-file/conf3.test
test/others/config-file/run.sh

Trying to see how robust the configuration parser I was able to crash CRIU pretty quickly. This fixes a few crashes in the existing configuration file parser.
This also adds tests for not tested option parsing and configuration file handling.

Make config file parser more robust

---

test/zdtm/static/Makefile
test/zdtm/static/netns_lock.c
test/zdtm/static/netns_lock.desc
test/zdtm/static/netns_lock.hook

This test would be useful when testing that the network is locked using different ways (using iptables currently and eBPF later).
When CRIU dumps a process in a network namespace it locks the network so that no packets from peer enters the stack, otherwise RST will be sent by a kernel causing the connection to fail.
In netns_lock.c we try to enter the netns created by post-start hook so that criu locks the network namespace between dump and restore.
A TCP server is started in post-start hook inside the test netns and runs in the background detached from its parent so that it stays alive for the duration of the test.
Other hooks (pre-dump, pre-restore, post-restore) try to connect to the server.
Pre-dump and post-restore hooks should be able to connect successfully.
Pre-restore hook should …

zdtm: add network namespace locking test

---

criu/files.c

If inherit-fd is read from a config file its buffer will be freed after the config file is parsed but before task restore, which is when we need to use the mapping. Therefore, when adding an inherit-fd mapping to the opts list, copy the key string to a new buffer and free all such buffers after task restore.

Keep inherit-fd strings alive until task restore

---

compel/arch/mips/src/lib/include/uapi/asm/sigframe.h
criu/arch/mips/include/asm/restore.h
criu/arch/mips/include/asm/restorer.h

The mips64el-cross test target started to show following error:
`error: listing the stack pointer register '$29' in a clobber list is deprecated [-Werror=deprecated]`
This fixes it in three different places by removing '$29' from the clobber list. This is only compile tested as we have no mips hardware for testing.

ci: fix mips64el-cross test

---

test/zdtm/static/netns_lock.c
test/zdtm/static/netns_lock.hook

As mentioned in https://github.com/checkpoint-restore/criu/issues/1530 netns_lock test fails in jenkins iterative tests.
```netns_lock``` test is highly dependent on the order of the hooks, and iterations causes the ```--pre-dump``` hook to be called multiple times which expectedly causes the test to fail.
https://ci.kernoops.org/job/CRIU/job/CRIU-iter/job/criu-dev/431/testReport/(root)/criu/zdtm_static_netns_lock/
This only fixes the jenkins test failure and not the random CentOS7 failure mentioned in the issue. 
Signed-off-by: Zeyad Yasser <zeyady98@gmail.com>

test: fix netns_lock CI test failure

---

criu/cgroup.c
criu/cr-restore.c

Cgroup yard is setup in crtools_prepare_shared. But it is not cleaned up
properly in some code path, which leads cgroup mountpoint leaking.
We can see this type of errors in runc's issue:https://github.com/opencontainers/runc/issues/3042

restore: cleanup cgroup properly in error path

---

test/zdtm.py

This is useful to investigate problems on predump iterations. After this
patch test output with "--pre=2 --sbs" would have new usefull stop
points:
========================== Run zdtm/static/env00 in h ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Pause at iter. Press Enter to continue.
Run criu pre-dump
Pause at iter. Press Enter to continue.
Run criu pre-dump
Pause at pre-dump. Press Enter to continue.
Run criu dump

zdtm: make --sbs also stop on each predump/snap iteration

---

scripts/build/Dockerfile.openj9-alpine
scripts/build/Dockerfile.openj9-ubuntu

Make sure to remove all files created from previous local build before compiling in the container.

ci/openj9: run mrproper before make

---

lib/py/images/images.py
scripts/ci/run-ci-tests.sh

This fixes Jenkins errors like:
```
b'test/dump/zdtm/static/msgque/63/1/ipcns-msg-11.img'  encode fails: expected bytes-like object, not str
b'test/dump/zdtm/static/msgque/63/1/ipcns-msg-11.img' pretty  encode fails: expected bytes-like object, not str
FAIL
```
and also adds the test case to GitHub based CI.

Fix another crit-recode Jenkins error

---

compel/include/uapi/infect.h
criu/cr-restore.c
criu/include/posix-timer.h
criu/parasite-syscall.c
criu/pie/restorer.c
criu/proc_parse.c
criu/seize.c
images/timer.proto
test/zdtm/static/Makefile
test/zdtm/static/pthread_timers.c

When sigev_notify_thread_id is not set, get_pid will return a NULL
pointer and do_timer_create will return -EINVAL in kernel. So criu
will failed to create posix timer:
(09.806760) pie: 41301: Error (criu/pie/restorer.c:1998): Can't restore posix timers -22
(09.806824) pie: 41301: Error (criu/pie/restorer.c:2133): Restorer fail 41301
(09.891880) Error (criu/cr-restore.c:2596): Restoring FAILED.
Signed-off-by: Liu Chao <liuchao173@huawei.com>

criu: dump and restore notify_thread_id of posix timer

---

Documentation/Makefile
Documentation/criu-ns.txt
criu/Makefile
scripts/criu-ns

This pull request adds a man page for the [`criu-ns`](https://criu.org/CR_in_namespace) script and includes it in the install/uninstall criu makefile targets.

criu-ns: add man page and install target

---

scripts/ci/podman-test.sh

GitHub Actions already has Podman installed. No need to install it a second time.

ci: use pre-installed Podman

---

criu/pie/parasite.c

If retcode of dump_posix_timers is not zero it is treated as an error in
compel_rpc_sync. And currently we can return positive overrun of last
timer (if we are lucky and it is not zero) as retcode of function
dump_posix_timers, let's fix it. Also I don't see any point in putting
negative value into .overrun on error path, fix it too.

posix-timers: fix getoverrun error handling

---

.github/workflows/fedora-rawhide-test.yml
scripts/build/Makefile
scripts/ci/Makefile

Fedora Rawhide updated to a glibc using clone3(). clone3() is, however, not yet part of the seccomp filter. Unfortunately 'docker build' does not allow dropping seccomp but luckily 'podman build' does.
This switches the Fedora Rawhide test to use Podman. Podman is part of GitHub Actions and no additional packages need to be installed.

ci: fix Fedora Rawhide

---

test/zdtm/static/Makefile

Improves while loop readability.

zdtm: fix indentation in Makefile wait_stop target

---

criu/cr-dump.c

Otherwise, criu pre-dump can fail with errors like this:
lib/infect.c:650: Unable to connect a transport socket: Permission denied'

dump: suspend/resume lsm on pre-dump

---

test/jenkins/_run_ct
test/jenkins/run_ct

Jenkins test runs are failing with:
./test/jenkins/run_ct ./test/jenkins/crit.sh
./test/jenkins/crit.sh: 3: source: not found
Switch to bash which has 'source'.
Fixes: https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-crit/job/criu-dev/627/console
CC: @mihalicyn

ci: fix 'crit.sh: 3: source: not found'

---

test/zdtm/static/pthread_timers.c

On Virtuozzo7 jenkins we see a fail of criu-dev zdtm:
===================== Run zdtm/static/pthread_timers in ns =====================
Start test
./pthread_timers --pidfile=pthread_timers.pid --outfile=pthread_timers.out
Run criu dump
=[log]=> dump/zdtm/static/pthread_timers/112/1/dump.log
------------------------ grep Error ------------------------
(00.004817) netlink: Collect netlink sock 0x1cad6e21
(00.004821) netlink: Collect netlink sock 0x1cad6e22
(00.004831) Collecting pidns 9/112
(00.004886) No parent images directory provided
(00.004903) Warn  (criu/lsm.c:328): don't know how to suspend LSM 0
------------------------ ERROR OVER ------------------------
Run criu restore
4: Old maps lost: set([])
4: New maps appeared: set([u'7fe4c54ca000-7fe4c54cb000 ---p', …

zdtm/pthread_timers: make sure glibc allocated SIGEV_THREAD's stack

---

criu/files-reg.c

On systems where there is no build_id we get a warning for each run
Warn  (criu/files-reg.c:1458): Couldn't find the build-id note for file with fd 15
Change the log level to debug for this message as the file just does not have
a build_id and printing a warning clutters the CI logs.

files-reg: do not print a warning if a file has no build_id

---

criu/lsm.c

Without any LSM detected CRIU would print a warning for every run:
Warn  (criu/lsm.c:328): don't know how to suspend LSM 0
Which clutters up the CI logs.
Change the message to a debug message.
CC: @avagin @brauner

lsm: do not print a warning if no LSM has been detected

---

.github/workflows/lint.yml
criu/action-scripts.c
criu/cgroup.c
criu/config.c
criu/external.c
criu/filesystems.c
criu/include/cr_options.h
criu/include/plugin.h
criu/namespaces.c

We have some code written with the assumption that argv is never
destroyed, but when we handle configs, we construct an argv-like array
for each config, parse it and release it.
I am still not sure that we need to release the memory of per-config argv
arrays... The current scheme is going to be a source of used-after-free
bugs. When we will add the non-privileged mode, all these bugs will be
serious security issues.

configs: fix used after free cases

---

test/zdtm/static/net_lock_socket_iptables.desc
test/zdtm/static/net_lock_socket_iptables6.desc
test/zdtm/static/net_lock_socket_nftables.desc
test/zdtm/static/net_lock_socket_nftables6.desc
test/zdtm/static/netns_lock_iptables.desc
test/zdtm/static/netns_lock_nftables.desc

In test/jenkins/{crit.sh,criu-dump}, ZDTM is run with --norst,
Causing tests to only go through dump wihtout restoring.
The network locking tests are highly dependant on dump/restore hooks
causing them to hang when run with --norst.
We just add a reqrst flag to all network lock tests.
Signed-off-by: Zeyad Yasser <zeyady98@gmail.com>

zdtm: fix network lock tests when run with --norst

---

criu/autofs.c
criu/include/namespaces.h
criu/mount.c
criu/namespaces.c
criu/sk-unix.c

When CONFIG_BINFMT_MISC_VIRTUALIZED is enabled, I found stats-dump is write to /, but not  work directory in dump  process. Finaly I found criu do not restore cwd when restoring mnt ns. The patch series do the following:
-  add helpers to switch/restore mnt ns
-  restore current work directory after restoring mnt ns in cr_dump_task
- use swich_mnt_ns/restore_mnt_ns helpers to simplify code in open_mountpoint

restore cwd when restore mnt namespace

---

lib/Makefile
scripts/ci/podman-test.sh

Since commit 1c25914 compiling [crun](http://github.com/containers/crun) with libcriu also requires `/usr/include/criu/rpc.pb-c.h`

lib: install images/rpc.pb-c.h

---

.gitignore

The build directory is generated when running make install.

gitignore: add build directory

---

criu/mount.c

In the function dump_one_fs(), there's a comment that says "mnt_bind is
a cycled list, so list_for_each can't be used here." That means that the
list head of the list is also a node of the list.
The subsequent list_for_each_entry() marks all the mount info nodes as
dumped, except it skips the list head, which is also a mount info.
This is the bug we fix.
This bug made CRIU dump a file system twice.
See https://github.com/checkpoint-restore/criu-image-streamer/issues/8

mount: fix double-dump file system bug

---

scripts/build/Dockerfile.openj9-alpine
scripts/build/Dockerfile.openj9-ubuntu

The AdoptOpenJDK docker images have been deprecated in favor of
eclipse-temurin.
https://github.com/AdoptOpenJDK/openjdk-docker/pull/604

ci: Update openj9 container images

---

Documentation/criu.txt

Support for external net namespaces has been introduced with commit c2b21fbf.

criu(8): add --external net option

---

Makefile
Makefile.install
criu/cr-restore.c
criu/file-ids.c
criu/files-reg.c
criu/include/criu-plugin.h
criu/plugin.c
criu/proc_parse.c
plugins/amdgpu/Makefile
plugins/amdgpu/dummy_plugin.c

Hi @checkpoint-restore/maintainers ,
Thank you for the review feedback on our previous RFC PR - https://github.com/checkpoint-restore/criu/pull/1519.
As per the recommendation, we have split our work into two parts and we'll close the previous PR, #1519  
1 - This Pull Request
*  brings in the proposed changes to CRIU
*  new hooks and a dummy plugin
*  some workaround/fixes for issues seen with CRIU to support amdgpu_plugin
2 - https://github.com/RadeonOpenCompute/criu/commits/amdgpu_rfc-210715-2
*  changes that implement actual amdgpu_plugin
*  several features such as multi gpu support, fast checkpoint restore using SDMA. 
*  fixes for lint, clang, fedora32, ubuntu focal build failures.
*  sets up build dependencies on libdrm which is required for amdgpu_plugin
There will be another PR …

Amdgpu rfc 210715 1

---

Documentation/Makefile
criu/Makefile
scripts/criu-ns

PEP 394 recommends changing python shebangs to python3 when Python 3.x is supported. This is similar to crit-python3.

criu-ns: change python shebang to python3

---

Documentation/criu.txt
criu/sk-tcp.c
test/zdtm/static/Makefile
test/zdtm/static/socket-tcp-close2.c
test/zdtm/static/socket-tcp-close2.desc

Since commit e42f5e0 ("tcp: allow to specify --tcp-close on dump"),
--tcp-close option can be used when checkpointing. This option skips
checkpointing TCP_CLOSE socket's state. However, when restoring, we
still try to restore TCP_CLOSE socket's state. As a result, a
non-existent protobuf image is opened.
This commit allows dumping TCP_CLOSE socket's state in --tcp-close case.
This commit also removes a redundant check for TCP_LISTEN state in
restore_one_tcp as TCP_LISTEN socket cannot reach this function
Fixes: #1523

tcp: Skip restoring TCP state when dumping with --tcp-close

---

Makefile
lib/c/criu.c
lib/c/criu.h
test/others/libcriu/.gitignore
test/others/libcriu/Makefile
test/others/libcriu/run.sh
test/others/libcriu/test_iters.c
test/others/libcriu/test_join_ns.c
test/others/libcriu/test_notify.c
test/others/libcriu/test_self.c
test/others/libcriu/test_sub.c

We use the join-ns RPC API in runc to enable checkpoint/restore of containers with shared namespaces. Shared namespaces are often used when containers run inside Kubernetes Pod. However, crun is using libcriu to interface with CRIU and libcriu currently doesn't provide an API for join-ns. This pull request adds the libcriu API necessary to enable checkpoint/restore of containers with shared namespaces with crun.

libcriu: add API for join-ns option

---

.github/workflows/gcov-test.yml
Makefile

Replace deprecated codecov bash uploader with new version:
https://about.codecov.io/blog/introducing-codecovs-new-uploader/

ci: replace deprecated codecov bash uploader

---

.github/workflows/lint.yml
scripts/ci/run-ci-tests.sh

Newer kernels (5.11) require echo 1 > /proc/sys/vm/unprivileged_userfaultfd
Without the 'echo 1' the kernel prints a message like this:
uffd: Set unprivileged_userfaultfd sysctl knob to 1 if kernel faults must be handled without obtaining CAP_SYS_PTRACE capability
I also pinned the clang-format to Fedora 34 which comes with clang 12. Fedora 35 has clang 13 which formats the code differently.

ci: fix userfaultfd and clang-format test failures

---

criu/cr-check.c
criu/include/kerndat.h
criu/include/sockets.h
criu/kerndat.c
criu/sockets.c
images/sk-opts.proto
test/zdtm/static/Makefile
test/zdtm/static/sock_opts02.c
test/zdtm/static/sock_opts02.desc

When one sets socket buffer sizes with setsockopt(SO_{SND,RCV}BUF*), kernel sets corresponding SOCK_SNDBUF_LOCK or SOCK_RCVBUF_LOCK flags on struct sock. It means that such a socket with explicitly changed buffer size can not be auto-adjusted by kernel (e.g. if there is free memory kernel can auto-increase default socket buffers to improve performance). (see tcp_fixup_rcvbuf() and tcp_sndbuf_expand())  
CRIU is always changing buf sizes on restore, that means that all sockets receive lock flags on struct sock and become non-auto-adjusted after migration. In some cases it can decrease performance of network connections quite a lot.  
So let's c/r socket buf locks (SO_BUF_LOCKS), so that sockets for which auto-adjustment is available does not lose it.  
Origin of the problem: 
We have a …

Socket bufs lock support (tcp perfomance decrease after migration fix)

---

criu/cr-dump.c

A zombie process with 0 sid has a session leader in
outer pidns and has ignored SIGHUP. So there is no
process in this pid ns to wait on it. No need to
dump it.

cr-dump: do not dump zombie process with sid 0

---

.cirrus.yml

We see error in centos8 ci on restore of socket-raw test:
inet: \tRestore: family AF_INET type SOCK_RAW proto 66
port 66 state TCP_CLOSE src_addr 0.0.0.0
Error (criu/sk-inet.c:834): inet: Can't create inet socket:
Protocol not supported
Centos 8 kernel replaces IPPROTO_MPTCP(262) with "in-kernel" value
IPPROTO_MPTCP_KERN(66) on inet_create(), but later shows this inkernel
value to criu when listing sockets info. Same code in inet_create()
returns EPROTONOSUPPORT on the attempr to create socket with
IPPROTO_MPTCP_KERN. So this ci error is completely rh8 kernel related.
Kernel should not show "in-kernel" value to userspace. But anyway this
is already changed in Centos 9 kernel, so we can just skip socket-raw
test on Centos 8.

ci: disable socket-raw test on centos8

---

test/zdtm/static/mprotect00.c
test/zdtm/static/shm-mp.c

Clang-format v13 on my Fedora 35 complains about these hunks, more over
reading the formating we had before is a pain:
```
} else /* comment */
if (smth) {
fail("")
return -1;
}
```
Let's make explicit {} braces for else, this way it looks much better.
Fixes: 93dd984ca ("Run 'make indent' on all C files")

clang-format/zdtm: fix clang complains about strange elseifs

---

.github/workflows/lint.yml

Now when we fixed clang-format complains in zdtm, let's switch to lates
clang-format available. This is effectively a revert of commit 07a2f0265
("ci: use Fedora 34 for lint CI runs").

ci: Use latest Fedora for lint ci runs again

---

.cirrus.yml

CentOS 8 goes EOL at the end of 2021. This switches our CentOS 8 based tests to CentOS Stream 8 which should be supported until 2024.

ci: switch to centos-stream-8

---

criu/cr-check.c

Always wait() for forked child processes. It avoid zombie processes in containers that don't have an init process reaping orphans.

check: cleanup child processes

---

criu/files-reg.c
criu/include/mount.h
criu/mount.c
criu/proc_parse.c
test/zdtm/static/mntns_ghost01.c

Port patches from Virtuozzo criu:
files-reg: temporary remount writable the mount we do unlink on
ghost/mount: allocate remounted_rw in shmem to get info from other processes
files-reg: fix error handling of rm_parent_dirs
files-reg: fix error handling in open_path
Should fix the problem related to https://github.com/checkpoint-restore/criu/pull/1643
Note: test mntns_ghost01 detects the problem fixed by 4-th patch when error handling  (1-2 patches) is fixed.

Fix ghost files and improve error handling

---

criu/fdstore.c
test/zdtm/lib/test.c
test/zdtm/static/child_subreaper_and_reparent.c
test/zdtm/static/child_subreaper_existing_child.c
test/zdtm/static/file_fown.c

When we declare struct and at the same time declare variable pointer of
this struct type, it looks like clang-format threats "*" as a
multiplication operator instead of indirection (pointer declaration)
operator and puts spaces on both sides, which looks wrong.
I decided to just disable clang, other ideas are welcome. Also I considered the idea to separate structure declaration from pointer declaration, but it would not work for unnamed structures, disabling clang looks more universal.

clang-format: disable wrong struct pointer declaration format

---

scripts/ci/vagrant.sh
test/jenkins/criu-fault.sh

This disables know broken tests and enables fixed tests. The disabled tests are tracked in the mentioned tickets.
The disabled tests are still being run on older kernels and this helps us to easily detect is something else than the already known broken tests does not work.
Broken tests are being tracked at
* https://github.com/checkpoint-restore/criu/issues/1669
* https://github.com/checkpoint-restore/criu/issues/1635
This also enables previously disabled BPF related tests:
* https://github.com/checkpoint-restore/criu/issues/1354

ci: disable broken tests until fixed

---

test/jenkins/criu-dedup.sh
test/jenkins/criu-fault.sh
test/jenkins/criu-fcg.sh

Looking at CI logs there are often messages like:
"[WARNING] Option --keep-going is more useful when running multiple tests"
This commit removes '--keep-going' from single zdtm test runs.

test: do not use --keep-going for single zdtm tests

---

criu/sk-unix.c
scripts/ci/vagrant.sh

Since commit 83301b5367a98 ("af_unix: Set TCP_ESTABLISHED for datagram sockets
too") in Linux kernel, SOCK_DGRAM unix sockets can have TCP_ESTABLISHED state
when connected. So we need to fix checks that assume SOCK_DRAM sockets cannot
have TCP_ESTABLISHED state.
I look around for TCP_ESTABLISHED usages in sk-unix and there is one place I'm not 
sure about
```
diff --git a/criu/sk-unix.c b/criu/sk-unix.c
index 8037d9cf2..d3402c3ac 100644
--- a/criu/sk-unix.c
+++ b/criu/sk-unix.c
@@ -460,7 +460,7 @@ static int dump_one_unix_fd(int lfd, uint32_t id, const struct fd_parms *p)
pr_warn("Shutdown mismatch %u:%d -> %u:%d\n", ue->ino, ue->shutdown, peer->sd.ino,
peer->shutdown);
}
-       } else if (ue->state == TCP_ESTABLISHED) {
+       } else if (ue->state == TCP_ESTABLISHED && ue->type != …
```

sk-unix: Fix TCP_ESTABLISHED checks in unix sockets

---

scripts/build/Dockerfile.alpine

The default version of ps in Alpine image is very limited. It is based on the one from busybox and doesn't support options used in zdtm such as `-p`.
```
ps --help
BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.
Usage: ps [-o COL1,COL2=HEADER] [-T]
Show list of processes
-o COL1,COL2=HEADER	Select columns for display
-T
```

ci: install procps in alpine

---

test/zdtm_ct.c

We try to disable time namespace based testing for kernels older than 5.11. But we fail to come up with the correct if condition.
This changes (major <= 5) to (major < 5). There are no kernels with major > 5 so currently the time namespace based are never run. This should finally change it to run time namespace based tests on kernel versions newer than 5.10.

test: another try to correctly fix the kernel version

---

compel/arch/x86/src/lib/include/uapi/asm/fpu.h
compel/arch/x86/src/lib/infect.c
test/jenkins/criu-fault.sh

Hi there :)
These patches aimed to fix the problem from the https://github.com/checkpoint-restore/criu/issues/1635 issue.
I've grabbed VM from Amazon and tested that it's working fine now. The problem was that after putting garbage into the pkru registers our victim's processes catch segfaults because they lose access to their own VMAs (see `arch_vma_access_permitted` function https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/arch/x86/include/asm/mmu_context.h#L207).
Thanks,
Alex

x86/compel/fault-inject: bound features to test

---

Documentation/criu.txt
criu/crtools.c

A timeout was introduced in https://github.com/checkpoint-restore/criu/commit/d0ff730 to prevent criu dump from being able to hang indefinitely. The `--timeout` option allows users to adjust the time limit in seconds for collecting tasks during the dump operation.

Add documentation for --timeout option

---

criu/namespaces.c

UNS_FDOUT means only that a userns call will return a file descriptor.

usernsd: UNS_FDOUT should not require an input descriptor

---

scripts/build/Dockerfile.fedora.tmpl
scripts/ci/run-ci-tests.sh

This is a temporary solution for the problem described in the following issue. It would allow us to run CI tests until CRIU has rseq support.
https://github.com/checkpoint-restore/criu/issues/1696

ci: fix fedora rawhide tests

---

criu/cr-service.c
images/rpc.proto
lib/c/criu.c
lib/c/criu.h
test/others/libcriu/.gitignore
test/others/libcriu/Makefile
test/others/libcriu/lib.h
test/others/libcriu/run.sh
test/others/libcriu/test_iters.c
test/others/libcriu/test_notify.c
test/others/libcriu/test_pre_dump.c

In contrast to the CLI it is not possible to do a single pre-dump via
RPC and thus libcriu. In cr-service.c pre-dump always goes into a
pre-dump loop followed by a final dump. runc already works around this
to only do a single pre-dump by killing the CRIU process waiting for the
message for the final dump.
Trying to implement pre-dump in crun via libcriu it is not as easy to
work around CRIU's pre-dump loop expectations as with runc that directly
talks to CRIU via RPC.
We know that LXC/LXD also does single pre-dumps using the CLI and runc
also only does single pre-dumps by misusing the pre-dump loop interface.
With this commit it is possible to trigger a single pre-dump via RPC and
libcriu without misusing the interface provided via cr-service.c. So
this commit basically updates CRIU to …

libcriu: add single pre-dump support

---

test/zdtm.py
test/zdtm_ct.c

This PR addresses the issue from https://github.com/checkpoint-restore/criu/issues/1699
We use implicit make rules to produce `test/umount2` and `test/zdtm_ct` binaries, but when `make umount2`
is called from zdtm.py which is called from `make test` (under the CRIU tree root) this nested make inherits `MAKEFLAGS`
variable with the value `rR --no-print-directory` and that's the problem because `-r` means "no builtin rules".
Let's just drop this variable value for `make umount2` and `make zdtm_ct` this is safe.

Fix `make test` compile failure

---

criu/cr-service.c
criu/crtools.c
criu/include/cr_options.h

We have multiple options which are valid only on restore or only on dump or in any other specific criu mode, so it would be useful to have info about current mode in opts so that we can validate other options against current mode.
Plan is to use it for mount-v2 (switch from current restore mount engine to a new one) option as it is only valid on restore, and this would make handling of different types of mountpoints much easier.
- When criu mode is set from main() we just parse mode from argv[optind] just after parse_options() found optind of the command. Note that opts.mode is available before check_options().
- For rpc service we reset opts.mode to CR_SWRK each time we restart cr_service_work(), in the original service process we still have CR_SERVICE to differentiate between them, and …

Export current criu mode to opts

---

criu/fsnotify.c
criu/include/mount.h
criu/mount.c
criu/proc_parse.c

We face that btrfs returns anonymous device in stat instead of real
superblock dev for volumes, thus __open_mountpoint can't open btrfs
mountpoint due to dev missmatch between stat and mountinfo. We can use
special helper get_sdev_from_fd instead of stat to get real dev of fd.
New get_sdev_from_fd helper first gets mnt_id from fd using fdinfo and
then converts mnt_id to sdev using mountinfo.

mount/btrfs: make __open_mountpoint fallback to get_sdev_from_fd

---

.lgtm.yml

A couple of months (or years) ago I looked into lgtm.com for CRIU. Today on a pull request I saw result from lgtm.com for the first time and it failed. Not sure what triggered the lgtm.com message into the CRIU repository, but with the .lgtm.yml file in this commit lgtm.com can actually build CRIU.

ci: added .lgtm.yml file

---

lib/c/criu.c
lib/c/criu.h
test/others/libcriu/.gitignore
test/others/libcriu/Makefile
test/others/libcriu/run.sh
test/others/libcriu/test_feature_check.c

This commit adds feature check support to libcriu. It already exists in the CLI and RPC and this just extends it to libcriu.
This commit provides one function to do all possible feature checks in one call. The parameter to the feature check function is a structure and the user can enable which features should be checked.
Using a structure makes the function extensible without the need to break the API/ABI in the future.

lib: introduce feature check in libcriu

---

test/zdtm/static/maps00.c

zdtm/static/maps00 case sometimes will cause SIGILL signal in arm64 platform.
<<ARM Coretex-A series Programmer's Guide for ARMv8-A>> notes:
> The ARM architecture does not require the hardware to ensure coherency
> between instruction caches and memory, even for locations of shared
> memory.
Therefore, we need flush dcache and icache for self-modifying code.

zdtm: fix zdtm/static/maps00 case in arm64

---

compel/plugins/std/string.c
compel/src/main.c
criu/config.c

This is a confusing change as it seems the original code was just wrong.
GCC 12 complains with:
```
In function ‘__conv_val’,
inlined from ‘std_strtoul’ at compel/plugins/std/string.c:202:7:
compel/plugins/std/string.c:154:24: error: array subscript 97 is above array bounds of ‘const char[37]’ [-Werror=array-bounds]
154 |                 return &conv_tab[__tolower(c)] - conv_tab;
|                        ^~~~~~~~~~~~~~~~~~~~~~~
compel/plugins/std/string.c: In function ‘std_strtoul’:
compel/plugins/std/string.c:10:19: note: while referencing ‘conv_tab’
10 | static const char conv_tab[] = "0123456789abcdefghijklmnopqrstuvwxyz";
|                   ^~~~~~~~
cc1: all warnings being treated as errors
```
Which sounds correct. The array conv_tab has just 37 elements.
If I understand the code …

fix GCC 12 failures

---

.github/workflows/cross-compile.yml

Running cross compile tests with Debian unstable sometimes fails due to missing or outdated packages.
In this patch we set [continue-on-error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) to prevent the GitHub Action workflow run from failing when one or more cross-compile tests with Debian unstable fails.
In other words, we can still see test errors with Debian _unstable_, but the workflow would fail only when the Debian _stable_ tests fail.

ci: set continue-on-error for cross-compile

---

test/zdtm/static/autofs.c

test/autofs: fix use-after-free

---

.cirrus.yml
.lgtm.yml
scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/vagrant.sh

The libbsd dependency is used to enable support for `setproctitle()` and `strlcpy()`.

ci: install libbsd dependency

---

criu/pstree.c

If we replace old_sid with current_sid we should also do same
replacement for matching pgid (=old_sid).
Reported in CRIU gitter by Younes Manton (@ymanton)

pstree: when updating sid for shell job also update matching pgid

---

criu/pie/restorer.c

As we call mmap syscall directly, the returned value in error case is the error
number not -1 like in libc wrapper. Use IS_ERR for correct checking in error
case.

restorer: Fix sys_mmap's returned value check

---

compel/arch/x86/src/lib/thread_area.c

When PTRACE_GET_THREAD_AREA errors on kernels with
!CONFIG_IA32_EMULATION beacuse of missing support (-EIO), compel should
ignore uch errors in native mode.
However the check for error type uses return value of ptrace rather than
errno, which will always result in error propagation.
Use errno to detect type of error to fix this.

compel: fix how PTRACE_GET_THREAD_AREA errors are handled

---

criu/crtools.c
criu/files.c
criu/include/util.h
criu/util.c

Transport socket names have to be unique for each criu run.
Fixes #1735 #1720

files: generate unique transport socket names

---

criu/bpfmap.c
criu/proc_parse.c
images/bpfmap-file.proto
scripts/build/Dockerfile.archlinux
test/zdtm/static/file_locks01.c

5.16 has changes which break CRIU when it comes to BPF and file maps.
This handles a new BPF related field in fdinfo and removes a flock test which is no longer supported.

Fix Fedora based CI on 5.16 and on Archlinux with glibc 2.35

---

test/zdtm.py

There is no 'err' argument for print(), it should be in grep_errors() in
line below.
Fixes: bed670f62 ("zdtm: print tails of all logs if a test has failed")

zdtm: fix missplacement of err=True

---

compel/arch/x86/src/lib/infect.c

During error injection tests there are random values loaded in some of
the registers. The kernel, however, has the following check:
if (mxcsr[0] & ~mxcsr_feature_mask)
return -EINVAL;
So depending on the random values loaded mxcsr might have values that
the kernel rejects with EINVAL. Setting mxcsr to zero during the tests
lets the error injection test pass.
Fixes: #1734

compel: set mxcsr during error injection to zero

---

criu/proc_parse.c

nonlinear information has been removed since the commit
1da4b35b001481df99 in kernel.
Signed-off-by: anatasluo <luolongjuna@gmail.com>

proc_smaps: remove useless nonlinear check

---

criu/mount.c

coverity CID 389202:
```
54int ext_mount_add(char *key, char *val)
55{
56        char *e_str;
57
1. alloc_fn: Storage is returned from allocation function malloc.
2. var_assign: Assigning: ___p = storage returned from malloc(strlen(key) + strlen(val) + 8UL).
3. Condition !___p, taking false branch.
4. leaked_storage: Variable ___p going out of scope leaks the storage it points to.
5. var_assign: Assigning: e_str = ({...; ___p;}).
58        e_str = xmalloc(strlen(key) + strlen(val) + 8);
6. Condition !e_str, taking false branch.
59        if (!e_str)
60                return -1;
...
7. noescape: Resource e_str is not freed or pointed-to in sprintf.
73        sprintf(e_str, "mnt[%s]:%s", key, val);
8. noescape: Resource e_str is not freed or pointed-to in add_external. [show details]
CID …
```

mount: fix e_str leak in ext_mount_add

---

criu/sk-unix.c

coverity CID 389193:
```
CID 389193 (#1 of 1): Printf format string issue (PW.BAD_PRINTF_FORMAT_STRING)
1. bad_printf_format_string: invalid format string conversion
598 pr_warn("Can't stat socket %#x(%s), skipping: %m (err %d)\n", id, rpath, errno);
```
Specifier "%#x" is wrong for id as it is of type uint32_t, let's change
it to "%#" PRIx32 "" to fix the problem.

sk-unix: fix uint32_t id variable printf format specifier

---

criu/config.c

coverity CID 389192:
```
550static int parse_join_ns(const char *ptr)
551{
...
553        char *ns;
554
1. alloc_fn: Storage is returned from allocation function strdup.
2. var_assign: Assigning: ___p = storage returned from strdup(ptr).
3. Condition !___p, taking false branch.
4. leaked_storage: Variable ___p going out of scope leaks the storage it points to.
5. var_assign: Assigning: ns = ({...; ___p;}).
555        ns = xstrdup(ptr);
6. Condition ns == NULL, taking false branch.
556        if (ns == NULL)
557                return -1;
558
7. noescape: Resource ns is not freed or pointed-to in strchr.
559        aux = strchr(ns, ':');
8. Condition aux == NULL, taking true branch.
560        if (aux == NULL)
CID 389192 (#1 of 1): Resource leak (RESOURCE_LEAK)9. leaked_storage: Variable ns …
```

config: fix ns leak in parse_join_ns

---

criu/net.c

coverity CID 389187:
```
3193int veth_pair_add(char *in, char *out)
3194{
3195        char *e_str;
3196
1. alloc_fn: Storage is returned from allocation function malloc.
2. var_assign: Assigning: ___p = storage returned from malloc(200UL).
3. Condition !___p, taking false branch.
4. leaked_storage: Variable ___p going out of scope leaks the storage it points to.
5. var_assign: Assigning: e_str = ({...; ___p;}).
3197        e_str = xmalloc(200); /* For 3 IFNAMSIZ + 8 service characters */
6. Condition !e_str, taking false branch.
3198        if (!e_str)
3199                return -1;
7. noescape: Resource e_str is not freed or pointed-to in snprintf.
3200        snprintf(e_str, 200, "veth[%s]:%s", in, out);
8. noescape: Resource e_str is not freed or pointed-to in add_external. [show …
```

net: fix e_str leak in veth_pair_add

---

criu/files.c

coverity CID 389190:
```
1538int inherit_fd_add(int fd, char *key)
1539{
1540        struct inherit_fd *inh;
...
2. alloc_fn: Storage is returned from allocation function malloc.
3. var_assign: Assigning: ___p = storage returned from malloc(32UL).
4. Condition !___p, taking false branch.
5. leaked_storage: Variable ___p going out of scope leaks the storage it points to.
6. var_assign: Assigning: inh = ({...; ___p;}).
1548        inh = xmalloc(sizeof *inh);
7. Condition inh == NULL, taking false branch.
1549        if (inh == NULL)
1550                return -1;
1551
...
9. Condition !___p, taking true branch.
1555        inh->inh_id = xstrdup(key);
10. Condition inh->inh_id == NULL, taking true branch.
1556        if (inh->inh_id == NULL)
CID 389190 (#1 of 1): Resource leak …
```

files: fix inh leak in inherit_fd_add

---

criu/sk-unix.c

coverity CID 389191:
```
int unix_sk_id_add(unsigned int ino)
2327{
2328        char *e_str;
2329
1. alloc_fn: Storage is returned from allocation function malloc.
2. var_assign: Assigning: ___p = storage returned from malloc(20UL).
3. Condition !___p, taking false branch.
4. leaked_storage: Variable ___p going out of scope leaks the storage it points to.
5. var_assign: Assigning: e_str = ({...; ___p;}).
2330        e_str = xmalloc(20);
6. Condition !e_str, taking false branch.
2331        if (!e_str)
2332                return -1;
7. noescape: Resource e_str is not freed or pointed-to in snprintf.
2333        snprintf(e_str, 20, "unix[%u]", ino);
8. noescape: Resource e_str is not freed or pointed-to in add_external. [show details]
CID 389191 (#1 of 1): Resource leak (RESOURCE_LEAK)9. …
```

sk-unix: fix e_str leak in unix_sk_id_add

---

criu/uffd.c

coverity CID 389197:
CID 389197 (#1 of 1): Invalid printf format string (PRINTF_ARGS)
format_error: Length modifier L not applicable to conversion specifier in %Lu. [show details]
284 pr_err("Incompatible uffd API: expected %Lu, got %Lu\n", UFFD_API, uffdio_api.api);
Looking on C11 standard it seems that "%Lu" is undefined, we better not
use this, see:
"L Specifies that a following a, A, e, E, f, F, g, or G conversion
specifier applies to a long double argument."
http://port70.net/~nsz/c/c11/n1570.html#7.21.6.1p7

uffd: fix __u64 print format specifier

---

criu/config.c
criu/mount-v2.c

On pre v5.15 kernel we don't have MOVE_MOUNT_SET_GROUP support and thus
all our ci logs are filled with "fallback" messages. Let's decrease log
level to debug, so that we don't see it in ci logs.

mount-v2: make mount engine fallback messages loglevel debug

---

criu/mount.c

We have three of "Can't mount at %s", let's distinguish simple mount
from bind-mount and re-mount to make log reading easier.
Found this when looking on https://github.com/checkpoint-restore/criu/issues/1778

Mount fix error message nits

---

scripts/ci/run-ci-tests.sh
test/zdtm.py
test/zdtm_mount_cgroups
test/zdtm_umount_cgroups

zdtm.py mounts two named controllers for tests. In CI, we run zdtm.py a few
times, so we can mount (create) these controllers once from the ci script to
avoid any unwanted effects.
Fixes: #1774

scripts/ci: create test cgroup controllers once

---

scripts/criu-ns

The init process can exit if it doesn't have any child processes and its
pidns is destroyed in this case. CRIU dump is running in the target pid
namespace and it kills dumped processes at the end. We need to create a
holder process to be sure that the pid namespace will not be destroy
before criu exits.
Fixes: #1775

criu-ns: add a helper to hold a pid namespace

---

criu/apparmor.c

```
criu/apparmor.c:679:26: error: 'fscanf' may overflow; destination buffer in argument 3 has size 48, but the corresponding specifier may require size 49 [-Werror,-Wfortify-source]
ret = fscanf(f, "%48s", contents);
```
The buffer size should be at least one larger than the fscanf maximum
field width.
Fixes: 8d992a680ef3 ("lsm: support checkpoint/restore of stacked apparmor profiles")

apparmor: Fix -Wfortify-source for Clang

---

criu/mount.c

Since https://reviews.llvm.org/D122271, Clang -Wset-but-unused-variable
gets smarter to warn about unused post-increments.

mount: fix -Wunused-but-set-variable for Clang 15

---

compel/include/uapi/infect-util.h
compel/src/lib/infect-util.c
compel/src/lib/infect.c
criu/fdstore.c
criu/pidfd-store.c
criu/unittest/mock.c
criu/util.c

CRIU has a few places where it creates unix sockets and their names have to be
unique for each criu run.
Fixes: #1798

criu: generate unique socket names

---

scripts/ci/docker-test.sh
scripts/ci/podman-test.sh

Switch to non overlaysfs tests for Podman and Docker.

ci: Ubuntu broke overlayfs again

---

scripts/ci/docker-test.sh
scripts/ci/podman-test.sh

Switch to non overlaysfs tests for Podman and Docker.
https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/1967924

ci: Switch to non overlaysfs tests

---

criu/cgroup.c
test/jenkins/crit.sh
test/jenkins/criu-dump.sh
test/zdtm/lib/zdtmtst.h
test/zdtm/static/Makefile
test/zdtm/static/cgroup_ignore.c
test/zdtm/static/cgroup_ignore.checkskip
test/zdtm/static/cgroup_ignore.desc

Using `--manage-cgroups=ignore` was still trying to restore cgroup properties at certain places.
Restoring a OCI container in a different cgroup (than the one it was checkpointed from) resulted in CRIU trying to put the container in the original cgroup but the container runtime (runc, crun) was putting it another cgroup. A second checkpoint of the container with two different cgroup settings did no longer work.
With this change CRIU really completely ignores the cgroup and the container can be checkpointed and restored multiple times even if the cgroup changes.
This PR includes a test to verify  `--manage-cgroups=ignore'` works as expected.

cgroup: fix --manage-cgroups=ignore

---

criu/bpfmap.c
criu/proc_parse.c
test/zdtm/static/bpf_array.c
test/zdtm/static/bpf_hash.c

`bpf_create_map_xattr()` has been replaced with `bpf_map_create()`: https://github.com/libbpf/libbpf/commit/6cfb97c
`DECLARE_LIBBPF_OPTS` has been renamed to `LIBBPF_OPTS`: https://github.com/libbpf/libbpf/commit/ea6c242

bpf: update deprecated API

---

criu/sk-unix.c

Commit d0308e5ecc1c ("sk-unix: make criu respect existing files while restoring ghost unix socket fd") broke return codes for bind_on_deleted(). Not only function will always return 0, but setting ret is pointless since it will be overriden by unlink() and rename()
~~Fix this by adding new err variable to store first-encountered error.~~
Simpilfy return codes and errno juggling. No one is relying on it. Also all encountered errors already print some info.

sk-unix: fix bind_on_deleted() return code

---

criu/cr-dump.c

It can be confusing to see error from post-dump action script and non
zero return from criu though at the same time see "Dumping finished
successfully" in log. I believe it is logical to consider post-dump
action script as a part of "dump" process so fail in it means that the
whole dump failed.

cr-dump: do not report success to logs if post-dump script failed

---

scripts/ci/podman-test.sh

GitHub Actions comes with pre-installed criu in /usr. configure scripts looking for CRIU will pickup the pre-installed version in /usr if we do not install CI criu also in /usr.
@rst0git: PTAL (without this the Podman test in https://github.com/checkpoint-restore/criu/pull/1862 fails once we increase the version to 3.17 because crun will pickup the wrong CRIU version)

test: install criu in /usr

---

scripts/ci/run-ci-tests.sh

Let's workaround race between `bridge` and `sit` tests by loading `sit` module before running zdtm suite
See also https://github.com/checkpoint-restore/criu/issues/1866

ci: workaround zdtm/static/bridge race with sit module load

---

.github/workflows/lint.yml

Fix for the following error that appears in the GitHub actions environment. This problem has been reported in https://github.com/actions/checkout/issues/760
```
fatal: unsafe repository ('/__w/criu/criu' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /__w/criu/criu
```

ci: Fix unsafe repository error

---

criu/mem.c
test/jenkins/criu-dedup.sh
test/jenkins/criu-lazy-migration.sh
test/jenkins/criu-lazy-pages.sh
test/jenkins/criu-pre-dump.sh
test/jenkins/criu-remote-lazy-pages.sh
test/jenkins/criu-snap.sh

As private hugetlb mappings are not pre-mapped, the content of them is restored
in the the restorer which cannot use page_read->read_pages. As a result, we
cannot recursively read the content of pre-dumped image in the parent directory
and use preadv to read the content from the last dumped image only. Therefore,
it may freeze while restoring when the content of mapping is in pre-dumped image
in parent directory.
We need to skip pre-dumping on hugetlb mappings to resolve the issue.
Fixes: #1868

mem: Skip pre-dumping on hugetlb mappings

---

Makefile
scripts/crit-setup.py

Name collision with an abandoned project named 'crit' in pypi causes pip to show crit (CRiu Image Tool) as outdated.  This patch updates crit to use the same version and license as criu.
```console
$ pip show crit
Name: crit
Version: 3.17
Summary: CRiu Image Tool
Home-page: https://github.com/checkpoint-restore/criu
Author: CRIU team
Author-email: criu@openvz.org
License: GPLv2
Location: /usr/local/lib/python3.10/site-packages
Requires: 
Required-by:
```

crit: Use same version as criu

---

plugins/amdgpu/Makefile

When building packages for CRIU the source directory might have a name different than `criu`.
Fixes: #1877
Reported-by: @siris

amdgpu/Makefile: Fix include path

---

Makefile.install
criu/include/plugin.h
plugins/amdgpu/Makefile

This patch fixes the following error which appears when building criu packages for Ubuntu/Debian.
mkdir: cannot create directory '/var/lib/criu': Permission denied

amdgpu: Set PLUGINDIR to /usr/lib/criu

---

.github/workflows/lint.yml

This allows us to only detect bad formating in PR changes but not all
the CRIU codebase.
I checked it in my repo here https://github.com/Snorch/criu/runs/6670451552

RFC: github: use git-clang-format instead of make indent

---

scripts/criu-ns

criu-ns script incorrectly compares the pidns fd with mntns fd.
Also reversed the condition in is_my_namespace function to align it
with the function name.
Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>

Fix the check for mnt namespace in criu-ns

---

criu/mount-v2.c
test/zdtm/static/Makefile
test/zdtm/static/mnt_ext_multiple.c
test/zdtm/static/mnt_ext_multiple.desc

It's a problem when while restoring sharing group we need to copy
sharing between to mounts with non-intersecting roots, because kernel
does not allow it.
We have a case https://github.com/opencontainers/runc/pull/3442, where
runc adds different devtmpfs file-bindmounts to container and there is
no fsroot mount in container for this devtmpfs, thus mount-v2 faces the
above problem.
Luckily for the case of external mounts which are in one sharing group
and which have non-intersecting roots, these mounts likely only have
external master with no sharing, so we can just copy sharing from
external source and make it slave as a workaround.
https://github.com/checkpoint-restore/criu/issues/1886

mount-v2: workaround for multiple external bindmounts with no common root

---

criu/hugetlb.c
criu/include/hugetlb.h
criu/proc_parse.c

Currently, the content of anonymous private hugetlb mapping is dumped in 2
different images: memfd approach and normal private mapping dumping. In memfd
approach, we dump the content of the backing pseudo file (/anon_hugepage). This
is incorrect and redundant since the mapping is private, the content of backing
file may differ from the content of the mapping. With this commit, we remove the
redundant memfd approach dump and only do the normal private mapping dump on
anonymous hugetlb mapping.
Run zdtm.py run -f h --keep-img always -t zdtm/static/maps09, du -h in the
dumped image directory
Before this commit
13M     test/dump/zdtm/static/maps09/55/1
After this commit
8.5M    test/dump/zdtm/static/maps09/55/1
The reduction in size is approximately 4MB which is the size of anonymous
private …

hugetlb: don't dump anonymous private hugetlb mapping using memfd approach

---

criu/util.c
test/zdtm/static/Makefile
test/zdtm/static/mnt_root_ext.c
test/zdtm/static/mnt_root_ext.desc
test/zdtm/static/mnt_root_ext.hook

Else we have a Segmentation fault in __move_mount_set_group() on
xfree(source_mp) if resolve_mountpoint() returned statically allocated
path.

util/mount-v2: fix resolve_mountpoint() to always return freeable pointer

---

Documentation/compel.txt
compel/include/uapi/infect.h
compel/src/lib/infect.c
criu/cr-dump.c
criu/cr-restore.c
criu/include/pid.h
criu/proc_parse.c
criu/pstree.c
criu/seize.c
images/core.proto
test/zdtm/static/Makefile
test/zdtm/static/stopped03.c
test/zdtm/static/stopped04.c

Criu is currently missing SIGTSTP signal support: infect reports unsupported signal.
Add SIGTSTP signal dump and restore. Add a corresponding field in the image, save it only if a task is in the stopped state.
Restore task state by sending desired stop signal if it is present in the image. Fallback to SIGSTOP if it's absent.

[RFC] Add SIGTSTP support

---

test/zdtm.py

Normally, vsyscall vma has VM_READ, VM_EXEC permission. However, when
CONFIG_LEGACY_VSYSCALL_XONLY=y, that vma only has VM_EXEC. This commit removes
the permission part when checking to skip vsyscall vma in x32 tests.
Signed-off-by: Bui Quang Minh <minhquangbui99@gmail.com>

zdtm: Remove permission part check for skipping vsyscall vma

---

criu/vdso.c

On Arch Linux with 5.18.3-zen1-1-zen kernel, the vdso's size is 3 pages which
exceeds the current 2-page reserved buffer. This commit simply increases the
reserved buffer size to 4 pages.
Fixes: https://github.com/checkpoint-restore/criu/issues/1916
Signed-off-by: Bui Quang Minh <minhquangbui99@gmail.com>

vdso-compat: Increase the reserved buffer for compat vdso

---

test/zdtm.py
test/zdtm/static/mnt_root_ext.c

1) "zdtm: make root mount private in criu mntns" - this protects from possible test fails in case host creates mounts in criu directory.
2) "zdtm/mnt_root_ext: don't allow propagation from test mntns to criu mntns" - this fixes race when mnt_root_ext creates mount which propagates into criu mntns creating children-overmount of the root mount source. Fixes: #1941

zdtm: fix race when propagations in root mount of criu mntns affected tests

---

criu/files-reg.c
test/zdtm/static/Makefile
test/zdtm/static/ghost_holes_large00.c
test/zdtm/static/ghost_holes_large01.c
test/zdtm/static/ghost_holes_large01.desc
test/zdtm/static/unlink_largefile.desc

CRIU checked the size of sparse ghosts with `st_size`, this shows the file length not the actual file size(disk size), so the check can't deal with a large sparse ghost file.
In this PR, I fixed this bug by replacing `st_size` with `st_blocks`, which shows the actual size of a file. Moreover,  I created a test with large sparse ghost file, it will break the previous check but not the fixed one.

[GSoC 2022] large ghost sparse file support 

---

MAINTAINERS

I've been contributing to CRIU for sometime and I'm hoping that my familiarity with the project would be sufficient to self-nominate as a maintainer. I would like to help with code reviews, submitting patches, implementing new features, and maintaining the project in general.

MAINTAINERS: Add Radostin (myself) to maintainers

---

scripts/ci/docker-test.sh
scripts/ci/podman-test.sh

In commits https://github.com/checkpoint-restore/criu/commit/046cad8 and https://github.com/checkpoint-restore/criu/commit/81a68ad the version of containerd installed by default in the GitHub CI virtual environment was replaced with the latest release from GitHub as a workaround to a bug in containerd.
This bug has been fixed sometime ago and the current default version of containerd (1.6.6) does not require this workaround. However, with the latest release, the containerd binaries uploaded on GitHub have been built for Ubuntu 22.04 (https://github.com/containerd/containerd/commit/6b2dc9a37). Our tests are still running on Ubuntu 20.04 and this results in the following error:
/usr/bin/containerd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by …

ci: fix docker test

---

criu/cr-check.c

The feature check for AppArmor stacking was introduced in commit 8723e3f998d1ec5f125e6600436a96f7ff9c1631. However, on systems that don't support AppArmour, this check always fails. As a result, `criu check --all` shows the following message:
> Looks good but some kernel features are missing which, depending on your process tree, may cause dump or restore failure.

cr-check: fix check for apparmor stacking

---

criu/cr-restore.c
criu/include/kerndat.h
criu/kerndat.c

Before this patch we assumed that CRIU is compiled against
the same GLibc as it runs with. But as we see from real
world examples like #1935 it's not always true.
The idea of this patch is to detect rseq configuration
for the main CRIU process and use it to unregister
rseq for all further child processes. It's correct,
because we restore pstree using clone*() syscalls,
don't use exec*() (!) syscalls, so rseq gets inherited
in the kernel and rseq configuration remains the same
for all children processes.
This will prevent issues like this:
https://github.com/checkpoint-restore/criu/issues/1935
Suggested-by: Florian Weimer <fweimer@redhat.com>
Signed-off-by: Alexander Mikhalitsyn <alexander.mikhalitsyn@virtuozzo.com>

cr-restore: rseq: dynamically handle *libc with rseq

---

.cirrus.yml

Mostly a copy-paste from CentOS 8 task, with a few differences:
- Use dnf instead of yum
- Enable crb instead of powertools
- Different way of installing EPEL
- No need to switch to python3 as this is the default
- `junit_xml` is now available as an rpm, no need to install via pip
- `flake8` is not (yet?) available, have to installed it via pip because of
https://bugzilla.redhat.com/show_bug.cgi?id=2070206

ci/cirrus: add CentOS Stream 9

---

criu/sk-unix.c
test/zdtm/lib/zdtmtst.h
test/zdtm/static/Makefile
test/zdtm/static/sk-unix-listen01.c
test/zdtm/static/sk-unix-listen02.c
test/zdtm/static/sk-unix-listen02.desc
test/zdtm/static/sk-unix-listen03.c
test/zdtm/static/sk-unix-listen03.desc
test/zdtm/static/sk-unix-listen04.c
test/zdtm/static/sk-unix-listen04.desc

Before this change, CRIU would just lose that data upon migration. So
it's better to fail migration in this case.
To reproduce the bug one can:
1. Create an AF_UNIX socket and call listen on it.
2. Create a second AF_UNIX socket and call connect to the first one.
3. Send the data to the second socket.
4. Migrate.
5. Call accept on the first socket and then read. There would be no data
available.
It should be even possible to close the second socket before migration.
This would cause accept to hang because CRIU totally misses a closed
in-flight socket.

criu: fail migration if data was sent to an in-flight socket

---

criu/include/linux/mount.h

A recent change in glibc introduced [`enum fsconfig_command`](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=7eae6a91e9b1670330c9f15730082c91c0b1d570) and as a result the compilation of criu fails with the following errors:
```
In file included from criu/pie/util.c:3:
/usr/include/sys/mount.h:240:6: error: redeclaration of 'enum fsconfig_command'
240 | enum fsconfig_command
|      ^~~~~~~~~~~~~~~~
In file included from /usr/include/sys/mount.h:32:
criu/include/linux/mount.h:11:6: note: originally defined here
11 | enum fsconfig_command {
|      ^~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:242:3: error: redeclaration of enumerator 'FSCONFIG_SET_FLAG'
242 |   FSCONFIG_SET_FLAG       = 0,    /* Set parameter, supplying no value */
|   ^~~~~~~~~~~~~~~~~
criu/include/linux/mount.h:12:9: …
```

ci: Fix build on Fedora Rawhide

---

criu/files-reg.c
scripts/criu-ns

These are (probable) fixes for two errors when using criu-ns:
1. When restoring first time via criu-ns (from criu-ns dump):
```
Error (criu/tty.c:689): tty: Failed to set group 40816 on 0: Inappropriate ioctl for device
```
2. When dumping second time via criu-ns:
```
(00.005678) Error (criu/files-reg.c:1710): Can't lookup mount=29 for fd=0 path=/dev/pts/20
```
Fixes: #1893

Criu ns tty fix

---

.github/workflows/lint.yml
Makefile
scripts/ci/apt-install
scripts/ci/asan.sh
scripts/ci/docker-test.sh
scripts/ci/podman-test.sh
scripts/ci/run-ci-tests.sh
scripts/protobuf-gen.sh
test/others/config-file/run.sh
test/others/crit/test.sh
test/others/criu-coredump/test.sh
test/others/libcriu/run.sh

1. Update shellcheck used in CI to the latest version (v0.7.2 -> v0.8.0).
2. Fix shellcheck warnings that were previously disabled (except for one).

Shellcheck followup

---

compel/arch/ppc64/src/lib/include/uapi/asm/sigframe.h
compel/arch/ppc64/src/lib/infect.c
compel/include/uapi/infect.h
compel/src/lib/infect.c
compel/test/Makefile
compel/test/infect/spy.c
compel/test/stack/.gitignore
compel/test/stack/Makefile
compel/test/stack/parasite.c
compel/test/stack/spy.c
compel/test/stack/victim.c
test/zdtm/transition/Makefile
test/zdtm/transition/stack.c

I've been seeing intermittent crashes on ppc64le, tracked back to incorrect parasite stack setup. The ppc64le ABI allows functions to write to their caller's stack frame, so we have to allocate a dummy frame before running parasite code on the stack, otherwise function prologues may write past the end of stack memory. The s390x ABI has the same behaviour, but the code there does the right thing. Fixed the ppc64le code in the same way.
I've added a simple test case (copied & modified an existing compel test) that checks that memory after the stack buffer is not modified after the parasite is set up. (It only detects modification, not cases where the same value is written.)
Looked around existing issues; turns out #1946 is the same problem, crashes when the stack ends on a page boundary and …

compel: Fix ppc64le memory corruption near stack

---

.cirrus.yml

python2-future, python2-junit_xml, python-flake8 and libbsd-devel are now provided from the EPEL package repository.

Fix CentOS 7 CI

---

.cirrus.yml
Documentation/criu.txt
criu/cgroup.c
criu/config.c
criu/cr-check.c
criu/cr-restore.c
criu/cr-service.c
criu/crtools.c
criu/fdstore.c
criu/files.c
criu/image.c
criu/include/cr_options.h
criu/include/crtools.h
criu/include/restorer.h
criu/include/util-caps.h
criu/include/util.h
criu/kerndat.c
criu/namespaces.c
criu/pie/restorer.c
criu/timens.c
criu/util.c
images/rpc.proto
lib/c/criu.c
lib/c/criu.h
scripts/ci/Makefile
scripts/ci/vagrant.sh
test/zdtm.py
test/zdtm/lib/test.c
test/zdtm_ct.c

We at the OpenJ9 and Open Liberty projects have been experimenting with CRIU to improve JVM and Java web application start-up times, primarily in container deployments.[^1] To that end we've been testing #1155 for a while now and having success and we want to help get it across the finish line.
---
With @adrianreber's agreement I've rebased the patches in #1155 and added 4 additional patches as follows:
Patches to add the `--unprivileged` option to `libcriu` and the RPC interface, and a fix to do the required `check_caps()` on the service worker path, equivalent to what's done on the tool path:
- 3807cc9cd non-root: Call check_caps() in service worker mode as well
- 8df76f09b non-root: Allow unprivileged flag to be set via libcriu
Patches to move some new code (that I believe requires …

Allow CRIU to be used as non-root (Take 2)

---

criu/cgroup.c

In Virtuozzo we've faced out-of-bound access when calling this function on short path string, which corrupted other memory and lead to segmentation fault. So it may be useful to have this comment in code to avoid such a missuse of this function in future.

cgroup: add a comment to restore_cgroup_prop about path argument requirements

---

criu/include/sysctl.h
criu/ipc_ns.c
criu/sysctl.c

Since commit https://github.com/torvalds/linux/commit/5563cabdde, user with enough capability can open IPC sysctl files and write to them. Therefore, we don't need to use usernsd process in the outside user namespace to help with that anymore. Furthermore, some later commits:
https://github.com/torvalds/linux/commit/1f5c135ee5, https://github.com/torvalds/linux/commit/0889f44e28 bind the IPC namespace to the opened file descriptor of IPC sysctl at the open() time, the changed value does not depend on the IPC namespace of write() time anymore. This breaks the current usernsd approach.
So, we prioritize opening/writing IPC sysctl files in the context of restored process directly without usernsd help. This approach succeeds in the newer kernel since the restored process has enough …

ipc_sysctl: Prioritize restoring IPC variables using non usernsd approach

---

scripts/ci/Makefile
scripts/ci/run-ci-tests.sh

A previous commit added a cgroup cpuset unmounting to scripts/ci/Makefile. We are sometimes running in a container without the necessary privileges to unmount certain cgroups.
This commit moves the cgroup unmounting to a place in run-ci-tests.sh which already requires privileged access and does not break unprivileged build-only CI runs.
CC: @minhbq-99

ci: move cgroup unmounting to run-ci-tests.sh

---

criu/kerndat.c

Some users on Raspberry Pi report that the kerndat checking for memfd_create(MFD_HUGETLB) support returns ENOSYS even when memfd_create syscall is available. We currently treat this error as unexpected and return error. This commit marks the memfd_create(MFD_HUGETLB) as unavailable when ENOSYS is returned.
Fixes: #1986

kerndat: Mark memfd_create(MFD_HUGETLB) unavailable when ENOSYS is returned

---

criu/cr-dump.c
criu/cr-restore.c
images/core.proto

Zombie tasks are dumped in dump_zombies() so it is redundant to handle them in dump_one_task().
Deprecate cg_set in task_core_entry as this field must be per thread now.

cgroup: Remove redundant code that handles zombie tasks

---

plugins/amdgpu/Makefile

This pull request adds a missing definition for `__nmk_dir` in the Makefile for the amdgpu plugin. This definition is required, for example, when building the `test_topology_remap` target:
make -C plugins/amdgpu/ test_topology_remap

amdgpu: define __nmk_dir if missing

---

criu/net.c
criu/util.c

While building on a machine that has a HOL clang compiler, I ran into warnings regarding the changed lines.  It appears this warning is on by default because of anticipated changes to the C standard.
Signed-off-by: Drew Wock <ajwock@gmail.com>

Fix warnings from -Wstrict-prototypes in clang 16.0.0

---

.github/workflows/lint.yml

The way ShellCheck is installed was changed in commit c056f99 to use v0.8.0 and remove some of the `"shellcheck disable=..."` annotations. Since then, Fedora 37 has been released and the ShellCheck package has been updated to v0.8.0.

ci/lint: install ShellCheck with dnf

---

scripts/build/Dockerfile.alpine

The python3 package in Alpine has recently been updated to install symbolic link for /usr/bin/python.
https://git.alpinelinux.org/aports/commit/main/python3?id=d91da210b1614eb75517d59b7f348fee01699f35
This causes the following error in CI:
Step 10/11 : RUN ln -s /usr/bin/python3 /usr/bin/python
---> Running in a5a94be9dc93
ln: failed to create symbolic link '/usr/bin/python': File exists
The command '/bin/sh -c ln -s /usr/bin/python3 /usr/bin/python' returned a non-zero code: 1

Fix CI tests on Alpine Linux

---

test/zdtm/static/stopped03.c
test/zdtm/static/stopped04.c
test/zdtm/transition/maps007.c

This patch fixes applies the changes required by clang-format v15.0.5 for `make indent`.

ci: fix make indent

---

criu/config.c
criu/files-reg.c
criu/include/cr_options.h
test/zdtm/static/Makefile
test/zdtm/static/ghost_multi_hole00.c
test/zdtm/static/ghost_multi_hole00.desc
test/zdtm/static/ghost_multi_hole01.c
test/zdtm/static/ghost_multi_hole01.desc

In order to reduce the frequency of using system call, I created a new algorithm
of copying chunk via fiemap.(copy_file_to_chunks_fiemap)
Also, I modified the sendfile-related inequality (e.g. from <= to =) to
avoid corresponding error.
Signed-off-by: Liang-Chun Chen <featherclc@gmail.com>

[GSoC 2022] Improve copy file algorithm in dump_ghost_file

---

criu/fdstore.c
criu/include/sockets.h
criu/pidfd-store.c
criu/sockets.c

Two fixes here related to running in unprivileged mode.
The first avoilds restoring `SO_MARK` on the service socket since we know the semantics of this socket and we know it doesn't need it.
The second changes how we use the `SO_*BUF*` options. As noted by @imachug[^1], checking if we have `CAP_NET_ADMIN` unfortunately doesn't tell us if we can really use these options. The easiest approach as suggested by @avagin is to simply try the `SO_*BUFFORCE` versions first and, if in unprivileged mode, fall back to the `SO_*BUF` ones on failure.
These two patches together allows users to avoid needing `CAP_NET_ADMIN` when doing unprivileged self-dump and restore, since the service socket is included in the dump and needs to be restored.
[^1]: …

non-root: Fix socket restore issues

---

scripts/build/Dockerfile.hotspot-alpine
scripts/build/Dockerfile.hotspot-ubuntu
scripts/build/Dockerfile.openj9-ubuntu
test/javaTests/pom.xml

TestNG is vulnerable to Path Traversal
Fixes https://github.com/checkpoint-restore/criu/security/dependabot/1.

test/javaTests: update org.testng:testng (Maven)

---

test/zdtm.py

After commit https://github.com/checkpoint-restore/criu/commit/0add1b6cdbedaaac93d48ea323beceb7328b69b2, the command `./zdtm.py list` fails with the following error.
if opts['rootless']:
~~~~^^^^^^^^^^^^
KeyError: 'rootless'

zdtm: fix 'zdtm.py list' command

---

include/common/arch/ppc64/asm/bitops.h
include/common/arch/s390/asm/bitops.h
include/common/arch/x86/asm/bitops.h
include/common/asm-generic/bitops.h

find_next_bit operates on a bit instead of byte positions/sizes.
Signed-off-by: Michal Clapinski <mclapinski@google.com>

asm: fix for_each_bit macro

---

criu/autofs.c

Fixes: 93dd984ca ("Run 'make indent' on all C files")

autofs: fix a frankenstein auto-created by clang-format

---

.clang-format
criu/tty.c
scripts/fetch-clang-format.sh

clang-format: add for_each_bit macros to ForEachMacros 
+
tty: fix codding-style around for_each_bit call
Wraping "{" to next line after for-each macros is wrong.

Clang format fix for each bit

---

.github/workflows/lint.yml
Makefile

Previousely "make indent" checked all files in criu source directory for codding style flaws. We have several problems with it:
- clang-format default format sometimes changes in new versions of the package and we need to reformat all our code base each time it happens
- on different systems we may have different versions of clang-format and on latest criu-dev "make indent" may be still unhappy on your system
- when we want to update clang-format rules ourselves we need to update all our code base each time
- sometimes clang-format rules are not fitting all our cases, (e.g.: an option IndentGotoLabels works nice for simple C code, but is a no go for assembler and C macros) and putting "clang-format off" everywhere is a mess
- sometimes we intentionally want to break clang-format rules …

clang-format: rework make indent to check specific commits

---

criu/pie/restorer.c

This kernel feature contained some bugs initially. Those logs are useful in identifing what the underlaying issue is and which kernel patch to backport.
Example logs after faking a failure:
```
[...]
(00.001826) pie: 56: prctl PR_SET_MM_MAP failed with 1
(00.001827) pie: 56:   .start_code = 0x402000
(00.001828) pie: 56:   .end_code = 0x404af1
(00.001829) pie: 56:   .start_data = 0x407df0
(00.001830) pie: 56:   .end_data = 0x4083e4
(00.001832) pie: 56:   .start_stack = 0x7ffe56abb870
(00.001833) pie: 56:   .start_brk = 0x768000
(00.001834) pie: 56:   .brk = 0x789000
(00.001835) pie: 56:   .arg_start = 0x7ffe56abd4ee
(00.001836) pie: 56:   .arg_end = 0x7ffe56abd534
(00.001837) pie: 56:   .env_start = 0x7ffe56abd534
(00.001838) pie: 56:   .env_end = 0x7ffe56abdff0
(00.001840) pie: 56: …
```

restorer: add logging on prctl PR_SET_MM_MAP failure

---

.github/workflows/codeql.yml

This is a replacement for #2015 which does not work correctly. This includes a couple of small changes to make it work.

ci: switch from lgtm to codeql

---

Makefile
compel/include/log.h
criu/fsnotify.c
criu/include/sk-inet.h
criu/kerndat.c
criu/sk-unix.c

As our pr_* functions are complex and can call different system calls
inside before actual printing (e.g. gettimeofday for timestamps) actual
errno at the time of printing may be changed.
Let's just use %s + strerror(errno) instead of %m with pr_* functions to
be explicit that errno to string transformation happens before calling
anything else.

Prohibit to use procent m in pr  functions

---

criu/Makefile.crtools
criu/apparmor.c
criu/cr-dump.c
criu/cr-restore.c
criu/cr-service.c
criu/crtools.c
criu/files-reg.c
criu/files.c
criu/include/setproctitle.h
criu/include/string.h
criu/log.c
criu/net.c
criu/proc_parse.c
criu/seize.c
criu/setproctitle.c
criu/string.c
criu/tun.c

string: define wrapers __setproctitle and __setproctitle_init to hide bsd headers
We see that libbsd redefines __has_include to be always true, which
breaks such checks for rseq. The idea behind this patch is to put all
uses of libbsd functions to separate c files and only export wrapper
functions for them.
Using __setproctitle and __setproctitle_init everywhere in existing
code:
git grep --files-with-matches "setproctitle" | xargs sed -i 's/setproctitle/__setproctitle/g'
git grep --files-with-matches "setproctitle_init" | xargs sed -i 's/setproctitle_init/__setproctitle_init/g'
Fixes: #2036
Suggested-by: Andrei Vagin <avagin@google.com>
string: define wrapers __strlcpy and __strlcat to hide bsd headers
We see that libbsd …

Hide bsd headers

---

criu/files-reg.c

This is a series of two simple changes fixing a typo and removing a `while` implemented with `goto`.

Trivial fixes (typo and code flow)

---

.clang-format
scripts/fetch-clang-format.sh

This is done to follow 'Linux kernel coding style', same change was added to .clang-format in linux kernel source recently https://github.com/torvalds/linux/commit/d7f6604341c74.

Dont indent goto labels

---

criu/proc_parse.c
criu/shmem.c
scripts/build/Dockerfile.alpine
scripts/ci/run-ci-tests.sh
scripts/ci/vagrant.sh

Patch originally written by @imachug to get httpd restored inside a container in unprivileged mode.
Fixes #2019.

Fix VMA handling for shmem maps

---

criu/cr-check.c
criu/include/kerndat.h
criu/kerndat.c
criu/sk-inet.c
images/sk-inet.proto
test/zdtm/static/Makefile
test/zdtm/static/sock_ip_opts00.c
test/zdtm/static/sock_ip_opts00.desc
test/zdtm/static/sock_ip_opts01.c
test/zdtm/static/sock_ip_opts01.desc

We see systemd-resolved relying on this option, and after migration this
option is lost and systemd-resolved stops serving dns requests.
The IP_PKTINFO socket option makes kernel add cmsg with destination
address to packets, see more how systemd-resolved uses it:
https://github.com/systemd/systemd/blob/00a60eaf5fcb3a0e415349aa649f2699550d26b0/src/resolve/resolved-manager.c#L826

 sk-inet: support of SOL_IP, IP_PKTINFO option

---

Documentation/criu.txt
criu/crtools.c

The `--ghost-fiemap` option was introduced with #1963. It enables an optimized algorithm based on fiemap ioctl that can reduce the number of syscalls used to checkpoint highly sparse ghost files.

Add documentation for --ghost-fiemap

---

Makefile

If we build tags for our repo:
```
[criu]$ make tags
GEN      tags
```
And then run codespell, we get an error:
```
[criu]$ codespell
./tags:3755: struc ==> struct
```
Let's exclude tags file from codespell search, this would add usability to `make lint`.

lint: exclude tags file from codespell

---

criu/cr-dump.c
criu/include/seize.h
criu/seize.c

When error happens on file dumping stage the only information about the task we dumping is its PID. For debug purpose show task's @comm early.
It proves useful when trying to understand which of dumped applications is "guilty" in brokern dump when pid is not there anymore.
Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>
--
This is a port of https://src.openvz.org/projects/OVZ/repos/criu/commits/487a62763
CC @cyrillos

dump: Show task comm early

---

lib/py/images/images.py
test/others/crit/test.sh

In Python 3 `b'' == ''` is `False`. This causes the `crit info` action to fail with the following error.
```
File "/usr/lib/python3.11/site-packages/crit-3.17-py3.11.egg/pycriu/images/images.py", line 178, in count
size, = struct.unpack('i', buf)
^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
```
Reported-by: Sankalp Acharya (@sankalp-12)

crit: fix info action

---

criu/seize.c

This addresses Andrei comments from
https://github.com/checkpoint-restore/criu/pull/2064
- Add comment about '\n' fixing
- Replace ret with more self explainting is_read
- Print warings if we failed to print comm for some reason

dump: improve error printing and readability of task_comm_info

---

test/zdtm/transition/epoll.c

Checking errno in case read succeeded is undefined behaviour.

zdtm/transition/epoll: don't rely on errno in case of zero return

---

criu/cr-restore.c

Fixes: 37b99ebe5 ("files: Do setup_newborn_fds() later")
It is a port of https://src.openvz.org/projects/OVZ/repos/criu/commits/12360ca98

restore: don't miss futex abort in restore_task_with_children

---

scripts/ci/podman-test.sh

This PR disables the checkpoint/restore of cgroups for the tests using Podman as a temporary workaround for https://github.com/checkpoint-restore/criu/issues/2091

ci: disable c/r of cgroups with podman

---

coredump/coredump.py
coredump/criu_coredump/coredump.py
test/others/criu-coredump/test.sh

This fixes errors with long command-lines:
```
File "/home/criu/coredump/criu_coredump/coredump.py", line 320, in _gen_prpsinfo
prpsinfo.pr_psargs = self._gen_cmdline(pid)
^^^^^^^^^^^^^^^^^^
ValueError: bytes too long (88, maximum length 80)
```
and gives a cleaner error (without a complete Python backtrace) if files are missing:
New message:
```
ERROR: Required file /usr/lib64/libcrypto.so.3.0.1 not found.
Exiting
```
Old message:
```
File "/home/criu/coredump/criu_coredump/coredump.py", line 693, in _gen_mem_chunk
f = open(fname, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/libcrypto.so.3.0.1'
```
Test has also been adapted verify that long command-lines do not break the coredump script.

coredump: two small fixes

---

criu/pie/restorer.c

Nothing serious since OS will close it anyway but still to be precise.
It is a port of https://src.openvz.org/projects/OVZ/repos/criu/commits/459dfa2ca
CC: @cyrillos

pie/restorer: Fix fd leaking on error path

---

criu/arch/x86/crtools.c

Just rebasing on top of `criu-dev`.
All credit to Dmitry @0x7f454c46 for this incredible investigation and fix. (-:
```
Setting all supported by CPU features in xstate_bv may bring it into dirty-upper-state as documented in specs, resulting in lower performance. Let's not do this and set only those have been used by dumpee.
P.S.
Off course it has to be a one-liner!
Fixes: #1171
```
Fixes: #1171

x86/xsave: Set only used XFEATURE_* in xstate_bv

---

Makefile

The patch is similar to what has been done in linux kernel, as this warning effectively prevents us from adding list elements to local list head. See https://github.com/torvalds/linux/commit/49beadbd47c2
Note: it fixes CI.

make: disable '-Wdangling-pointer' warning with gcc 12

---

criu/net.c

Fixes: e1c4871 ("net: add nftables c/r")

net: fail restore if nftables isn't supported but image is present

---

criu/cgroup.c
criu/cr-dump.c
criu/cr-restore.c
images/cgroup.proto
images/core.proto

The newly added fields in image protobuf are currently marked as required. This causes backward compatibility problem when using the newer CRIU version to restore an dumped image from older version which doesn't have these fields. This commit marks these new fields optional and reworks the logic:
- Fallback to cg_set in task_core when it is not in thread_core
- Skip fixing up threaded cgroup controllers if there is no information in dumped image

cgroup-v2: make new fields in image protobuf optional

---

criu/mount.c

When we collect external mount namespace we don't want to dump mounts in it, so lets remove this flag. This way we can e.g. use for_dump in ->parse() callbacks to separate in-container mounts from others.
This only affects rare case of `--ext-mount-map auto` but to be absolutely correct let's fix it anyway.

mount: do collect_mntinfo of external mount namespace with no for_dump

---

test/jenkins/criu-fault.sh
test/others/mem-snap/run-predump-2.sh
test/others/mem-snap/run-predump.sh
test/others/mem-snap/run-snap-auto-dedup.sh
test/others/mem-snap/run-snap-dedup-on-restore.sh
test/others/mem-snap/run-snap-dedup.sh
test/others/mem-snap/run-snap-maps04.sh
test/others/mem-snap/run-snap.sh
test/others/mounts/mounts.sh
test/others/mounts/run.sh
test/others/ns_ext/run.sh
test/others/ns_ext/run_pidns.sh
test/others/unix-callback/run.sh

This PR optimizes shell code as reading a single file as input using a 'cat' command to a program is considered to be a Useless Use of Cat [[UUOC](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat)]. It's more efficient to simply use redirection. Fixes the issue https://github.com/checkpoint-restore/criu/issues/330.

Optimized shell code with <'s (instead of cat + |)

---

scripts/build/Dockerfile.archlinux

When installing packages within Archlinux container, pacman fails with the following errors:
```
(3/7) Creating temporary files...
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:23: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:25: Failed to replace specifiers in '/run/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:26: Failed to replace specifiers in '/run/log/journal/%m/*.journal*': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:29: Failed to replace specifiers in '/var/log/journal/%m': No such file or directory
/usr/lib/tmpfiles.d/systemd.conf:30: Failed to replace …
```

ci/archlinux: initialize machine ID

---

criu/filesystems.c

Currently we only allow external fuse mount itself, let's allow bindmount for it too. Other mount code is ready for this change and will be able to bindmount it from corresponding external mount.
This is a missing hunk from initial mount-v2 implementation in Virtuozzo criu:
https://src.openvz.org/projects/OVZ/repos/criu/commits/1105e1e3f
note for myself: don't have a test for it, but it can be a good initial GSOC task to add it for detached mount support project

mount: allow bindmounts for external fuse mounts

---

test/zdtm/lib/mountinfo.h
test/zdtm/static/mount_complex_sharing.c

With this macro we can easily declare struct mntns_zdtm variables with all lists properly initiallized. Let's use it in mount_complex_sharing as without it we can have segfault on error path when accessing uninitialized list pointers.

zdtm: add MNTNS_ZDTM macro to fix initialization

---

criu/sk-unix.c

In Virtuozzo tests we have seen uninformative errors:
(26.575039) 151187 fdinfo 6: pos: 0 flags: 2/0
(26.575076) sockets: Searching for socket 0x346d1 family 1
(666.230281 ----------------------------------------
(666.230586 Error (criu/cr-dump.c:1850): Dump files (pid: 151187) failed with -1
So let's add some error messages to this stack.
This is a port from Virtuozzo criu:
https://src.openvz.org/projects/OVZ/repos/criu/commits/cca9aa8dc

sk-unix: add some missed error printing

---

test/zdtm/lib/fs.c
test/zdtm/lib/unix.c

Fix cwd freeing on error path in get_cwd_check_perm and on non-error-path in unix_fill_sock_name.
This is a port of Virtuozzo patch:
https://src.openvz.org/projects/OVZ/repos/criu/commits/a7916411a
CC: @uravas

zdtm/lib: fix cwd path freeing

---

.github/workflows/alpine-test.yml
.github/workflows/archlinux-test.yml
.github/workflows/codeql.yml
.github/workflows/compat-test.yml
.github/workflows/cross-compile.yml
.github/workflows/docker-test.yml
.github/workflows/fedora-asan-test.yml
.github/workflows/fedora-rawhide-test.yml
.github/workflows/gcov-test.yml
.github/workflows/java-test.yml
.github/workflows/lint.yml
.github/workflows/podman-test.yml
.github/workflows/stream-test.yml
.github/workflows/x86-64-clang-test.yml
.github/workflows/x86-64-gcc-test.yml

This pull request adds concurrency groups to the CI workflows to automatically cancel any in-progress workflows when a pull request has been updated. A [`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) group allows to ensure that a single job or workflow will run at a time. For example, when a pull request is updated with a force-push, the GiHub CI workflows currently in-progress will be automatically cancelled, and the CI would run only with the updated commits.

ci: cancel preceding workflows run

---

criu/cr-dump.c
criu/parasite-syscall.c
test/zdtm/transition/Makefile
test/zdtm/transition/rseq01.c

Previously fixup was done before threads' registers were dumped so it
didn't actually work. This commit splits rseq fixup into thread leader
fixup and other threads fixup and applies them after the entities are
seized.

cr-dump: properly apply rseq fixup for all threads

---

criu/sk-netlink.c

During the restore process, netlink fd uses the flags in the NetlinkSkEntry structure to restore the file state, but during the dump process, the flags values is not saved to the structure.
Signed-off-by: zhoujie zhoujie133@huawei.com
Signed-off-by: hejingxian hejingxian@huawei.com

netlink: fix netlink fd flags dump/restore failed

---

criu/proc_parse.c
test/zdtm/lib/fs.c
test/zdtm/static/apparmor.c
test/zdtm/static/apparmor_stacking.c
test/zdtm/static/cgroup01.c
test/zdtm/static/cgroup02.c
test/zdtm/static/change_mnt_context.c
test/zdtm/static/file_locks01.c
test/zdtm/static/file_locks02.c
test/zdtm/static/file_locks03.c
test/zdtm/static/file_locks04.c
test/zdtm/static/netns-dev.c
test/zdtm/static/ofd_file_locks.c

Fixes: #2121
limit the field width of 'scanf'

limit the field width of 'scanf'

---

criu/log.c

Previously when tv_sec>=100, the line would look like this:
(269.189615 Error [...]
Now the last char is overwritten with ')'.

log: fix timestamp logging when tv_sec>=100

---

criu/cr-check.c

We do kerndat_has_nspid in kerndat_init already and save result to kerndat cache, we don't need to recheck it each time.

cr-check: remove excess kerndat_has_nspid from check_ns_pid

---

criu/page-pipe.c

The pipe_size type is unsigned int, when the fcntl call fails and 
return -1, it will cause a negative rollover problem.
Signed-off-by: zhoujie <zhoujie133@huawei.com>

dump: increase fcntl call failure judgment

---

compel/arch/x86/src/lib/include/uapi/asm/fpu.h

Newer Intel CPUs (Sapphire Rapids) have a much larger xsave area than before. Looking at older CPUs I see 2440 bytes.
```
...
bytes required by XSAVE/XRSTOR area     = 0x00000988 (2440)
```
On newer CPUs (Sapphire Rapids) it grows to 11008 bytes.
```
...
bytes required by XSAVE/XRSTOR area     = 0x00002b00 (11008)
```
This increases the xsave area from one page to four pages.
Without this patch the fpu03 test fails, with this patch it works again.

compel: support XSAVE on newer Intel CPUs

---

scripts/criu-ns

Using the fact that we know criu_pid and criu is a parent of restored process we can create pidfile with pid on caller pidns level.
We need to move mount namespace creation to child so that criu-ns can see caller pidns proc.
This should help with adding the test for repeated criu-ns c/r. See https://github.com/checkpoint-restore/criu/pull/2114#issuecomment-1517590581

criu-ns: make --pidfile option show pid in caller pidns

---

lib/c/criu.c
lib/c/criu.h

crun wants to set empty_ns and this interface is missing from the library. This adds it to libcriu.
See https://github.com/containers/crun/issues/1210

lib/c: add empty_ns interfaces to libcriu

---

.cirrus.yml
Makefile
scripts/ci/run-ci-tests.sh
scripts/criu-ns
test/Makefile
test/others/criu-ns/Makefile
test/others/criu-ns/run.py

These changes add test implementations for criu-ns script.
Fixes: #1909

criu-ns: Add tests for criu-ns script

---

criu/cgroup.c
criu/cr-restore.c
criu/include/cgroup.h

This does cgroup namespace creation separately from joining task cgroups. This makes the code more logical, because creating cgroup namespace also involves joining cgroups but these cgroups can be different to task's cgroups as they are cgroup namespace roots (cgns_prefix), and mixing all of them together may lead to misunderstanding.
Another positive thing is that we consolidate !item->parent checks in one place in restore_task_with_children.
This is a backport of:
https://src.openvz.org/projects/OVZ/repos/criu/commits/4ab1a32cf
https://src.openvz.org/projects/OVZ/repos/criu/commits/fafbe61a6
Signed-off-by: Valeriy Vdovin <valeriy.vdovin@virtuozzo.com>

cgroup/restore: split prepare_task_cgroup code into two separate functions

---

criu/cgroup.c
criu/memfd.c

Small changes to account for differences in earlier kernel support for cgroups and memfds.

Fixes for old (4.15) kernels

---

criu/cr-restore.c
criu/include/restorer.h
criu/include/rst_info.h
criu/kerndat.c
criu/mem.c
criu/pie/restorer.c
test/zdtm/static/thp_disable.c

Fix and test restoring of prctl(THP_DISABLE).

Fix migrating prctl(THP_DISABLE)

---

compel/test/fdspy/spy.c

Found this bug when working on adding riscv64 support to compel #1702 :) Specifically, the bug appeared when the `p_err` pipe became broken after resuming, causing `check_pipe_ends()` to hit either these branches:
```c
if (write(wfd, "1", 2) != 2) {
fprintf(stderr, "write to pipe failed\n");
return -1;
}
if (read(rfd, aux, sizeof(aux)) != sizeof(aux)) {
fprintf(stderr, "read from pipe failed\n");
return -1;
}
```
The -1 return value was not correctly handled in the final check:
```c
pass = check_pipe_ends(stolen_fd, p_err[0]);
if (pass)
printf("All OK\n");
else
printf("Something went WRONG\n");
```
This pull request modified the condition to `pass == 1`, ensuring that "All OK" is printed only when `check_pipe_ends()` returns 1 (indicating a successful case), and any other value will …

compel/test: Fix success condition check in fdspy

---

criu/kerndat.c
test/zdtm/static/thp_disable.c

The `fail()` macro provides a new line character at the end of the message. This patch fixes the following lint check that currently fails in CI:
```
$ git --no-pager grep -E '^\s*\<(pr_perror|fail)\>.*\\n"'
test/zdtm/static/thp_disable.c:         fail("prctl(GET_THP_DISABLE) returned unexpected value: %d != 1\n", ret);
test/zdtm/static/thp_disable.c:         fail("Flags changed %lx -> %lx\n", orig_flags, new_flags);
test/zdtm/static/thp_disable.c:         fail("Madvs changed %lx -> %lx\n", orig_madv, new_madv);
test/zdtm/static/thp_disable.c:         fail("post-migration prctl(GET_THP_DISABLE) returned unexpected value: %d != 1\n", ret);
test/zdtm/static/thp_disable.c:         fail("Flags changed %lx -> %lx\n", orig_flags, new_flags);
test/zdtm/static/thp_disable.c:         fail("Madvs …
```

test/thp_disable: fix lint

---

criu/pipes.c

A trivial fix for error path leaking pipe fds.

pipes: Plug pipe fd leak in "Unable to set a pipe size" error case.

---

criu/cr-check.c
criu/kerndat.c

Try IPv6 if IPv4 sockets are not supported.

Make socket feature probing work on IPv6-only host.

---

criu/action-scripts.c
scripts/ci/docker-test.sh
scripts/ci/podman-test.sh

Container runtimes commonly use CRIU with RPC. However, this prevents the use of action-scripts set in a configuration file due to the explicit scripts mode introduced with commit ac78f13bdfaee260dd4234f054bf4c5d2a373783. This pull request enables container checkpoint/restore with action-scripts specified via configuration file.

action-scripts: allow shell scripts in rpc mode

---

Documentation/criu.txt
criu/action-scripts.c
criu/cr-dump.c
criu/cr-service.c
criu/include/action-scripts.h
images/rpc.proto

A set of independent features allowing more options to be controlled via RPC.
The series needs to be applied in sequence to limit conflict resolution due to RPC fields inserted.

RPC control extensions

---

Makefile
criu/include/log.h
criu/include/net.h
criu/kerndat.c
criu/util.c

If not dumping netns nor connections, nsid support is not used. Don't fail the run as if the support is needed, the dumping process will fail later.

kerndat: Don't fail on NETLINK/nsid support missing.

---

criu/util.c
test/zdtm_ct.c

The first patch improves on run-id generation to make it guaranteed to be unique on a running machine.
Second removes wrapping tests in an empty netns that was working around the lack of run-id uniqueness.

Guarantee run-id uniqueness

---

README.md

Instead of opening the image directly, the commit refactors the asciinema image embedded link to redirect users to the corresponding video.
Signed-off-by: Abhishek Guleri <abhishekguleri24@gmail.com>

readme: refactor asciinema link for video playback

---

test/zdtm/static/seccomp_filter_inheritance.c

`NR_fstat` is a deprecated syscall, usually use `NR_statx` instead. `NR_statx` is supported since linux 4.10. https://github.com/torvalds/linux/commit/a528d35e8bfcc521d7cb70aaf03e1bd296c8493f

test: replace NR_fstat with NR_statx

---

criu/include/sk-inet.h

The changes in this series are mostly independent and could be applied individually. If there are change requests I'll shuffle relevant commits to the back when addressing them.

A set of assorted fixes in logging and error propagation.

---

criu/apparmor.c

This makes the apparmor replace file path on riscv64 (#2234) zdtm/static/apparmor_stacking appear as `/sys/kernel/security/apparmor/policy/namespaces/criu_stacking_test/.replac`, where the final e is missing and leads to an error on `open()`. Although here `sizeof(path) - offset - my_offset` should be automatically converted to a quite large unsigned int, and the return value is still 9. Maybe it's due to different glibc implementation? 🤔
As paths are always declared as `char path[PATH_MAX]` when calling this function, I think it's okay to directly use `PATH_MAX` rather than introducing a new argument like size?

apparmor: fix incorrect usage of sizeof on char ptr

---

criu/include/util.h
criu/page-xfer.c
criu/util.c

Move tcp_cork() and tcp_nodelay() to the only user: page-xfer.c. While at it, fix error messages (as they do not refer to restoring the sockopt values) and demote them as they are not fatal to the page transfer.

page-xfer: Pull tcp_cork,nodelay().

---

criu/irmap.c

Make the scan use the order of paths that came from the user.
This assumes that the order actually matters and makes it easier to construct the list as to speed up inotify-using binaries.

irmap: scan user-provided paths in order

---

plugins/amdgpu/amdgpu_plugin.c

The log prefix `"amdgpu_plugin:"` is defined with `LOG_PREFIX` in `amdgpu_plugin.c`.  However, the prefix is also included in each log message. As a result it appears duplicated in the log messages:
```
(00.044324) amdgpu_plugin: amdgpu_plugin: devices:1 bos:58 objects:148 priv_data:45696
(00.045376) amdgpu_plugin: amdgpu_plugin: Thread[0x5589] started
(00.167172) amdgpu_plugin: amdgpu_plugin: img_path = amdgpu-kfd-62.img
(00.083739) amdgpu_plugin: amdgpu_plugin : amdgpu_plugin_dump_file() called for fd = 235
```

amdgpu_plugin: remove duplicated log prefix

---

coredump/criu_coredump/coredump.py
lib/py/images/pb2dict.py

`VMA_AREA_MEMFD` was introduced with commit 29a1a88bcebaf9d83591077d2bec424da82c0e71. This pull request extends the status map used in CRIT and coredump with the value of this constant to recognise it.
Before:
```
sudo crit show dump/zdtm/static/maps01/56/1/mm-57.img
...
{
"start": "0x7f224b4d4000",
"end": "0x7f224b4d5000",
"pgoff": 0,
"shmid": 6,
"prot": "PROT_READ | PROT_WRITE",
"flags": "MAP_SHARED",
"status": "VMA_AREA_REGULAR | VMA_FILE_SHARED | 0x4000",
"fd": -1,
"fdflags": "0x2"
},
```
After:
```
sudo crit show dump/zdtm/static/maps01/56/1/mm-57.img
...
{
"start": "0x7f224b4d4000",
"end": "0x7f224b4d5000",
"pgoff": 0,
"shmid": 6,
"prot": "PROT_READ | PROT_WRITE",
"flags": "MAP_SHARED",
"status": "VMA_AREA_REGULAR | VMA_FILE_SHARED | VMA_AREA_MEMFD",
"fd": -1,
"fdflags": "0x2"
}, …
```

lib/py: add VMA_AREA_MEMFD constant

---

.github/workflows/manage-labels.yml

Labels are removed when new comments are posted.

github: auto-remove `changes requested` and `awaiting reply` labels

---

criu/files-reg.c
criu/memfd.c

There is only one user of memfd_open() outside of memfd.c: open_filemap(). It is restoring a file-backed mapping and doesn't need to F_SETOWN nor update the fd's position.
An optimization / cleanup.

memfd: make memfd_open() skip fd attributes not needed for vma mapping

---

scripts/ci/loongarch64-qemu-test.sh

Otherwise tests fail by timeout.

ci/loongarch64: compile tests before running zdtm.py

---

.github/workflows/lint.yml
CONTRIBUTING.md
Makefile
scripts/github-indent-warnings.py

There are multiple cases where good human readable code block is
converted to an unreadable mess by clang-format, so we don't want to
rely on clang-format completely. Also there is no way, as far as I can
see, to make clang-format only fix what we want it to fix without
breaking something.
So let's just display hints inline where clang-format is unhappy. When
reviewer sees such a warning it's a good sign that something is broken
in codding style around this warning.

Lint add warnings instead of check failure

---

Documentation/criu-amdgpu-plugin.txt
plugins/amdgpu/amdgpu_plugin.c

The amdgpu plugin would create a memory buffer at the size of the largest VRAM bo (buffer object). On some systems, VRAM size exceeds RAM size, so the largest bo might be larger than the available memory.
Add an environment variable KFD_MAX_BUFFER_SIZE, which caps the size of this buffer. By default, it is set to 0, and has no effect. When active, any bo larger than its value will be saved to/restored from file in multiple passes.

criu/plugin: Add environment variable to cap size of buffers.

---

compel/arch/ppc64/src/lib/infect.c

Power ISA 3.0 added a new syscall instruction. Kernel 5.9 added corresponding support.
https://github.com/torvalds/linux/commit/912237ea166428edcbf3c137adf12cb987c477f2
https://github.com/torvalds/linux/commit/4e0e45b07d790253643ee05300784ab2156e2d5e
https://github.com/torvalds/linux/commit/7fa95f9adaee7e5cbb195d3359741120829e488b
https://github.com/torvalds/linux/commit/5665bc35c1ed917ac8fd06cb651317bb47a65b10
Add CRIU support to recognize the new instruction and kernel ABI changes to properly dump and restore threads executing in syscalls. Without this change threads executing in syscalls using the scv instruction will not be restored to re-execute the syscall, they will be restored to execute the following instruction and will return unexpected error codes (ERESTARTSYS, etc) to user …

compel: Add support for ppc64le scv syscalls

---

crit/setup.py
lib/py/.gitignore
lib/py/Makefile
lib/py/__init__.py
lib/py/cli.py
test/others/crit/test.sh

This pull request implements `--version` for `crit`.
```
$ crit --version
3.17
```

crit: add --version option

---

scripts/ci/Makefile
scripts/ci/asan.sh

They break it with each kernel rebase. More details are here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1857257
Last time, it was fixed a few month ago and it has been broken again in 5.15.0-1046-azure.

ci: stop testing ubuntu overlayfs

---

compel/plugins/std/infect.c
criu/pie/restorer.c
include/common/arch/aarch64/asm/page.h
include/common/arch/loongarch64/asm/page.h
include/common/arch/mips/asm/page.h
include/common/arch/ppc64/asm/page.h

The page_size() returns unsigned int value that is after "bitwise not"
is promoted to unsigned long (msg->arg.pagefault.address) value. Sinc
e the value is unsigned promotion is done with 0 MSB that results in
lost of MSB pagefault address bits. Cast page_size to unsigned long
first to avoid such situation.

uffd: Fix page fault address

---

criu/include/vma.h

Currently most of the times we don't have problems with VVAR segment and
lazy restore because when VDSO is parked there is an munmap call that
calls UFFDIO_UNREGISTER on the destination address.
But we don't want to enable userfaultfd for VDSO and VVAR at the first
place.

vma: Add !VVAR condition to vma_entry_can_be_lazy

---

.cirrus.yml
plugins/amdgpu/amdgpu_plugin.c
plugins/amdgpu/kfd_ioctl.h
scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.archlinux
scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/run-ci-tests.sh

This pull request adds the `libdrm-dev` package to the list of CRIU dependencies installed in CI to build CRIU with amdgpu plugin.

ci: enable build with amdgpu plugin

---

.clang-format
scripts/fetch-clang-format.sh

The "ColumnLimit: 120" is not only allowing lines to be longer than 80 characters but it also forces line wrapping at 120 characters. If total expression length is more than 120 characters, clang-format will try to wrap it as close to 120 as it can, it would not even allow to wrap at 80 characters if we really want it. But as we all know 80 characters is Linux kernel coding style default and as far as our coding style is based on it it is really strange to prohibit wrapping lines at 80 characters...

clang-format: disable column limit constraint

---

criu/pie/restorer.c
include/common/compiler.h

GCC's lto source:
```
> To avoid this problem the compiler must assume that it sees the
> whole program when doing link-time optimization.  Strictly
> speaking, the whole program is rarely visible even at link-time.
> Standard system libraries are usually linked dynamically or not
> provided with the link-time information.  In GCC, the whole
> program option (@option{-fwhole-program}) asserts that every
> function and variable defined in the current compilation
> unit is static, except for function @code{main} (note: at
> link time, the current unit is the union of all objects compiled
> with LTO).  Since some functions and variables need to
> be referenced externally, for example by another DSO or from an
> assembler file, GCC also provides the function and variable
> attribute …
```

pie: Mark __export_*() functions as externally_visible

---

criu/util.c

fork_and_ptrace_attach has to fork a child with CLONE_UNTRACED, so that strace doesn't trace it.

util: allow to run criu under strace

---

criu/net.c
criu/tun.c

read_ns_sys_file() can return an error, but we are trying to parse a buffer before checking a return code.
CID 417395 (#3 of 3): String not null terminated (STRING_NULL)
2. string_null: Passing unterminated string buf to strtol, which expects a null-terminated string.

tun: don't parse buffers that have not been filled with data

---

criu/files-reg.c
test/zdtm/lib/lock.h
test/zdtm/static/Makefile
test/zdtm/static/fd_offset.c

https://github.com/checkpoint-restore/criu/commit/9191f8728d6224e3c108063128131c8f219bdd4f ("criu/files-reg.c: add build-id validation functionality") added a feature to verify build-id of ELF files. Unfortunately it also broke the offset migration of such files due to a `read` after `lseek`. This PR fixes that.

Fix migration of fds to ELF files

---

test/zdtm/static/cgroup_ifpriomap.checkskip

This series contains a mostly-independent patches that improve test debuggability and make running the tests easier to parallelize.

ZDTM test assorted improvements

---

Makefile
test/zdtm/Makefile.inc
test/zdtm/lib/Makefile

Do not use $(USERCFLAGS) for anything other than what the user provide.
If $(USERCFLAGS) is provided by the user, then the make command will be unable to add machine specific options (used for ARM) resulting in build failures.
Instead, introduce $(ARCHCFLAGS) for such flags.

Makefile: introduce ARCHCFLAGS for arch specific cflags

---

compel/arch/arm/plugins/std/syscalls/syscall.def

In the compel/arch/arm/plugins/std/syscalls/syscall.def, the syscall number of bind on ARM64 should be 200 instead of 235
Referring to [this](https://gpages.juszkiewicz.com.pl/syscalls-table/syscalls.html)

compel: correct the syscall number of bind on ARM64

---

scripts/ci/vagrant.sh
test/jenkins/criu-fault.sh

The rawhide netlink errors are fixed with a newer kernel than the default 6.2 available in Fedora 38.

ci: fix rawhide netlink error

---

Makefile

WARNINGS variable should be amended, not redefined. We still need, e.g.,  `-Wno-dangling-pointer` to build criu on loongarch64 with gcc13.

Makefile: Use common warnings settings for loongarch64

---

scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/run-ci-tests.sh
scripts/ci/vagrant.sh

Newer versions of 'tail' rely on inotify and after a restore 'tail' is unhappy with the state of inotify and just stops.
This replaces 'tail' with a minimal test in C which just keeps a file open to still be able to test how CRIU reacts if the file mode has changed.
The skip-file-rwx-check test sometimes fails if `kill` is slower than `tail` ending itself.

ci: do not use 'tail' for skip-file-rwx-check test

---

.gitignore

In commit bbc2f133 was introduced a mechanism to auto-generate the files: sys-exec-tbl*.c, syscalls*.S, syscall-codes*.h, and syscall*.h. This commit also updated the gitignore rules to ignore auto-generated files. However, after commit 19fadee9, the path for these files has changed and the patterns specified in gitignore are no longer needed.
Reported-by: @felicitia

gitignore: remove historical left-over files

---

Makefile
scripts/build/Dockerfile.alpine
test/zdtm/Makefile.inc

Starting with the musl v1.2.4~69, _GNU_SOURCE doesn't set _LARGEFILE64_SOURCE.

make: fix compilation on alpine

---

criu/irmap.c

Hardcoding irmap hint for: `/usr/share/dbus-1/services`
Fixes issue described at: https://github.com/checkpoint-restore/criu/issues/77#issuecomment-1257183193
Uses approach as in this commit: https://github.com/checkpoint-restore/criu/commit/7f44f1dbf9935582a21e8b1f24a5b4396f2c3795
Tested locally and worked ok, checkpoint was successfully created.
Signed-off-by: Robert Ayrapetyan <robert.ayrapetyan@gmail.com>

irmap: hardcode some more interesting paths

---

criu/include/criu-log.h

This pull request removes a leftover declaration for `log_closedir()`. This function has been removed in commit dc80d6f125e1e919363a0b8f938b8679ff0dbc2b.

criu-log: remove unused declaration

---

criu/net.c

To improve readability, this pull request changes the return type of `iptables_has_criu_jump_target()` to a boolean, where `true` indicates that iptables has CRIU jump target and `false` indicates otherwise.
Suggested-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

net: return bool with iptable_has_criu_jump_target

---

plugins/amdgpu/amdgpu_plugin.c

During the late stages of restore, each process being resumed gets an ioctl call to KFD_CRIU_OP_RESUME. If the process has no kfd process info, this call with fail with -ESRCH. This is normal behaviour, so we shouldn't print an error message for it.

plugin/amdgpu: Don't print error for "No such process" during resume

---

plugins/amdgpu/amdgpu_plugin.c

We already don't treat it as error in the plugin itself, but after returning -1 from RESUME_DEVICES_LATE hook we print debug message in criu about failed plugin, let's return 0 instead.
While on it let's replace ret to exit_code.
Fixes: a9cbdad76 ("plugin/amdgpu: Don't print error for "No such process" during resume")

plugin/amdgpu: Also don't print 'plugin failed' in criu

---

plugins/amdgpu/Makefile
plugins/amdgpu/amdgpu_plugin.c
plugins/amdgpu/amdgpu_plugin_drm.c
plugins/amdgpu/amdgpu_plugin_drm.h
plugins/amdgpu/amdgpu_plugin_topology.c
plugins/amdgpu/amdgpu_plugin_topology.h
plugins/amdgpu/amdgpu_plugin_util.c
plugins/amdgpu/amdgpu_plugin_util.h
plugins/amdgpu/criu-amdgpu.proto

Refactor criu plugin baseline v2

---

criu/sk-inet.c
images/sk-inet.proto
test/zdtm/static/sock_ip_opts00.c

Adding IP_TTL socket option while restoring

---

criu/sk-inet.c

Commit [1] introduced codding-style breackage, let's fix it.
Fixes: 66cab1f49 ("sk-inet: Added IP_TTL socket option") [1]

sk-inet: fix codding style in restore_ip_opts

---

criu/kerndat.c

The [commit](https://github.com/torvalds/linux/commit/e6a9a2cbc13bf) introducing `PAGE_IS_SOFT_DIRTY` has not been merged in kernel v6.7.x, and as a result, CRIU fails with the following error:
```
Error (criu/pagemap-cache.c:199): pagemap-cache: PAGEMAP_SCAN: Invalid argument'
Error (criu/pagemap-cache.c:225): pagemap-cache: Failed to fill cache for 63 (400000-402000)'
```
This patch updates `check_pagemap()` in kerndat to also check if `PAGE_IS_SOFT_DIRTY` is supported.
Fixes: #2334

kerndat: check support for PAGE_IS_SOFT_DIRTY

---

.cirrus.yml
.github/workflows/lint.yml
CONTRIBUTING.md
Makefile
lib/pycriu/images/pb2dict.py
scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.archlinux
scripts/build/Dockerfile.centos8
scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/run-ci-tests.sh
scripts/ci/vagrant.sh
scripts/criu-ns
scripts/ruff.toml

This pull request is rebased on https://github.com/checkpoint-restore/criu/pull/2333 and https://github.com/checkpoint-restore/criu/pull/2345.
[Ruff](https://github.com/astral-sh/ruff) is a Python linter written in Rust, designed to replace flake8. It is significantly faster and actively maintained.

make: replace flake8 with ruff

---

.github/workflows/docker-test.yml
scripts/ci/docker-test.sh

Upgrade to 22.04 base image and skip pinning docker to a certain version.

ci: try to fix broken docker test

---

criu/mem.c

A memory interval is a half-open interval, so the condition when pr->pe->vaddr == vma->e->end should not be interpreted as an intersection and should cause vma to be marked with VMA_NO_PROT_WRITE.
Fixes: #2364

mem: fix some VMAs being incorrectly mapped wtih PROT_WRITE

---

criu/cr-dump.c
criu/cr-restore.c
test/zdtm/static/sched_policy00.c

This pull request extends CRIU with checkpoint/restore support for the reset-on-fork scheduling flag ([`SCHED_RESET_ON_FORK`](https://lwn.net/Articles/335203/)). When this flag is set, the following rules apply for subsequently created children:
- If the calling thread has a scheduling policy of `SCHED_FIFO` or `SCHED_RR`, the policy is reset to `SCHED_OTHER` in child processes.
- If the calling process has a negative nice value, the nice value is reset to zero in child processes.
(See `man 7 sched`)
Fixes: #2359

Add support for reset-on-fork scheduling flag

---

criu/include/timer.h

Currently we have tabs + spaces on the wrapped line but the wrapped part is not alligned to the opening bracket.
Fixes: bbe26d1b7 ("timer: fix allignment in function definition")

timer: fix wrapping allignment in function declaration

---

Makefile.config

1. Tell which RPMs or DEBs are required in all cases.
2. Use `$(info ...)` everywhere.
3. Drop extra nested $(info), instead use (a document) a simpler kludge.
4. Simplify and unify the language, add missing periods.
Before:
```
Note: Building without setproctitle() and strlcpy() support.
To enable these features, please install libbsd-devel (RPM) / libbsd-dev (DEB).
Note: Building criu without amdgpu_plugin.
Note: libdrm and libdrm_amdgpu are required to build amdgpu_plugin.
Makefile.config:53: Warn: you have no libnftables installed
Makefile.config:54: Warn: Building without nftables support
```
After:
```
Note: Building without setproctitle() and strlcpy() support.
Install libbsd-devel (RPM) / libbsd-dev (DEB) to fix.
Note: Building without amdgpu_plugin.
Install libdrm-devel (RPM) or …
```

Makefile.config: fix/improve feature warnings.

---

criu/cr-check.c
scripts/ci/run-ci-tests.sh

Check that the file device and inode shown in /proc/pid/maps match values returned by stat(2).

check: verify ino and dev of overlayfs files in /proc/pid/maps

---

criu/mem.c

During restore, CRIU prints `"Enqueue page-read"` messages for each page-read request (https://github.com/checkpoint-restore/criu/commit/91388fc). However, this message does not provide useful information, increases performance overhead during restore and the size of log file.
```
$ ./zdtm.py run -t zdtm/static/maps06 -f h -k always
$ grep 'Enqueue page-read' dump/zdtm/static/maps06/56/1/restore.log | wc -l
20493
```
This pull request replaces these messages with a single message that shows the number of enqueued page-read requests.
```
$ grep 'enqueued' dump/zdtm/static/maps06/56/1/restore.log
(00.061449)     56: nr_enqueued:   20493
```

mem: optimize debug logging of enqueued pages

---

criu/sk-tcp.c

1) In dump_tcp_conn_state, if return from libsoccr_save is >=0, we check that sizeof(struct libsoccr_sk_data) returned from libsoccr_save is equal to sizeof(struct libsoccr_sk_data) we see in dump_tcp_conn_state (probably to check if we use the right library version). And if sizes are different we go to err_r, which just returns ret, which can teoretically be 0 (if size in library is zero) and that would lead dump_one_tcp treat this as success though it is obvious error.
2) In case of dump_opt or open_image fails we don't explicitly set ret and rely that sizeof(struct libsoccr_sk_data) previously set to ret is not 0, I don't really like it, it makes reading code too complex.
3) We have a lot of err_* labels which do exactly the same thing, there is no point in having all of them, also it …

sk-tcp: cleanup dump_tcp_conn_state error handling

---

test/Makefile

A fault-injection test was introduced in b95407e264fcf58f4f73f78abef6dac60436e7dd and later removed in 2cb4532e266d0c9f8e87839d5b5eb728a3e4d10d. This pull request removes the obsolete Makefile target for this test.

test/make: remove unused target

---

scripts/ci/run-ci-tests.sh

The rawhide tests runs in a container. Containers always have SELinux disabled from the inside. Somehow `/sys/fs/selinux` is now mounted. We used the existence of that directory if SELinux is available. This seems to be no longer true.
Signed-off-by: Adrian Reber <areber@redhat.com>
Fixes: #2406

ci: update check for SELinux

---

criu/autofs.c
criu/timens.c
criu/timer.c

See also:
https://wiki.debian.org/ReleaseGoals/64bit-time
Needed for:
https://github.com/checkpoint-restore/criu/issues/2404

criu: use proper format-specified to accommodate time_t 64-bit change

---

criu/net.c
scripts/build/Dockerfile.x86_64.hdr

The unix_conf_op function reads the size of the sysctl entry array twice. gcc thinks that it can lead to a time-of-check to time-of-use (TOCTOU) race condition if the array size changes between the two reads.
Fixes #2398

net: Fix TOCTOU race condition in unix_conf_op

---

criu/pagemap-cache.c
scripts/ci/run-ci-tests.sh
test/libfault/Makefile
test/libfault/libfault.c
test/zdtm.py
test/zdtm/criu_config.py

It is possible for `pread()` to return fewer number of bytes than requested. In such case, we need to repeat the read operation with appropriate offset.
Fixes: https://github.com/checkpoint-restore/criu/issues/2365

pagemap-cache: handle short reads

---

Makefile.install
crit/Makefile
lib/Makefile

This pull request moves `PYTHON_EXTERNALLY_MANAGED` and `PIP_BREAK_SYSTEM_PACKAGES` into `Makefile.install` to avoid code duplication and adds `PIPFLAGS` variable to enable specifying pip options during installation. This is particularly useful for packaging where it is common for `pip install` to run in an environment with pre-installed dependencies and without internet.
Related to https://github.com/checkpoint-restore/criu/issues/2404

make: improve check for externally managed Python

---

README.md

The current link opens a page with the following text:
The MediaWiki FAQ can be found at:
https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:FAQ

readme: update link to FAQ page

---

compel/include/uapi/ptrace.h

Hi,
This PR fixes build failure on Amazon Linux 2 (and any other distro using glibc 2.26 or older). Further explanation is already in the commit message, which I have pasted below.
Regards,
Pratyush Yadav
------
Commit fc683cb01 ("compel: shstk: save CET state when CPU supports it") started using PTRACE_ARCH_PRCTL to query shadow stack status. While PTRACE_ARCH_PRCTL has existed in the kernel for a long time, it was only added to glibc in version 2.27. Amazon Linux 2 (AL2) has glibc 2.26, which does not have this definition. As a result, build on AL2 fails with the below error:
compel/arch/x86/src/lib/infect.c: In function ‘get_task_xsave’:
compel/arch/x86/src/lib/infect.c:276:14: error: ‘PTRACE_ARCH_PRCTL’ undeclared (first use in this function)
276 |   if (ptrace(PTRACE_ARCH_PRCTL, pid, …

compel: fix build on Amazon Linux 2 due to missing PTRACE_ARCH_PRCTL

---

criu/apparmor.c

Before this fix, it could return MAP_FAILED which is ((void *) -1).

apparmor: get_suspend_policy must return NULL in error cases

---

criu/arch/x86/include/asm/vdso.h

It was added in v5.3-rc1~211^2~4^2~10.
Fixes #2390

vdso: proxify the __vdso_clock_gettime64 function

---

scripts/build/Makefile
scripts/ci/Makefile

The CI tests with CentOS 7 have been disabled and removed (https://github.com/checkpoint-restore/criu/commit/24bc083653f7d2b984653194e921b1ff32292b3b, https://github.com/checkpoint-restore/criu/commit/f8466ca798acd124eebbba2655894ebd2f777879, https://github.com/checkpoint-restore/criu/commit/42a5b640f658771d2ddf238045bf4fa54569a64a). This pull request removes the obsolete Makefile targets for these tests.

scripts/build: Drop CentOS 7 makefile targets

---

test/zdtm/static/cgroup00.desc
test/zdtm/static/cgroup01.desc
test/zdtm/static/cgroup02.desc
test/zdtm/static/cgroup_threads.desc
test/zdtm/static/cgroup_yard.desc
test/zdtm/static/cgroupns.desc
test/zdtm/static/cgroupv2_00.desc
test/zdtm/static/cgroupv2_01.desc

cgroup testcases live in the same cgroup root zdtmtst and zdtmtst.defaultroot controller then create child subgroup for testing. This can cause problems when cgroup testcases run in parallel. For example, testcase A dumps the child subgroup of testcase B since it's in the cgroup root but in the middle of restoring of testcase A, testcase B completes and cleans up the subgroup directory. This causes error in testcase A restore. This commit adds excl flag to all cgroup testcases description so that these don't run parallel.
Fixes: #2405

zdtm: make cgroup testcases run non-parallel

---

criu/cr-restore.c
test/zdtm/static/rseq00.c
test/zdtm/transition/rseq01.c

We plan to backport this glibc change all the way to glibc 2.35. Most distributions use the stable release branches, so they will get this change eventually. I hope this is still fine from a CRIU perspective because the non-`ptrace` fallback path is not used.

Adjust to glibc __rseq_size semantic change

---

Documentation/criu-amdgpu-plugin.txt

This pull request updates the dependencies section of the amdgpu-plugin man page to reflect that the plugin has been merged upstream and to fix a formatting issue.

docs: update amdgpu-plugin man page

---

plugins/amdgpu/Makefile
plugins/cuda/Makefile

For historical reasons, some tools like [rpm](https://docs.fedoraproject.org/en-US/package-maintainers/CommonRpmlintIssues/#unstripped_binary_or_object) or [ldd](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/ldd.bash.in;h=d6b640df;hb=HEAD#l154) may expect the executable bit to be present for the correct identification of shared libraries. The executable bit on .so files is set by default by compilers (e.g., GCC). It is not strictly necessary but primarily a convention.
```
$ sudo ldd /usr/lib/criu/*.so
/usr/lib/criu/amdgpu_plugin.so:
ldd: warning: you do not have execution permission for `/usr/lib/criu/amdgpu_plugin.so'
linux-vdso.so.1 (0x00007fd0a2a3e000)
libdrm.so.2 => /lib64/libdrm.so.2 (0x00007fd0a29eb000)
libdrm_amdgpu.so.1 => /lib64/libdrm_amdgpu.so.1 (0x00007fd0a29de000) …
```

plugins: set executable bit on .so files

---

test/others/mnt-ext-dev/run.sh
test/zdtm.py
test/zdtm/lib/ns.c

The current file system can be mounted with nodev.
Fixes #2441

test/zdtm: mount a new tmpfs into the zdtm /dev

---

criu/seize.c

The plugin hook `PAUSE_DEVICES` was recently introduced in a85f488595e0a3a6e6cc6ca7c94d4a00b1341aaf. This hook was intended to execute the `cuda-checkpoint` tool *before* the process tree is frozen. However, the `run_plugins()` call has been placed immediately *after* `freeze_processes()`. This causes the `cuda-checkpoint` tool to hang indefinitely during the checkpointing of CUDA applications running in containers, eventually leading to its termination by the timeout alarm.
This problem can be reproduced with the following example:
```
sudo podman run -d --rm \
--device nvidia.com/gpu=all --security-opt=label=disable \
quay.io/radostin/cuda-counter
sudo podman container checkpoint -l -e /tmp/checkpoint.tar
```

seize: fix pause-devices plugin hook

---

plugins/amdgpu/amdgpu_plugin.c
plugins/cuda/cuda_plugin.c

CRIU provides two plugins for checkpoint/restore of GPU applications: amdgpu and cuda. Both plugins use the `RESUME_DEVICES_LATE` hook to enable restore:
CR_PLUGIN_REGISTER_HOOK(CR_PLUGIN_HOOK__RESUME_DEVICES_LATE, amdgpu_plugin_resume_devices_late)
CR_PLUGIN_REGISTER_HOOK(CR_PLUGIN_HOOK__RESUME_DEVICES_LATE, cuda_plugin_resume_devices_late)
However, CRIU currently [does not support](https://github.com/checkpoint-restore/criu/blob/93746eb25014f21287f2edc5f5dd7545ce19ab52/criu/include/plugin.h#L42) running more than one plugin for the same hook. As a result, when both plugins are installed, the resume function for CUDA applications is not executed. To fix this, we need to make sure that both `plugin_resume_devices_late()` functions return `-ENOTSUP` when restore is not supported.

plugin: enable multiple plugins for the same hook

---

criu/pie/restorer.c

restorer.h has been included in line 43.
Fixes: 22963d282729 ("Hide asm/restorer.h from sources")

delete redundant include header files

---

criu/timer.c
test/zdtm/lib/msg.c
test/zdtm/lib/ns.c
test/zdtm/static/mtime_mmap.c
test/zdtm/static/pthread_timers.c
test/zdtm/static/vdso00.c
test/zdtm/static/vdso01.c

New internal glibc types [__timeval64](https://sourceware.org/git/?p=glibc.git;h=504c98717062cb9bcbd4b3e59e932d04331ddca5) and [__suseconds64_t](https://sourceware.org/git/?p=glibc.git;h=3fced064f23562ec24f8312ffbc14950993969e6) have been introduced as a solution for the [Y2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem). These 64-bit types are used across all architectures. However, this change causes build errors when cross-compiling on ARMv7 (armhf). This pull request updates the printf format specifiers to support 64-bit integer types.

timer: fix printf specifiers for __suseconds64_t

---

compel/include/uapi/infect.h
compel/src/lib/infect.c

1. os auto assignment vma addr maybe conflict with vma in gpu living migrate scene;
2. so, we should give choice to user;
3. default, user_set_remote_map is 0L, so we donot change default behave;
user set vma usecase:
```
// we use compel/test/infect/spy.c to show example
static int do_infection(int pid)
{
... ....
ictx = compel_infect_ctx(ctl);
ictx->log_fd = STDERR_FILENO;
// TODO: use should set assignment vma addr at here
ictx->user_set_remote_map = xxxxL;
parasite_setup_c_header(ctl);
.... .....
}
```

support user set remote mmap vma address

---

plugins/amdgpu/Makefile
plugins/amdgpu/amdgpu_plugin.c
plugins/amdgpu/amdgpu_plugin_util.c
plugins/amdgpu/kfd_ioctl.h
scripts/build/Dockerfile.stable-cross.tmpl

This pull request fixes a problem with cross compilation for the amdgpu plugin (similar to https://github.com/checkpoint-restore/criu/pull/2428) and enables CI testing.
In addition, it allows building RPM/DEB packages that provide the amdgpu-plugin for CPU architectures currently supported by CRIU [^1].
[^1]: https://src.fedoraproject.org/rpms/criu/pull-request/11

plugins/amdgpu: fix cross compilation

---

.github/workflows/actuated-aarch64-test.yaml
coredump/coredump
crit/crit/__main__.py
test/others/criu-coredump/test.sh
test/others/ns_ext/run.sh
test/zdtm/static/macvlan.checkskip
test/zdtm/static/selinux00.checkskip

This brings aarch64 based tests to CRIU GitHub CI setup. The difference to the previous configurations is that now actually all tests (almost) are being run.
The tests on the actuated runners are with following limitations:
* tests using macvlan have to be skipped as that module is not available
* the coredump python script is x86_64 only (register names and other arch specific code)
* the `change_mnt_context` test fails with
```
```
* the `sched_policy00` test fails with
```
```
* in combination with '--remote-lazy-pages' following error occurs:
```
```
* the crit test case triggers an out of range error when displaying rss on aarch64 which was fixed based on an old commit from @rst0git

ci: run aarch64 tests native via actuated

---

plugins/cuda/cuda_plugin.c

When attempting to checkpoint a container with CUDA processes, CRIU could fail with the following error:
```
Error (criu/cr-dump.c:1791): Timeout reached. Try to interrupt: 1
Error (cuda_plugin.c:143): cuda_plugin: Unable to read output of cuda-checkpoint: Interrupted system call
Error (cuda_plugin.c:384): cuda_plugin: PAUSE_DEVICES failed with
``` 
In this situation, the target process is locked, but CRIU fails due to a timeout and exits with an error. We need to make sure that the target PID is unlocked in such case.

cuda: unlock on timeout error

---

criu/kerndat.c
test/others/bers/bers.c

This pull request fixes the following typos reported by codespell:
```
./test/others/bers/bers.c:394: dependin ==> depending, depend in
./criu/kerndat.c:837: hitted ==> hit
```

codespell: fix typos

---

Makefile.config
plugins/amdgpu/Makefile

By default, CRIU uses the path `/usr/lib/criu` to install and load plugins at runtime. This path is defined by the `PLUGINDIR` variable in `Makefile.install` and `CR_PLUGIN_DEFAULT` in `criu/include/plugin.h`. However, some distribution packages might install the CRIU plugins at `/usr/lib64/criu` instead. This patch updates the makefile to align the path defined by `CR_PLUGIN_DEFAULT` with the value of `PLUGINDIR`.

Makefile.config: set CR_PLUGIN_DEFAULT variable

---

Makefile
lib/pycriu/images/pb2dict.py

The command `ruff <path>` has been deprecated and removed:
https://astral.sh/blog/ruff-v0.5.0#removed-deprecated-features

make/lint: use 'ruff check <path>'

---

criu/cr-restore.c
criu/image.c
criu/include/image.h
criu/plugin.c
images/inventory.proto
plugins/amdgpu/amdgpu_plugin.c
plugins/cuda/cuda_plugin.c
scripts/ci/run-ci-tests.sh
test/plugins/Makefile
test/plugins/inventory_test_disabled_plugin.c
test/plugins/inventory_test_enabled_plugin.c
test/zdtm.py

This pull request extends the inventory image with a `plugins` field that contains an array of names indicating which plugins were used during checkpointing, for example, to save GPU state. In particular, the CUDA and AMDGPU plugins are added to this field *only* when the checkpoint contains GPU state. This allows to disable unnecessary plugins during restore, show appropriate error messages if required CRIU plugins are missing, and migrate a process that does not use GPU from a GPU-enabled system to CPU-only environment.
Examples:
1. The checkpoint contains AMDGPU state and requires `amdgpu_plugin` for restore.
```json
{
"magic": "INVENTORY",
"entries": [
{
"plugins_entry": {
"plugins": [
"amdgpu_plugin"
]
}
}
]
}
```
2. The checkpoint contains CUDA state and requires `cuda_plugin` for …

images/inventory: add field for enabled plugins

---

criu/include/pagemap.h
criu/pagemap.c
criu/uffd.c

After a fork, both the child and parent processes may trigger a page fault (#PF) at the same virtual address, referencing the same position in the page image. If deduplication is enabled, the last process to trigger the page fault will fail.
Therefore, deduplication should be disabled after a fork to prevent this issue.

uffd: Disable image deduplication after fork

---

criu/seize.c

When `check_freezer_cgroup()` has non-zero return value, `goto err` calls `return ret`. However, the value of `ret` has been set to `0` in the lines above and CRIU does not handle the error properly.
This problem is related to https://github.com/checkpoint-restore/criu/issues/2508

seize: fix error handling for check_freezer_cgroup

---

plugins/cuda/cuda_plugin.c

The check for `/dev/nvidiactl` to determine if the CUDA plugin can be used is unreliable because in some cases the default path for driver installation is different [^1]. This pull request changes the logic to check if a GPU device is available in `/proc/driver/nvidia/gpus/`. This approach is similar to [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/_modules/torch/cuda.html#is_available) and it is a more accurate indicator. The subsequent check for support of the `cuda-checkpoint --action` option would confirm if the driver supports checkpoint/restore.
[^1]: https://github.com/NVIDIA/gpu-operator
Fixes: #2509

cuda: fix check for GPU device availability

---

criu/files.c
criu/include/pidfd.h
criu/pidfd.c
test/zdtm/static/Makefile
test/zdtm/static/pidfd_diffdead.c

Fixes: #2496
This patch ensures that the process that created the tmp process is the one that kills and waits for it after all pidfds have been opened. We do this by keeping track of each process that has to open a pidfd for the tmp process and the number of pidfds it has to open.
Thing I am unsure about need to dump the pid of the process that opened the pidfd. (This might be available from some where else)

pidfd: tmp process is waited upon by correct process

---

plugins/cuda/cuda_plugin.c
test/cuda-checkpoint/cuda-checkpoint.c

If a CUDA process is already in a "locked" or "checkpointed" state during `criu dump`, the CUDA plugin fails with an error because it attempts an unnecessary "lock" action using the `cuda-checkpoint` tool. This pull request extends the CUDA plugin to handle such case by first checking the original state of the CUDA process and skipping unnecessary "lock" and "checkpoint" actions if the process was already locked or checkpointed before CRIU was invoked.

cuda: enable checkpoint support for paused tasks

---

criu/pidfd.c

This pull request fixes the following error when building CRIU on Rocky Linux 8:
```
criu/pidfd.c: In function ‘pidfd_open’:
criu/pidfd.c:119:17: error: ‘__NR_pidfd_open’ undeclared (first use in this function); did you mean ‘pidfd_open’?
return syscall(__NR_pidfd_open, pid, flags);
^~~~~~~~~~~~~~~
pidfd_open
criu/pidfd.c:119:17: note: each undeclared identifier is reported only once for each function it appears in criu/pidfd.c:120:1: error: control reaches end of non-void function [-Werror=return-type]
}
^
criu/pidfd.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror] cc1: error: unrecognized command line option ‘-Wno-dangling-pointer’ [-Werror] cc1: all warnings being treated as errors
```

pidfd: add missing include

---

criu/include/util-vdso.h
criu/pie/parasite-vdso.c
criu/proc_parse.c
criu/vdso.c

The vvar_vclock was introduced by [1]. Basically, the old vvar vma has been splited on two parts. In term of C/R, these two vma-s can be still treated as one.
[1] e93d2521b27f ("x86/vdso: Split virtual clock pages into dedicated mapping")
Fixes #2532

vdso: handle vvar_vclock vma-s

---

plugins/cuda/cuda_plugin.c

When cuda-checkpoint fails an operation it always returns the positive CUDA error code. In CHECKPOINT_DEVICES that was getting passed up as the failure code from one of the calls so if the operation failed we would write the failure to the log but not stop the dump since that checked for error values less than 0.

cuda: Fix return value from CHECKPOINT_DEVICES

---

scripts/build/Dockerfile.openj9-ubuntu

Right now, this test fails with this error:
```
Error (criu/files-reg.c:1031): Can't dump ghost file
/criu/test/javaTests/omrvmem_000000626_Mlm48x of 2097152 size,
increase limit
```

test/java: increate the ghost file limit

---

test/zdtm/static/scm06.desc

The kernel releases a test socket asynchronously, so the restore can fail if it is executed before the kernel actually destroys the socket.
Fixes #2537

test: run scm06 in the ns and uns flavors

---

criu/seize.c

There are a few issues with the freeze_processes logic:
1. Commit https://github.com/checkpoint-restore/criu/commit/9fae23fbe292be7f041c599c03b1f84dadea5216 grossly (by 1000x) miscalculated the number of
attempts required, as a result, we are seeing something like this:
> (00.000340) freezing processes: 100000 attempts with 100 ms steps
> (00.000351) freezer.state=THAWED
> (00.000358) freezer.state=FREEZING
> (00.100446) freezer.state=FREEZING
> ...close to 100 lines skipped...
> (09.915110) freezer.state=FREEZING
> (10.000432) Error (criu/cr-dump.c:1467): Timeout reached. Try to interrupt: 0
> (10.000563) freezer.state=FREEZING
For 10s with 100ms steps we only need 100 attempts, not 100000.
2. When the timeout is hit, the "failed to freeze cgroup" error is not
printed, and the …

Freeze fixes and v1 kludges

---

criu/seize.c

Based on the code, the `ret` variable at this point does not represent the task state, so this log message should be moved to a position after the `compel_wait_task()` function.

seize: Adjust the position of the log message

---

criu/files-reg.c

Running the zdtm/static/unlink_regular00 test on Ubuntu 24.04 on aarch64 results in following error:
```
userns is supported
=== Run 1/1 ================ zdtm/static/unlink_regular00
==================== Run zdtm/static/unlink_regular00 in ns ====================
Skipping rtc at root
Start test
Test is SUID
./unlink_regular00 --pidfile=unlink_regular00.pid --outfile=unlink_regular00.out --dirname=unlink_regular00.test
Run criu dump
*** buffer overflow detected ***: terminated
############# Test zdtm/static/unlink_regular00 FAIL at CRIU dump ##############
Test output: ================================
<<< ================================
Send the 9 signal to  47
Wait for zdtm/static/unlink_regular00(47) to die for 0.100000
##################################### FAIL …
```

files-reg: fix buffer overflow on aarch64

---

criu/arch/aarch64/include/asm/types.h

On aarch64 the test cmdlinenv00 was failing with:
```
FAIL: cmdlinenv00.c:120: auxv corrupted on restore (errno = 11 (Resource temporarily unavailable))
```
Starting with Linux kernel version 6.3 the size of AUXV was changed:
```
commit 28c8e088427ad30b4260953f3b6f908972b77c2d
Author: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Date:   Wed Jan 4 14:20:54 2023 -0500
rseq: Increase AT_VECTOR_SIZE_BASE to match rseq auxvec entries
Two new auxiliary vector entries are introduced for rseq without
matching increment of the AT_VECTOR_SIZE_BASE, which causes failures
with CONFIG_HARDENED_USERCOPY=y.
Fixes: 317c8194e6ae ("rseq: Introduce feature size and alignment ELF auxiliary vector entries")
```
https://github.com/torvalds/linux/commit/28c8e088427ad30b4260953f3b6f908972b77c2d
With this …

test: fix cmdlinenv00 on aarch64

---

.github/workflows/check-commits.yml

* Switch to v4 actions/checkout (from v3)
* Use our apt wrapper to gracefully handle temporary repository errors

ci: two check-commits.yml changes

---

.cirrus.yml
.github/workflows/check-commits.yml
compel/include/uapi/infect-util.h
compel/src/lib/infect-util.c
compel/src/lib/infect.c
criu/Makefile.packages
criu/fdstore.c
criu/files.c
criu/image.c
criu/include/util.h
criu/netfilter.c
criu/pidfd-store.c
criu/unittest/mock.c
criu/util.c
images/inventory.proto
scripts/build/Dockerfile.alpine
scripts/build/Dockerfile.amd-rocm
scripts/build/Dockerfile.archlinux
scripts/build/Dockerfile.hotspot-alpine
scripts/build/Dockerfile.hotspot-ubuntu
scripts/build/Dockerfile.linux32.tmpl
scripts/build/Dockerfile.openj9-ubuntu
scripts/build/Dockerfile.riscv64-stable-cross.tmpl
scripts/build/Dockerfile.stable-cross.tmpl
scripts/build/Dockerfile.tmpl
scripts/build/Dockerfile.unstable-cross.tmpl
scripts/ci/prepare-for-fedora-rawhide.sh
scripts/ci/run-ci-tests.sh
scripts/ci/vagrant.sh

Using libnftables the chain to lock the network is composed of ("CRIU-%d", real_pid). This leads to around 40 zdtm tests failing with errors like this:
```
Error: No such file or directory; did you mean table 'CRIU-62' in family inet?
delete table inet CRIU-86
```
The reason is that as soon as a process is running in a namespace the real PID can be anything and only the PID in the namespace is restored correctly. Relying on the real PID does not work for the chain name.
Using the PID of the innermost namespace would lead to the chain be called 'CRIU-1' most of the time which is also not really unique.
The uniqueness of the name was always problematic. With this change all tests are working again which rely on network locking if the nftables backend is used for network locking.

net: remember the name of the lock chain (nftables)

---

criu/cr-dump.c
criu/include/seize.h
criu/seize.c
plugins/cuda/cuda_plugin.c

When creating a checkpoint of large models, the `checkpoint` action of `cuda-checkpoint` can exceed the CRIU timeout. This causes CRIU to fail with the following error, leaving the CUDA task in a locked state:
cuda_plugin: Checkpointing CUDA devices on pid 84145 restore_tid 84202
Error (criu/cr-dump.c:1791): Timeout reached. Try to interrupt: 0
Error (cuda_plugin.c:139): cuda_plugin: Unable to read output of cuda-checkpoint: Interrupted system call
Error (cuda_plugin.c:396): cuda_plugin: CHECKPOINT_DEVICES failed with
net: Unlock network
cuda_plugin: finished cuda_plugin stage 0 err -1
cuda_plugin: resuming devices on pid 84145
cuda_plugin: Restore thread pid 84202 found for real pid 84145
Unfreezing tasks into 1
Unseizing 84145 into 1
Error (criu/cr-dump.c:2111): Dumping FAILED.
To fix …

cuda: prevent task lockup on timeout error

---

lib/c/criu.c

For two cases libcriu was setting the RPC protobuf field `has_*` before checking if the given parameter is valid. This can lead to situations, if the caller doesn't check the return value, that we pass as RPC struct to CRIU which has the `has_*` protobuf field set to true, but does not have a verified value (or non at all) set for the actual RPC entry.
Detected via https://github.com/containers/crun/issues/1627

lib: do not set protobuf has_* field too early

---

.codespellrc
criu/include/rbtree.h
criu/include/rst_info.h
criu/page-xfer.c
test/zdtm/static/packet_sock.c

CI pulls in a newer version of codespell. This fixes complaints from that codespell version.

ci: handle results from latest codespell

---

criu/net.c
images/netdev.proto
test/zdtm/lib/sysctl.c
test/zdtm/lib/sysctl.h
test/zdtm/static/netns_sub_sysctl.c

Here are preparation patches for https://github.com/checkpoint-restore/criu/pull/2558

checkpoint/restore ping_group_range sysctl

---

criu/pie/util-vdso.c

Trying to run latest CRIU on CentOS Stream 10 or Ubuntu 24.04 (aarch64) fails like this:
```
[...]
(00.096460) vdso: Parsing at ffffb2e2a000 ffffb2e2c000
(00.096539) vdso: PT_LOAD p_vaddr: 0
(00.096567) vdso: DT_STRTAB: 1d0
(00.096592) vdso: DT_SYMTAB: 128
(00.096616) vdso: DT_STRSZ: 8a
(00.096640) vdso: DT_SYMENT: 18
(00.096663) Error (criu/pie-util-vdso.c:193): vdso: Not all dynamic entries are present
(00.096688) Error (criu/vdso.c:627): vdso: Failed to fill self vdso symtable
(00.096713) Error (criu/kerndat.c:1906): kerndat_vdso_fill_symtable failed when initializing kerndat.
(00.096812) Found mmap_min_addr 0x10000
(00.096881) files stat: fs/nr_open 1073741816
(00.096908) Error (criu/crtools.c:267): Could not initialize kernel features detection.
```
This seems to be related to the …

vdso: switch from DT_HASH to DT_GNU_HASH (aarch64)

---

.codespellrc
Makefile

This way,
- Makefile is less cluttered;
- one can run codespell from the command line.
Fixes: fd7e97fcf ("lint: exclude tags file from codespell")

Makefile: move codespell options to .codespellrc

---

criu/kerndat.c

Resolving service names can be slow and it isn't needed here.
Fixes #2032

kerndat: run iptables with -n to not resolve service names

---

criu/cgroup.c

What do i want:
I want to fix bug in function "find_dir()". Then CRIU add cgroups it search
parent directory for cgroup to add it in the correct place. But function
that check it - "strstartswith()" is incorrent in this context. For example:
New cgroup: /dsch_tasks
Existent cgroup: /dsch
The "strstartswith" will return TRUE (which is ok) but in our context
/dsch is not parent directory for /dsch_tasks.
Thats why i cannot restore my application. So i want to fix this bug:
"(00.002162) Error (criu/cgroup.c:1766): cg: failed to open cg dir fd
(freezer//dsch/tasks) for chowning: Not a directory"
How i want to do it:
I replace "strstartswith()" on to "issubpath()" function.
It is written exactly for this purpose.
Signed-off-by: Dmitrii Chervov <dschervov1@yandex.ru>

Fixes: internal representation of cgroups hierarchical structure

---

coredump/coredump
coredump/criu_coredump/coredump.py
coredump/criu_coredump/elf.py
test/others/criu-coredump/test.sh

@rst0git can you please check this patch? Have I included all the relevant notes and registers? I was using the output of `gcore` to verify which notes need to be added. I will soon add the support for more architectures if this one is alright.
Thank you.

Enable coredump generation for `aarch64` and `arm`

---

scripts/uninstall_module.py

With Python 3.13, the `subprocess` module now uses the `posix_spawn()` function [^1], which requires the `signal` module to be imported.
Fixes: #2607
[^1]: https://docs.python.org/3/whatsnew/3.13.html#subprocess

scripts/uninstall_module: import signal module

---

criu/lsm.c

Currently CRIU has the possibility to specify a LSM label during restore. Unfortunately the information is completely ignored in the case of SELinux.
This change selects the lsm label from the user if it is provided and else the label from the checkpoint image is used.

lsm: use the user provided lsm label

---

criu/pie/util-vdso.c

On s390x there is currently a build failure:
```
criu/pie/util-vdso.c: In function ‘elf_symbol_lookup’: criu/pie/util-vdso.c:313:31: error: initialization of ‘uint32_t *’ {aka ‘unsigned int *’} from incompatible pointer type ‘Hash_t *’ {aka ‘long unsigned int *’} [-Wincompatible-pointer-types]
313 |                 uint32_t *h = bucket + nbucket + (j - sym_off);
|                               ^~~~~~
```
Replacing uint32_t with Hash_t which is defined behind a architecture specific ifdef solves this error.
Fixes: #2582
CC: @0x7f454c46

vdso: handle s390x correctly

---

criu/cr-restore.c
criu/include/rst_info.h
criu/pie/restorer.c

Threads are put into cgroups through the cgroupd thread, which communicates with other threads using a socketpair.  Each thread received a dup'd copy of the socket, and did the following
sendmsg(socket_dup_fd, my_cgroup_set);
// wait for ack.
while (1) {
recvmsg(socket_dup_fd, &h, MSG_PEEK);
if (h.pid != my_pid) continue;
recvmsg(socket_dup_fd, &h, 0);
}
close(socket_dup_fd);
When restoring many threads, most threads would be spinning in the above loop waiting for their PID to appear.
In my test-case, restoring a process with a 11.5G heap and 491 threads could take anywhere between 10 seconds and 60 seconds to complete.
To avoid the spinning, we drop the loop and MSG_PEEK, and add a lock around the above code. This does not decrease parallelism, as the cgroupd daemon uses a single thread …

Add a lock around cgroupd communication.

---

criu/pie/util-vdso.c

Let's change the data types of `nbucket` and `nchain` to uint32.
This should fix the following compile-time error on arm32:
/criu/criu/pie/util-vdso.c:336: undefined reference to `__aeabi_uldivmod'

vdso: correct data types for ELF hash table sizes

---

criu/log.c
include/common/lock.h

When using pr_err in signal handler, locking is used in an unsafe manner. If another signal happens while holding the lock, deadlock can happen.
To fix this, we can introduce mutex_trylock similar to pthread_mutex_trylock that returns immediately. Due to the fact that lock is used only for writing first_err, this change garantees that deadlock cannot happen.
Fixes: #358

criu: fix log_keep_err signal deadlock

---

criu/cr-restore.c

This is highly confusing, and it seems that the ret variable is not handled in the subsequent process.

criu: Do not print failed message when there is no late stage hook

---

compel/include/uapi/infect.h
compel/src/lib/infect.c
compel/test/stack/spy.c

The stack test incorrectly assumed the page immediately following the stack pointer could never be changed. This doesn't work, because this page can be a part of another mapping.
This commit introduces a dedicated "stack redzone," a small guard region directly after the stack. The stack test is modified to specifically check for corruption within this redzone.

compel: fix the stack test

---

criu/cr-check.c
criu/include/kerndat.h
criu/include/prctl.h
criu/include/restorer.h
criu/kerndat.c
criu/pie/restorer.c
criu/timer.c

Thomas Gleixner introduced the new interface to create posix timers with specified timer IDs:
https://github.com/torvalds/linux/commit/ec2d0c04624b3c8a7eb1682e006717fa20cfbe24
Previously, CRIU recreated timers by repeatedly creating and deleting them until the desired ID was reached. This approach isn't fast, especially for timers with large IDs. For example, restoring two timers with IDs 1000000 and 2000000 took approximately 1.5 seconds.
The new `prctl()` based interface allows direct creation of timers with specified IDs, reducing the restoration time to around 3 microseconds for the same example.

restore: use the new kernel interface to restore timers

---

plugins/cuda/cuda_plugin.c

When handing errors for functions such as `ptrace()`, `pipe()`, and `fork()` it would be better to use `pr_perror` instead of `pr_err` as it would include a message describing the encountered error.

cuda: use pr_perror for libc function errors

---

criu/arch/aarch64/crtools.c

On a RHEL 8 based system building CRIU fails with:
```
criu/arch/aarch64/crtools.c: In function 'save_pac_keys': criu/arch/aarch64/crtools.c:73:39: error: 'NT_ARM_PAC_ENABLED_KEYS' undeclared (first use in this function); did you mean 'NT_ARM_PACA_KEYS'?
ret = ptrace(PTRACE_GETREGSET, pid, NT_ARM_PAC_ENABLED_KEYS, &iov);
^~~~~~~~~~~~~~~~~~~~~~~
NT_ARM_PACA_KEYS
criu/arch/aarch64/crtools.c:73:39: note: each undeclared identifier is reported only once for each function it appears in criu/arch/aarch64/crtools.c: In function 'arch_ptrace_restore': criu/arch/aarch64/crtools.c:261:44: error: 'NT_ARM_PAC_ENABLED_KEYS' undeclared (first use in this function); did you mean 'NT_ARM_PACA_KEYS'?
if ((ret = ptrace(PTRACE_SETREGSET, pid, NT_ARM_PAC_ENABLED_KEYS, &iov))) {
^~~~~~~~~~~~~~~~~~~~~~~ …
```

aarch64: fix build with missing NT_ARM_PAC_ENABLED_KEYS

---

criu/cr-restore.c
criu/include/net.h
criu/net.c

CRIU is locking the network during restore in an "empty" network namespace. However, "empty" in this context means CRIU isn't restoring the namespace. This network namespace can be the same namespace where processes have been dumped and so the network is already locked in it.
Fixes #2650

net: nftables: avoid restore failure if the CRIU nft table already exist

---

criu/arch/aarch64/crtools.c

Building CRIU package on Debian 11 aarch64 fails with the following errors. This patch adds the missing constants and structs if undefined.
```
criu/arch/aarch64/crtools.c: In function 'save_pac_keys': criu/arch/aarch64/crtools.c:32:31: error: storage size of 'paca' isn't known
struct user_pac_address_keys paca;
^~~~
criu/arch/aarch64/crtools.c:33:31: error: storage size of 'pacg' isn't known
struct user_pac_generic_keys pacg;
^~~~
criu/arch/aarch64/crtools.c:47:15: error: 'HWCAP_PACA' undeclared (first use in this function); did you mean 'HWCAP_FCMA'?
if (hwcaps & HWCAP_PACA) {
^~~~~~~~~~
HWCAP_FCMA
criu/arch/aarch64/crtools.c:47:15: note: each undeclared identifier is reported only once for each function it appears in criu/arch/aarch64/crtools.c:53:44: error: 'NT_ARM_PACA_KEYS' …
```

aarch64/crtools: fix define for missing constants

---

criu/mount-v2.c
criu/mount.c
test/zdtm.py
test/zdtm/lib/ns.c
test/zdtm/static/Makefile
test/zdtm/static/mnt_ro_root.c
test/zdtm/static/mnt_ro_root.desc

mount-v2: restore root mount flags
Mount flags belong to mount and mount namespace of the Container, so we
should preserve them, as Container user will not expect mounts switching
between ro and rw over c/r.
Fixes: https://github.com/checkpoint-restore/criu/issues/2632

Preserve root mount flags

---

criu/sk-inet.c

With Go version 1.24, `ListenConfig` now uses MPTCP [by default](https://go.dev/doc/go1.24#netpkgnet). Checkpoint/restore for this protocol is not currently supported and adding support requires kernel changes that are not trivial to implement. As a result, checkpointing of many containers that run Go programs is likely to fail with the following error (https://github.com/checkpoint-restore/criu/issues/2655):
```
(00.026522) Error (criu/sk-inet.c:130): inet: Unsupported proto 262 for socket 2f9bc5
```
This patch adds a message with suggested workaround for this problem.

sk-inet: add message how to disable MPTCP in Go

---

criu/cr-check.c
criu/cr-restore.c
criu/include/kerndat.h
criu/kerndat.c
criu/parasite-syscall.c

In some cases, they might not work in virtual machines if the hypervisor doesn't virtualize them. For example, they don't work in AMD SEV virtual machines if the Debug Virtualization extension isn't supported or isn't enabled in SEV_FEATURES.
Fixes #2658

kerndat: check that hardware breakpoints work

---

criu/seize.c

The container checkpointing procedure in Kubernetes freezes running containers to create a consistent snapshot of both the runtime state and the rootfs of the container. However, when checkpointing a GPU container, the container must be unfrozen before invoking `cuda-checkpoint`. This is achieved in `prepare_freezer_for_interrupt_only_mode()`, which needs to be called before the `PAUSE_DEVICES` hook.
The patch introducing this functionality (in #2514) fixes this problem for containers with multiple processes. However, if the container has a single process, `prepare_freezer_for_interrupt_only_mode()` must be invoked immediately before the  `PAUSE_DEVICES` hook.
Fixes: #2514

seize: fix pause devices for frozen containers

---

criu/sk-inet.c

Ubuntu 20.04 ships with kernel 5.4 by default, which does not include MPTCP support. As a result, building CRIU fails with the following error:
```
criu/sk-inet.c: In function 'can_dump_ipproto':
criu/sk-inet.c:131:16: error: 'IPPROTO_MPTCP' undeclared (first use in this function); did you mean 'IPPROTO_MTP'?
131 |   if (proto == IPPROTO_MPTCP)
|                ^~~~~~~~~~~~~
|                IPPROTO_MTP
```
This pull request add definition for `IPPROTO_MPTCP` to fix this error.

sk-inet: add MPTCP definition

---

Documentation/criu-amdgpu-plugin.txt
criu/cr-dump.c
criu/cr-restore.c
criu/include/criu-plugin.h
criu/include/pstree.h
criu/plugin.c
criu/pstree.c
criu/seize.c
plugins/amdgpu/Makefile
plugins/amdgpu/README.md
plugins/amdgpu/amdgpu_plugin.c
plugins/amdgpu/amdgpu_plugin_topology.c
plugins/amdgpu/amdgpu_plugin_topology.h
plugins/amdgpu/amdgpu_socket_utils.c
plugins/amdgpu/amdgpu_socket_utils.h

**TL;DR:**
This pull request extends CRIU to support parallel restore of AMDGPU buffer object content alongside other restore operations to accelerate the restoration.
**The target issue:** 
In the current restore procedure of AMDGPU applications, the content of the AMDGPU buffer object (BO) is restored synchronously in `CR_PLUGIN_HOOK__RESTORE_EXT_FILE`. This procedure usually takes a significant amount of time, and during this time the target process cannot perform any other restore operations. However, this restoration has no logical dependencies with other restore operations. Parallelizing this part with other restore operations can speed up the restoration.
**The parallel restore approach in this PR:** 
The core idea of these patch series is to offload the restore of the BO content …

AMDGPU: add parallel restore of BO content to accelerate restore

---

test/zdtm.py

By default zdtm expects that criu is built from source first and only then you can run zdtm tests against it. But what if you really want to run tests against a criu version installed on the system? Yes there is already a nice option for zdtm to change the criu binary it uses "--criu-bin", but it would still end up using the pycriu module from source and you would still have to build everything beforehand.
Let's add an option to change the path where zdtm searches for pycriu module "--pycriu-search-path". This way we can run zdtm tests on the criu installed on the system directly without building criu from source, e.g. on Fedora it works like:
```
test/zdtm.py run --criu-bin /usr/sbin/criu \
--pycriu-search-path /usr/lib/python3.13/site-packages \
-t zdtm/static/env00
```

zdtm.py: add an option to change pycriu import path

---

images/Makefile
plugins/amdgpu/Makefile
test/others/rpc/Makefile
test/others/unix-callback/Makefile
test/zdtm/static/Makefile

The new protoc 1.5.2 reports warnings:
`protoc-c` is deprecated. Please use `protoc` instead!

image: use `protoc` instead of `protoc-c`

---

criu/include/mman.h
criu/mem.c
criu/proc_parse.c
lib/pycriu/images/pb2dict.py
test/zdtm/static/Makefile
test/zdtm/static/get_smaps_bits.c
test/zdtm/static/maps02.c
test/zdtm/static/maps11.c

It would be good to have this before https://github.com/checkpoint-restore/criu/pull/2652 as I would like to test how these two can co-exist.
ToDo:

mem: support VM_WIPEONFORK/MAP_DROPPABLE

---

test/zdtm/Makefile.inc

Fixes a clang compile-time error: "argument unused during compilation: '-c'".

test/zdtm: remove unused argument during compilation

---

criu/cr-service.c
criu/log.c
test/others/rpc/errno.py

Introduce interface to criu-log component to allocate 
first error buffer shared between a parent and its children.
Use shared first error buffer to return correct
first error in rpc.
Fixes: #338

rpc/log: return first error always

---

criu/include/sysctl.h
criu/net.c
criu/sk-inet.c
criu/sockets.c
test/zdtm/Makefile.inc
test/zdtm/static/Makefile
test/zdtm/static/netns_sub_sysctl.c
test/zdtm/static/netns_sub_sysctl.desc
test/zdtm/static/socket6_icmp.c
test/zdtm/static/socket_icmp.c

Currently there is no option to checkpoint/restore programs that use ICMP sockets, such as `ping`. This patch adds support for the same.
Fixes #2557

sk-inet: Add support for checkpoint/restore of ICMP sockets

---

criu/mount-v2.c

A kernel change (commit 12f147ddd6de, "do_change_type(): refuse to operate on unmounted/not ours mounts") modified how mount propagation properties can be changed. Previously, these properties could be changed from any mount namespace. Now, they can only be modified from the specific mount namespace where the target mount is actually mounted
This commit addresses this new restriction by ensuring that CRIU enters the correct mount namespace before attempting to restore mount propagation properties (MS_SLAVE or MS_SHARED) for a mount.
Fixes #2694

mount-v2: enter the mount namesapce to propagation properties

---

scripts/ci/vagrant.sh

This pull request updates the Fedora image used to run the CI tests with Vagrant and resolves a few errors.

ci: fix vagrant tests

---

criu/cr-check.c
criu/cr-dump.c
criu/cr-restore.c
criu/include/image.h
criu/include/kerndat.h
criu/include/mem.h
criu/include/mman.h
criu/include/pagemap_scan.h
criu/kerndat.c
criu/mem.c
criu/pagemap-cache.c
criu/pie/restorer.c
criu/shmem.c
criu/vdso.c
scripts/ci/vagrant.sh
test/zdtm/static/Makefile
test/zdtm/static/maps12.c
test/zdtm/static/maps12.desc

Ready for review / merge.
Linux kernel 6.16+ is required to support dump for `MADV_GUARD_INSTALL`-protected pages.
Change-log:
05.08.2025: completely reworked to support file mappings and shared mappings
ToDo:
Closes #2626

Support MADV_GUARD_INSTALL

---

test/zdtm/static/maps12.c

The `offset` argument to `mmap()` was computed with a direct cast from pointer to `off_t`:
(off_t)addr_hint - (off_t)map_base
This causes a build failure when compiling since pointers and `off_t` may differ in size on some platforms. The fix in this patch is to cast both pointers to `intptr_t`, perform the subtraction in that type, and then cast the result back to `off_t`.

test/zdtm/static/maps12: fix pointer-to-int cast

---

compel/arch/mips/src/lib/handle-elf.c

On **MIPS** platforms, shared libraries may use **EI_ABIVERSION** = 5 to indicate
support for **.MIPS.xhash** sections. The previous ELF header check in
`handle_binary()` strictly compared e_ident against a hardcoded value,
causing legitimate shared objects to be rejected.
This patch replaces the memcmp-based check with a structured validation
of ELF magic and class, and allows **EI_ABIVERSION** values beside 0.
fixes: #2745

fix: Relax ELF magic check to support MIPS libraries

---

criu/lsm.c

On some kernels, attr/current can be intercepted by BPF LSM, causing errors (#2033). Using attr/apparmor/current is preferable, because it is guaranteed to return the apparmor label. attr/current will still be used as a fallback for older kernels.
Fixes: #2033

lsm: use attr/apparmor/current to get apparmor label

---

criu/files.c
criu/pstree.c

On restore, CRIU needs to change mount namespaces to properly restore files and unix sockets. However, the kernel prevents this if a process is sharing its file system information (fs) with other processes.
Fixes #2687

files: fork helpers without CLONE_FILES | CLONE_FS

---

criu/page-xfer.c
criu/pagemap.c

`page_pipe_read()` expects an `unsigned long *`, but `pi->nr_pages` is `u64`. On 32-bit platforms (e.g., armv7), passing `&pi->nr_pages` directly causes a compiler error. To fix this we introduce a temporary variable and copy the result back to `pi->nr_pages`.
Fixes: #2756

page-xfer: fix incompatible pointer type on armv7

---

.github/workflows/alpine-test.yml
compel/arch/aarch64/src/lib/include/uapi/asm/sigframe.h
contrib/dependencies/apk-packages.sh
criu/arch/aarch64/include/asm/restorer.h

Compilation on gentoo/arm64 (llvm+musl) fails with:
```
In file included from compel/include/uapi/compel/asm/sigframe.h:4,
from compel/plugins/std/infect.c:14:
/usr/include/asm/sigcontext.h:28:8: error: redefinition of 'struct sigcontext'
28 | struct sigcontext {
|        ^~~~~~~~~~
In file included from criu/arch/aarch64/include/asm/restorer.h:4,
from criu/arch/aarch64/crtools.c:11:
/usr/include/asm/sigcontext.h:28:8: error: redefinition of 'struct sigcontext'
28 | struct sigcontext {
|        ^~~~~~~~~~
```
This is happening because <asm/sigcontext.h> and <signal.h> are mutually incompatible on Linux.
To fix, use  <signal.h> instead of <asm/sigcontext.h> for arm64 (like all others arches do).

criu/compel: fix compilation on musl/arm64
