checkpoint-restore/criu

- lib/c/criu.c
The functions criu_(local_)set_service_address and
criu_(local_)set_service_binary are the only functions that
do not create a copy of the given string arguments.
This may lead to problems, if the original string gets freed
but criu relies on them.
Additionally, the function criu_local_init_opts() assigns the
default service_binary now to opt->service_binary instead of
opt->service_address which is in my opinion the preferred way
since both are types of an anonymous union.
Signed-off-by: Martin Wührer <martin.wuehrer@artech.at>
> c-lib: strdup for service_address and service_binary

- Documentation/criu.txt
Document **post-resume**, **post-setup-namespaces** and **orphan-pts-master** action-script hooks.
> criu(8): Update list of action-script hooks

- criu/img-cache.c
- criu/img-proxy.c
- criu/img-remote.c
Sort and remove unused/unnecessary include stements in `criu/img-*.c`
> Sort includes in criu/img-*.c

- coredump/criu_coredump/coredump.py
> [coredump]: correct the parsing of reg_files from files.img

- lib/py/images/pb2dict.py
> pb2dict: Resolve Py2/3 compatibility issues

- test/zdtm/static/autofs.c
- test/zdtm/static/caps00.c
- test/zdtm/static/packet_sock_mmap.c
- test/zdtm/static/s390x_runtime_instr.c
- test/zdtm/static/sock_peercred.c
- test/zdtm/static/unlink_multiple_largefiles.c
- test/zdtm/static/vdso-proxy.c
- test/zdtm/transition/lazy-thp.c
These errors were found by Cppcheck 1.84
> zdtm: Fix memory and resource leaks

- lib/Makefile
This will be useful to bind libcriu features into one binary. e.g. container runtime or some ops tools.
Would anyone have time to check this out?
> c-lib: Support to build a static archive

- test/zdtm/static/seccomp_filter_threads.c
- test/zdtm/static/seccomp_filter_tsync.c
As discusses on the [musl mailing list](https://www.openwall.com/lists/musl/2019/06/26/7) when libc api is used to create a POSIX thread, and this thread is killed by seccomp, this breaks a fundamental assumption the C runtime relies on, causing any libc call (i.e. pthread_join) after the kill to have undefined behaviour.
In order to work around the issue we could use `SECCOMP_RET_ERRNO` instead of `SECCOMP_RET_KILL`. This filter will set a magic value to user space as `errno` without executing the system call.
> zdtm: Refactor seccomp_filter_{threads,tsync}

- test/zdtm/static/packet_sock_mmap.c
7f95a16df000-7f95a16e1000 rw-p 00000000 00:09 2183152397                 socket:[2183152397]
> test/packet_sock_mmap: parse inode as unsigned long long

- criu/cr-dump.c
- criu/cr-restore.c
- criu/include/parasite.h
- criu/include/restorer.h
- criu/pie/parasite.c
- criu/pie/restorer.c
- images/core.proto
- test/zdtm/static/Makefile
- test/zdtm/static/child_subreaper.c
- test/zdtm/static/child_subreaper_and_reparent.c
- test/zdtm/static/child_subreaper_and_reparent.desc
- test/zdtm/static/child_subreaper_existing_child.c
1. Checkpoint it via parasite.
2. Restore it before forking.
3. Add ZDTM test.
> Add support for migrating CHILD_SUBREAPER prctl

- criu/mount.c
> mount: fix inconsistent return and goto err alternation

- criu/config.c
- criu/cr-check.c
- criu/crtools.c
- criu/proc_parse.c
This patch series aims to address some of the issues described in:
https://lists.openvz.org/pipermail/criu/2019-September/044469.html
https://lists.openvz.org/pipermail/criu/2019-September/044470.html
> crtools: flush early log using destructor

- .travis.yml
- scripts/build/Dockerfile.openj9-alpine
- scripts/build/Dockerfile.openj9-ubuntu
- scripts/travis/Makefile
- scripts/travis/openj9-test.sh
Add travis job to run Java functional tests on travis, as per #825 
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>
> Run java functional tests on travis

- test/javaTests/README.md
- test/javaTests/src/org/criu/java/tests/CheckpointRestore.java
- test/javaTests/src/org/criu/java/tests/FileRead.java
- test/javaTests/src/org/criu/java/tests/Helper.java
- test/javaTests/src/org/criu/java/tests/MemoryMappings.java
- test/javaTests/src/org/criu/java/tests/MultipleFileRead.java
- test/javaTests/src/org/criu/java/tests/MultipleFileWrite.java
- test/javaTests/src/org/criu/java/tests/ReadWrite.java
- test/javaTests/test.xml
Add remaining File-based Java functional tests, as per #825 
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>
> Add File-based Java Functional Tests

- README.md
We will continue accepting patches.
> readme: github pull-requests is the preferred way to contribute

- criu/arch/x86/cpu.c
Make xfeatures_mask check explicit.
Split up comments about xsave_size and xfeatures_mask because we have
different approaches for them:
1) for xfeatures we need to have on destination all the features which we
had on source
2) for xsave_size we need to have smaller size on destination than on
source, because xsave operation on small allocated buffer may corrupt the
nearby data
Having single comment for both cases is less understandable.
> x86/cpu: cleanup and improve xfeatures_mask check

- scripts/build/Dockerfile.openj9-ubuntu
- test/javaTests/README.md
- test/javaTests/src/org/criu/java/tests/CheckpointRestore.java
- test/javaTests/src/org/criu/java/tests/Helper.java
- test/javaTests/src/org/criu/java/tests/SocketHelper.java
- test/javaTests/src/org/criu/java/tests/Sockets.java
- test/javaTests/src/org/criu/java/tests/SocketsClient.java
- test/javaTests/src/org/criu/java/tests/SocketsConnect.java
- test/javaTests/src/org/criu/java/tests/SocketsConnectClient.java
- test/javaTests/src/org/criu/java/tests/SocketsConnectServer.java
- test/javaTests/src/org/criu/java/tests/SocketsData.java
- test/javaTests/src/org/criu/java/tests/SocketsDataClient.java
- test/javaTests/src/org/criu/java/tests/SocketsDataServer.java
- test/javaTests/src/org/criu/java/tests/SocketsListen.java
- test/javaTests/src/org/criu/java/tests/SocketsListenClient.java
- test/javaTests/src/org/criu/java/tests/SocketsListenServer.java
- test/javaTests/src/org/criu/java/tests/SocketsMultiple.java
- test/javaTests/src/org/criu/java/tests/SocketsMultipleClient.java
- test/javaTests/src/org/criu/java/tests/SocketsMultipleServer.java
- test/javaTests/src/org/criu/java/tests/SocketsServer.java
- test/javaTests/test.xml
Add Socket-based Java Functional Tests, as per #825 
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>
> Add Socket-based Java Functional Tests

- scripts/build/Dockerfile.openj9-alpine
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>
> Switch openj9 alpine tests to python3

- criu/clone-noasan.c
clone3() explicitly blocks setting an exit_signal if CLONE_PARENT is specified. With clone() it also did not work, but there was no error message. The exit signal from the thread group leader is taken.
runc restores are currently failing if clone3() is present as clone3() returns EINVALID if exit_signal is set and CLONE_PARENT is specified.
This fix works for me, but I am not sure if it is the right approach.
> clone3: handle clone3() with CLONE_PARENT

- criu/cr-restore.c
- criu/files-reg.c
- criu/files.c
- criu/img-remote.c
- test/zdtm/lib/parseargs.c
- test/zdtm/lib/zdtmtst.h
> Rawhide build warnings

- test/zdtm/static/mntns_rw_ro_rw.c
Update error messages in `mntns_rw_ro_rw` test.
> zdtm: mntns_rw_ro_rw update error msg

- lib/py/images/pb2dict.py
- test/inhfd/memfd.py
- test/inhfd/socket.py
- test/others/rpc/config_file.py
- test/zdtm.py
This allows to run inhfd tests with many iterations of C/R.
> test/zdtm/inhfd: update dump options one each iteration

- test/jenkins/criu-fault.sh
> test/jenkins: remove empty line at the end of file

- criu/uffd.c
In the recent kernels the userfaultfd support for FORK events is limited to
CAP_SYS_PTRACE. That causes the followong error when the ioctl(UFFDIO_API)
is executed from non-privilieged userns:
Error (criu/uffd.c:273): uffd: Failed to get uffd API: Operation not permitted
Wrapping the call to ioctl(UFFDIO_API) in userns_call() resolves the issue.
Fixes: #964
> uffd: use userns_call() to execute ioctl(UFFDIO_API)

- criu/memfd.c
Right now, criu uses a dumped fd to dump content of a memfd "file".
Here are two reasons why we should not do this:
* a state of a dumped fd doesn't have to be changed, but now criu calls
lseek on it. This can be workarounded by using pread.
* a dumped descriptor can be write-only.
Cc: @nviennot
> memfd: don't corrupt a state of the dumped fd

- test/zdtm/transition/fifo_loop.c
... otherwise write() can block.
> zdtm/fifo_loop: don't try to write more than pipe size

- MAINTAINERS
Hope I have enough experience in the project to be nominated. I want to help with review and will try to do my best in it.
> MAINTAINERS: Add Pavel (myself) to maintainers

- criu/autofs.c
In real life cases pipe_ino param could be larger that INT_MAX,
but in autofs_parse() function we using atoi function, that uses
4 byte integers. It's a bug.
Example of mount info from real case:
(00.508286) 	type autofs source /etc/auto.misc mnt_id 2824 s_dev 0x4b9 / @
./misc flags 0x300000 options fd=5,pipe_ino=3480845226,pgrp=95929,timeout=300,
minproto=5,maxproto=5,indirect
3480845226 > 2147483647 (32-bit wide signed int max value) => we have a problem
It causes a error:
(03.195915) Error (criu/pipes.c:529): The packetized mode for pipes is not supported yet
Signed-off-by: Alexander Mikhalitsyn (Virtuozzo) <alexander@mihalicyn.com>
> autofs: fix integer overflow in mount options parsing

- criu/pstree.c
First don't free pstree_item as they are allocated with shmalloc on
restore. Second always pstree_entry__free_unpacked PstreeEntry. Third
remove all breaks replacing them with implict goto err, so that it would
be easier to understand that we are on error path.
Sadly there is no much use in xfree-ing pi->threads because in case of
an error we still have ->threads unfreed from previous entries anyway.
But at least some cleanup can be done here.
> pstree: improve error handling in read_pstree_image

- criu/arch/mips/include/asm/restorer.h
- criu/arch/mips/restorer.c
- criu/cr-restore.c
Related to this, zdtm test suites ipc.c、shm.c、shm-unaligned.c and shm-mp.c are passed.
Signed-off-by: Guoyun Sun <sunguoyun@loongson.cn>
> mips: impliment arch_shmat()

- criu/cr-restore.c
- criu/crtools.c
- criu/img-cache.c
- criu/img-proxy.c
- criu/img-remote.c
See the commit messages for details.
Aside from code simplification and bug fixes, the important contribution is the use of pipes instead of UNIX sockets for local communication, enabling highly efficient data transfers for proxies that use splice().
> Remote image: code simplification, fixes, and performance improvements

- criu/arch/x86/crtools.c
The layout of xsave frame in a standart format is predefined by the hardware.
Lets make sure we're increasing in frame offsets and use latest offset where
appropriate.
https://github.com/checkpoint-restore/criu/issues/1042
Reported-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>
Signed-off-by: Cyrill Gorcunov <gorcunov@gmail.com>
> arch/x86: Fix calculation of xstate_size

- scripts/travis/vagrant.sh
- test/zdtm/static/vdso01.checkskip
> test: skip vdso test on non-vdso systems

- Makefile
- flog/Makefile
- flog/built-in.S
- flog/include/compiler.h
- flog/include/flog.h
- flog/include/log.h
- flog/include/types.h
- flog/include/uapi/flog.h
- flog/include/util.h
- flog/src/Makefile
- flog/src/flog.c
- flog/src/main.c
- flog/tests/test00
Hello community! 
I have created this draft pr for my GSoC project of optimising logging engine and would be sending weekly pr's here.  
I have described the change in the commit message and would request your feedback on how to make it better or alternative approaches to follow.
I have included the link to the timeline containing the approach [here](https://docs.google.com/document/d/16JRdxWxHibPZ_HBHUu2EfbOZblKcVyWSbcATlHwHBXo/edit?usp=sharing). The wiki page containing the project idea is also referenced [here](https://criu.org/Google_Summer_of_Code_Ideas#Optimize_logging_engine).
Signed-off-by: prakritigoyal19 <prakritigoyal19@gmail.com>
> [GSoC 2020:WIP] Optimise Logging Engine

- criu/files-reg.c
This addresses [issue #1149](https://github.com/checkpoint-restore/criu/issues/1149). Even if the ELF file contains multiple PT_NOTE program headers, only the first header was being checked for the build-id.
Also addresses a bug where the RegFileEntry n_build_id field would be populated with incorrect data, causing dump to crash at times (Sometimes affected job 7 on Travis).
Mentors: @avagin @0x7f454c46
> Bug fixes for the build-ID validation method

- criu/action-scripts.c
- criu/autofs.c
- criu/cgroup-props.c
- criu/cgroup.c
- criu/cr-dump.c
- criu/files-reg.c
- criu/filesystems.c
- criu/img-streamer.c
- criu/irmap.c
- criu/kerndat.c
- criu/mount.c
- criu/net.c
- criu/page-xfer.c
- criu/pagemap.c
- criu/proc_parse.c
- criu/sk-netlink.c
- criu/uffd.c
- criu/util.c
- flog/src/flog.c
I went through all open coverity warnings and tried to fix them.
> Trying to fix many coverity warnings

- compel/src/lib/handle-elf.c
GNU ld precalculates this information but lld does not. With this change, handle-elf.c calculates those addresses on its own.
When calculating addresses sections with SHF_ALLOC bit are put one after another, respecting their alignment requirements. This matches the way how the blob is constructed by copying section contents.
This solves the issue with lld that was discussed in https://github.com/checkpoint-restore/criu/pull/1121 but this time in a way that handles all known cases.
Signed-off-by: Wojciech Marczenko <marczenko@google.com>
> compel: Calculate sh_addr if not provided by linker

- include/common/arch/x86/asm/bitops.h
Build on Fedora Core 33 produces the following warnings:
```
include/common/asm/bitops.h: Assembler messages:
include/common/asm/bitops.h:37: Warning: no instruction mnemonic suffix given and no register operands; using default for `bt'
include/common/asm/bitops.h: Assembler messages:
include/common/asm/bitops.h:63: Warning: no instruction mnemonic suffix given and no register operands; using default for `bts'
```
Update test_bit() and test_and_set_bit() implementation with recent
version from the Linux kernel to fix the warning.
Fixes #1217
Reported-by: Adrian Reber <areber@redhat.com>
> x86/asm: update test_bit() and test_and_set_bit()

- .travis.yml
It is running on GitHub Actions
> CI: remove centos7 from Travis

- criu/cr-restore.c
`(00.113189) Error (criu/cr-restore.c:1476): 4066 stopped by signal 11: Segmentation fault`
seems a bit better than
`(01.012320) Error (criu/cr-restore.c:1480): 11953 killed by signal 127: Unknown signal 127`
> cr-restore: Properly inspect status in sigchld_process()

- criu/uffd.c
We can't use errno in case read returned >=0 according to man.
Found in scope of #1277
> uffd: cleanup read error handling in handle_uffd_event

- .gitignore
- scripts/build/Dockerfile.centos8
Recently started to fail on criu-dev
> GitHub Actions: Fix Centos8 build

- .circleci/config.yml
- .travis.yml
- scripts/ci/run-ci-tests.sh
Circle CI provides bare metal test systems which are a very good environment for the CRIU test cases. This adds two CI runs on Circle CI.
> CI: Add Circle CI definition

- .github/workflows/alpine-test.yml
- .travis.yml
I had to disable the fault injection tests as they do no longer seem to work. Something during the last weeks, when Travis was not running broke fault injection.
> Switch Alpine to GitHub Actions

- test/zdtm_ct.c
This is a temporary workaround for a kernel issue that has to be fixed
in the 5.11 kernel.
start_time in /proc/pid/stat is printed in the host time namespace,
but /proc/uptime is shown in a current namespace, but criu compares them
to detect when a new task has reused one of old pids.
https://github.com/checkpoint-restore/criu/issues/1266
> test/zdtm_ct: Run zdtm.py in the host time namespace

- test/zdtm/transition/thread-bomb.c
1) Let's do test_init earlier so that max_nr test_msg is now visible in
thread-bomb.out.
2) Also lets check errors from malloc and pthread_...  functions, print
messages about their errors and do proper deallocation at least.
> zdtm: cleanup thread-bomb test error handling and printing

- criu/sk-unix.c
- include/common/bug.h
> Fix compile time warnings

- lib/py/images/images.py
This fixes the next errors in the Jenkins crit-recode test runs.
> More Jenkins crit-recode fixes

- criu/pstree.c
Previously we only skipped replacing sid for shell job if root_item was
session leader, but there is other case where root_item sid is the same
as current_sid we can safely skip replacing for this case. Same applies
to gid-s.
Now after we have pid collision check we not only "can" but should skip
pid collision checks for the latter case. It is quite obvious that
there are tasks in tree with sid==current_sid if current_sid==old_sid.
Fixes: #1400
Fixes: 77968d43c ("pstree: check for pid collision before switching to
new sid/gid")
> pstree: don't change sid/gid-s if current sid/gid is the same

- criu/cr-check.c
- criu/include/kerndat.h
- criu/include/net.h
- criu/kerndat.c
- criu/net.c
- test/zdtm/static/Makefile
- test/zdtm/static/cr_veth02.c
- test/zdtm/static/cr_veth02.checkskip
- test/zdtm/static/cr_veth02.desc
- test/zdtm/static/cr_veth02.hook
Send an RTM_SETLINK request with a negative IFLA_NEW_IFINDEX. If
IFLA_NEW_IFINDEX is supported, the kernel will return ERANGE.
Cc: @brauner
> kerndat: check whether IFLA_NEW_IFINDEX is supported or not

- .cirrus.yml
- criu/cr-check.c
- criu/include/util.h
- criu/net.c
- criu/util.c
- test/zdtm/static/Makefile
- test/zdtm/static/netns-nft-ipt.c
- test/zdtm/static/netns-nft-ipt.desc
- test/zdtm/static/netns-nft.checkskip
- test/zdtm/static/netns-nft.desc
> skip iptables dump if it has nft backend and nft dump is supported

- lib/py/cli.py
- test/others/crit/test.sh
> lib/cli.py: Open explore file as a binary

- criu/crtools.c
Signed-off-by: Valery Ivanov <ivalery111@gmail.com>
> crtools: improve error handling on signal setting

- lib/py/images/images.py
It will broken when the cli `crit show ipcns-shm-9.img` is executed, msg:
```
{
"magic": "IPCNS_SHM",
"entries": [
{
"desc": {
"key": 0,
"uid": 0,
"gid": 0,
"cuid": 0,
"cgid": 0,
"mode": 438,
"id": 0
},
"size": 1048576,
"in_pagemaps": true,
"extra": Traceback (most recent call last):
File "/usr/bin/crit", line 6, in <module>
cli.main()
File "/usr/lib/python3/dist-packages/pycriu/cli.py", line 412, in main
opts["func"](opts)
File "/usr/lib/python3/dist-packages/pycriu/cli.py", line 45, in decode
json.dump(img, f, indent=indent)
File "/usr/lib/python3.9/json/__init__.py", line 179, in dump
for chunk in iterable:
File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
yield from _iterencode_dict(o, _current_indent_level)
File "/usr/lib/python3.9/json/encoder.py", line 405, in …
```
> pycrit: fix the broken of cli the `crit show ipcns.img`

- lib/py/cli.py
Else we get error:
[root@fedora criu]# crit/crit x test/dump/zdtm/static/memfd00/56/1/ mems
...
Traceback (most recent call last):
File "/home/snorch/devel/ms/criu/crit/crit", line 6, in <module>
cli.main()
File "/home/snorch/devel/ms/criu/crit/pycriu/cli.py", line 430, in main
opts["func"](opts)
File "/home/snorch/devel/ms/criu/crit/pycriu/cli.py", line 361, in explore
explorers[opts['what']](opts)
File "/home/snorch/devel/ms/criu/crit/pycriu/cli.py", line 283, in explore_mems
fn = ' ' + get_file_str(opts, {
File "/home/snorch/devel/ms/criu/crit/pycriu/cli.py", line 214, in get_file_str
f = ft['get'](opts, ft, fd['id'])
File "/home/snorch/devel/ms/criu/crit/pycriu/cli.py", line 165, in ftype_reg
rf = ftype_find_in_image(opts, ft, fid, 'reg-files.img')
File …
> crit: fix error on memfd files parsing

- lib/py/images/images.py
- scripts/ci/run-ci-tests.sh
Also add tcp stream crit recoding to CI.
> Fix recode test

- criu/cgroup.c
> cgroup: cgroup_contains has to update the mask for cgroupv2

- scripts/ci/docker-test.sh
In the current test for docker, we create a single container that is checkpoint/restore it 50 times sequentially. It is fairly uncommon (and not very useful) to checkpoint a container immediately after restore. We have seen the following error from containerd that occurs when trying to checkpoint a container immediately after restore:
```
Error response from daemon: Cannot checkpoint container cr: content sha256:12c69b7a9d25695dd5f9d37d4e858e2f7c3f9da738ccf86f8d3042f6973af1df: already exists
```
This PR aims to address the error above by modifying the test to remove the container after restore. Thus, it would use a new container for each checkpoint/restore test iteration.
> docker-test: refactor test scenario

- criu/crtools.c
> remove tls parameter description if without GnuTLS support

- criu/net.c
Previously, `open_image(CR_FD_RULE, O_RSTR, pid)` was called twice.
Opening an image file twice is not allowed when streaming the image.
This commit optimizes the code to only open the image file once.
Also improved the error path in restore_ip_dump().
> net: optimize restore_rule() to avoid opening the CR_FD_RULE image file twice

- test/zdtm.py
When exceptions are raised during testing, the image streamer process should be terminated as opposed to being left hanging.
> tests: improve the image streamer process control

- test/zdtm.py
We see that tests mntns_ghost01 and unlink_fstat03 can run
simultaneousely and thus the former sees leftover link_remap.* files in
the test directory created by the latter, and the latter is still
running so it's ok to have link_remap.* at this point.
Let's implicitly make all --link-remap tests exclusive (not running in
parallel).
Fixes: #1633
> zdtm.py: make tests with --link_remap exclusive

- test/zdtm.py
Various I/O objects are unclosed when the object falls out of scope.
This can lead to non-deterministic behavior.
> tests: improve the deterministic behavior of the test suite

- criu/seize.c
Now if criu dump failed before freezing dumpee, criu always freeze
dumpee in cr_dump_finish.
> seize: restore cgroup freezer to right state

- criu/crtools.c
> crtools: ignore SIGPIPE in swrk mode

- criu/files-reg.c
- criu/include/fs-magic.h
**What this PR does**
Fixes an issue with dumping deleted reg files in overlayfs:
After deleting a file originated from lower layer in merged dir, `fstat()` on the `/proc/$pid/map_files` symlink returns `st_nlink=1`, while `linkat()` fails with errno `ENOENT`.
criu: v3.16.1
kernel: 5.4.119 
**How to reproduce it**
1. start a docker container with overlay2 and run a process that `mmap()` any file from lower layer
2. inside the container, delete the mapped file so that it shows `(deleted)` in /proc/$pid/map_files
3. try dump the container, it ends up with dump.log like following: 
```
(00.111612) Dumping path for -3 fd via self 14 [/foo (deleted)]
(00.111616) Strip ' (deleted)' tag from './foo (deleted)'
(00.111632) Warn  (criu/files-reg.c:1718): Can't link  -> ./link_remap.5
(00.111635) …
```
> files-reg: try dump_ghost_remap if link-remap failed with error ENOENT

- criu/util.c
The function run_tcp_server() was the last place CRIU was still using the IPv4 only function inet_ntoa(). It was only used during a print, so that it did not really break anything, but with this commit the output is now no longer:
` Accepted connection from 0.0.0.0:58396`
but correctly displaying the IPv6 address
` Accepted connection from ::1:58398`
if connecting via IPv6.
> util: make page-server IPv6 safe

- criu/tls.c
This pull request contains minor improvements to the code in `tls.c`.
> tls: minor improvements

- criu/include/tls.h
- criu/page-xfer.c
- criu/tls.c
- criu/uffd.c
- scripts/ci/run-ci-tests.sh
- test/zdtm.py
- test/zdtm/static/uffd-events.c
> uffd: call disconnect_from_page_server to shutdown a page-server connection

- scripts/ci/run-ci-tests.sh
All the bugs that were in the way got fixed. We can enable all tests.
> ci: test criu-image-streamer with all tests

- CONTRIBUTING.md
- README.md
This pull request updates the links of badges in `CONTRIBUTING.md`.
> contributing: update links in badges

- scripts/ci/vagrant.sh
update to latest Vagrant and Fedora images
> ci: update to latest Vagrant and Fedora images

- criu/pagemap.c
When requested iovs are huge, criu needs to invoke more then one
preadv()s. In this situation criu truncates memory image with
offset of first preadv() and length of last one, which leads
to leakage of memory image. This patch fixs truncating with right
offset and length.
> pagemap: tiny fix on truncating memory image

- Documentation/criu.txt
Signed-off-by: Ashutosh Mehra <asmehra@redhat.com>
> Fix formatting in criu documentation

- scripts/criu-ns
> criu-ns: fix exit code for criu dump

- criu/cr-dump.c
coverity CID 389194:
```
1238static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
1239{
...
1245        struct cr_imgset *cr_imgset = NULL;
...
11. alloc_fn: Storage is returned from allocation function cr_task_imgset_open. [show details]
12. var_assign: Assigning: cr_imgset = storage returned from cr_task_imgset_open(vpid(item), 577).
1355        cr_imgset = cr_task_imgset_open(vpid(item), O_DUMP);
13. Condition !cr_imgset, taking false branch.
1356        if (!cr_imgset)
1357                goto err_cure;
1358
...
25. Condition opts.lazy_pages, taking false branch.
1427        if (opts.lazy_pages)
1428                ret = compel_cure_remote(parasite_ctl);
1429        else
1430                ret = compel_cure(parasite_ctl);
26. Condition ret, taking true …
```
> cr-dump: fix cr_imgset leak in dump_one_task

- criu/tun.c
coverity CID 389205:
```
452int dump_tun_link(NetDeviceEntry *nde, struct cr_imgset *fds, struct nlattr **info)
453{
...
458        struct tun_link *tl;
...
2. alloc_fn: Storage is returned from allocation function get_tun_link_fd. [show details]
3. var_assign: Assigning: tl = storage returned from get_tun_link_fd(nde->name, nde->peer_nsid, tle.flags).
475        tl = get_tun_link_fd(nde->name, nde->peer_nsid, tle.flags);
4. Condition !tl, taking false branch.
476        if (!tl)
477                return ret;
478
479        tle.vnethdr = tl->dmp.vnethdr;
480        tle.sndbuf = tl->dmp.sndbuf;
481
482        nde->tun = &tle;
CID 389205 (#1 of 1): Resource leak (RESOURCE_LEAK)5. leaked_storage: Variable tl going out of scope leaks the storage it points to.
483        return …
```
> tun: fix tun_link leak in dump_tun_link

- compel/src/main.c
* I am new here to learn criu, here is some codereview fix.
> Style: delete some redundant code

- README.md
This commit adds a link to the workflow runs for each badge.
> readme: Add badge links to workflows

- criu/kerndat.c
- test/zdtm.py
- test/zdtm/static/maps09.checkskip
- test/zdtm/static/maps10.checkskip
> hugetlb: properly handle case when not supported

- plugins/amdgpu/.gitignore
This pull request adds .gitignore file for auto-generated files in `plugins/amdgpu`.
> amdgpu: Add gitignore

- criu/arch/x86/cpu.c
- criu/arch/x86/crtools.c
- criu/cr-check.c
- criu/unittest/mock.c
- plugins/amdgpu/amdgpu_plugin.c
- test/zdtm/static/inotify_system.c
This pull request contains auto-generated changes from `make indent` that fix the CI lint error.
> ci: Fix code indent

- .github/workflows/lint.yml
- Makefile
- Makefile.install
- criu/arch/x86/cpu.c
- criu/arch/x86/crtools.c
- criu/cr-check.c
- criu/include/page-xfer.h
- criu/include/plugin.h
- criu/mount-v2.c
- criu/page-pipe.c
- criu/page-xfer.c
- criu/unittest/mock.c
- criu/util.c
- plugins/amdgpu/Makefile
- plugins/amdgpu/amdgpu_plugin.c
- scripts/ci/run-ci-tests.sh
- scripts/crit-setup.py
- test/zdtm/static/Makefile
- test/zdtm/static/inotify_system.c
- test/zdtm/static/mnt_ext_multiple.c
- test/zdtm/static/mnt_ext_multiple.desc
- test/zdtm/static/mnt_root_ext.c
- test/zdtm/static/mnt_root_ext.desc
- test/zdtm/static/mnt_root_ext.hook
A couple of commits cherry-picked to fix a few bug reports from users in the current 3.17 release.
Fixes: #1886
CC: @Snorch @avagin
> Release 3.17.1

- compel/arch/x86/src/lib/infect.c
Error from:
./test/zdtm.py run -t zdtm/static/fpu00 --fault 134 -f h --norst
(00.003111) Dumping GP/FPU registers for 56
(00.003121) Error (compel/arch/x86/src/lib/infect.c:310): Corrupting fpuregs for 56, seed 1651766595
(00.003125) Error (compel/arch/x86/src/lib/infect.c:314): Can't set FPU registers for 56: Invalid argument
(00.003129) Error (compel/src/lib/infect.c:688): Can't obtain regs for thread 56
(00.003174) Error (criu/cr-dump.c:1564): Can't infect (pid: 56) with parasite
See also:
145e9e0d8c6 ("x86/fpu: Fail ptrace() requests that try to set invalid MXCSR values")
https://github.com/torvalds/linux/commit/145e9e0d8c6fada4a40f9fc65b34658077874d9c
Reported-by: Mr. Jenkins
Signed-off-by: Alexander Mikhalitsyn <alexander.mikhalitsyn@virtuozzo.com>
> x86/compel/fault-inject: cleanup mxcsr for PTRACE_SETFPREGS

- scripts/ci/docker-test.sh
There is a race condition in docker/containerd that causes docker to occasionally fail when starting a container from a checkpoint immediately after the checkpoint has been created. This problem is unrelated to criu and has been reported in https://github.com/moby/moby/issues/42900
> docker-test: handle race condition error

- compel/arch/aarch64/src/lib/include/uapi/asm/breakpoints.h
- compel/arch/aarch64/src/lib/infect.c
- compel/arch/x86/src/lib/infect.c
- compel/include/ptrace.h
- compel/include/uapi/infect.h
- compel/src/lib/infect.c
- compel/src/lib/ptrace.c
- criu/cr-restore.c
- criu/include/fault-injection.h
This is slightly reworked #1815. @time-river, could you review it?
> breakpoint: implement hw breakpoint for arm64 platform 

- criu/seize.c
> seize: do not overwrite exit code from failpath

- test/zdtm/static/s390x_regs_check.c
Signed-off-by: Shubham Verma <shubhamv.sv@gmail.com>
> Fix typo in comment

- criu/cgroup.c
memory.kmem.limit_in_bytes has been deprecated. Look at e7c4184164f7 ("memcg, kmem: further deprecate kmem.limit_in_bytes") for more details.
> cgroups: ignore EOPNOTSUPP on setting memory.kmem.limit_in_byte

- criu/log.c
This is a backport of:
https://src.openvz.org/projects/OVZ/repos/criu/commits/8e6bc1aeb
Signed-off-by: Cyrill Gorcunov <gorcunov@virtuozzo.com>
> log: Write more details in write_pidfile

- criu/mount.c
- criu/namespaces.c
Checking errno in outer function is really strange, also saving errno of mount syscall after calling pr_perror is completely wrong. So let's try to simplify things.
> mount: simplify code around mount_cr_time_mount

- compel/src/main.c
> compel/mips: fix parasite with GCC 12

- .mailmap
> mailmap: update my email

- Makefile
- lib/py/images/images.py
This pull request proposes approaches to reduce code duplication in `lib/py/images/images.py`.
Fixes: #340
> lib/py: Reduce code duplication

- criu/cr-check.c
- criu/include/util.h
- criu/net.c
- criu/util.c
Without this we might try to restore iptables legacy images with iptables nft.
> net: use get_legacy_iptables_bin also on restore

- CONTRIBUTING.md
This pull request documents how do we use `make lint` and `make indent` and adds a note about their integration with CI.
> CONTRIBUTING.md: document make lint / indent

- criu/pstree.c
First, let's move lookup_create_item-s to the end so that on pgid replacement we don't have false positive pstree_pid_by_virt check founding item created by sid replacement. (note: we need those lookup_create_item-s for the sake of free pid selection mechanism)
Second, let's add checks for sid/pgid in images intersecting with current_sid/pgid, as this would also bring problems on restore.
(second part is similar to what we already do in Virtuozzo criu here https://src.openvz.org/projects/OVZ/repos/criu/commits/23448a763)
> pstree: improve id intersection detection in prepare_pstree_for_shell_job

- criu/net.c
For better logging.
It is a port of https://src.openvz.org/projects/OVZ/repos/criu/commits/ea981a7f1
CC: @cyrillos
> net: Add net log prefix

- criu/sk-unix.c
> Sk unix cleanup unix resolve name

- test/zdtm/transition/rseq01.c
Kernel shouldn't clean up rseq_cs inside a critical section.
If rseq_cs has been cleaned up, it means there is a bug in migration.
> zdtm: don't ignore rseq_cs mismatch in rseq01 test

- criu/sk-inet.c
- images/sk-inet.proto
- test/zdtm/static/sock_ip_opts00.c
DUMP and restore the TOS option
> sk-inet: Add IP TOS socket option

- .codespellrc
- compel/arch/aarch64/src/lib/include/uapi/asm/sigframe.h
- compel/arch/ppc64/src/lib/include/uapi/asm/sigframe.h
- criu/include/image.h
- criu/mem.c
- criu/mount.c
- criu/namespaces.c
- criu/net.c
- criu/pie/restorer.c
- flog/include/uapi/flog.h
- include/common/scm.h
- plugins/amdgpu/README.md
- plugins/amdgpu/amdgpu_plugin_topology.c
- scripts/install-debian-pkgs.sh
- test/exhaustive/unix.py
- test/others/app-emu/java/HelloWorld/run.sh
- test/others/app-emu/make/run.sh
- test/zdtm/static/child_opened_proc.c
- test/zdtm/static/maps00.c
- test/zdtm/static/mntns_root_bind.c
- test/zdtm/static/stopped.c
- test/zdtm/transition/ipc.c
- test/zdtm/transition/lazy-thp.c
Fixes an error in CI during `make lint`.
> Fix CI errors (shellcheck,  codespell)

- criu/action-scripts.c
- criu/img-streamer.c
- criu/include/action-scripts.h
This pull request adds a new action-script hook `pre-stream`. This hook allows to start image streamer process from an action script.
> action-scripts: add pre-stream hook

- criu/kerndat.c
kerndat_has_ipv6_freebind creates a socket but doesn't close it.
> kerndat: don't leak a socket file descriptor

- criu/pie/restorer.c
While each preadv() is followed by a fallocate() that removes the data range from image files on tmpfs, temporarily (between preadv() and fallocate()) the same data is in two places; this increases the memory overhead of restore operation by the size of a single preadv. Uncapped preadv() would read up to 2 GiB of data, thus we limit that to a smaller block size (128 MiB).
> Put a cap on the size of single preadv in restore operation.

- criu/cgroup.c
Sometimes due to sigblockmask inheritance cgroupd can inherit SIGTERM blocked. That will lead cgroupd ignoring SIGTERM from stop_cgroupd() and CRIU will get stuck due to waiting for never-stopping cgroupd.
I see this happening in lxc-checkpoint, also saw this in OpenVZ jenkins on cgroup_inotify00 test.
> cgroupd: unblock SIGTERM to make stop_cgroupd actually work

- scripts/uninstall_module.py
The `uninstall_module.py` script is a wrapper for the `pip uninstall` command that enables support for specifying installation prefix (i.e., `--prefix`). When this functionality is used, we intentionally set `sys.path` to include only search paths for the specified prefix to avoid unintentional uninstallation of packages in system paths.
Since `importlib_metadata` version 8.1.0, the `Distribution.from_name()` method has been modified [^1] to perform additional pre-processing of Distribution objects [^2] that requires loading distribution metadata and results in the following error:
```
File "/usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py", line 422, in <lambda>
buckets = bucket(dists, lambda dist: bool(dist.metadata))
^^^^^^^^^^^^^
File …
```
> scripts/uninstall_module: fix package discovery

- criu/pstree.c
Signed-off-by: Han-Wen Nienhuys <hanwen@engflow.com>
> pstree: print clone flags in error message

- test/zdtm/static/vdso02.c
It is a part of vvar and this test intends to unmap vdso and all vvar mappings.
Fixes #2622
> zdtm/vdso02: unmap vvar_vclock mappings

- criu/namespaces.c
free_userns_maps is called to clean up uid/gid map when the dump finishes. If we try to clean up these maps in error cases, it can lead to double free panic. So just skip cleaning up these maps and let free_userns_maps do its job.
Fixes: #2483
> namespace: skip cleaning up the uid/gid map in error cases

- criu/arch/s390/crtools.c
Currently we save FP regs before parasite code runs, and restore after for --leave-running, --check-only, and in case of errors. In case of errors the error may have happened before FP regs were saved, so we should only restore them if they were actually saved.
> s390: Fix FP reg restore after parasite code runs

- CONTRIBUTING.md
- flake.lock
- flake.nix
> feat: add Nix flake

- scripts/ci/docker-test.sh
This change modifies the CI script to avoid Docker version 28, which has a known regression that breaks Checkpoint/Restore (C/R) functionality. The issue is tracked in the moby/moby project as
https://github.com/moby/moby/issues/50750.
> ci: avoid Docker 28 due to regression

- test/zdtm/static/Makefile
- test/zdtm/static/sk-unix-restore-fs-share.c
- test/zdtm/static/sk-unix-restore-fs-share.desc
This pull request adds a ZDTM test case based on the patch in https://github.com/checkpoint-restore/criu/pull/2742#issuecomment-3327840816
> zdtm: add sk-unix-restore-fs-share test
